### ISSUE TITLE
About non-valid geometries

### ISSUE THREAD

**Issue by etiennebr** [edzer/sfr#101]
First, @edzer I just want to say how excited I am about this package. I think it's a great project, especially much-needed support for 3D features ! S3 structure is also great. I'm sorry I haven't found that package earlier. I see the first commits are already one year-old !

Going through the [SF1 vignette](https://github.com/edzer/sfr/blob/master/vignettes/sf1.Rmd), I think it would be relevant to specify that non-valid geometries can exist and be useful, however it means we can only apply a limited set of spatial operations to them. For instance modelling a shuttle's trajectory could lead to self-intersection, but still be a valid representation.

**Comment by edzer** [comment]
Thanks Etienne! Easier to read vignettes [here](https://edzer.github.io/sfr/), under Articles.

Regarding non-valid or non-simple geometries: they can exist, it is just that some GEOS functions may dislike them, and stop functioning. GEOS is limited to 2D geometries, so is not particularly useful for 3D stuff.

Integrating with rasters is the next big thing - your ideas are welcome!
