### ISSUE TITLE
limits on geometric-dimension mixing?

### ISSUE THREAD

**Issue by mdsumner** [edzer/sfr#103]
The rules for which topological types are allowed within a feature are quite clear, pretty much anything goes including empty GEOMETRYCOLLECTION but only one GEOMETRYCOLLECTION per feature. 

What about a mix of "XY" and "XYZ" geometric-dimensions within a feature? Within an sf object? 

It seems a bit perverse to allow either, with an implication that any explict XY would implicitly be XYZ but with a missing value for Z. 

I see that mixing is not allowed when collecting geometries: 

```R
st_sfc(st_point(c(1,2,3)), st_point(c(1,2), "XY"))
Error in st_sfc(st_point(c(1, 2, 3)), st_point(c(1, 2), "XY")) : 
  found multiple dimensions: XYZ XY
```

But with points we can mix them with implicit casting to multipoint, and with a warning recycling occurs:
 
```R
 c(st_point(c(1,2,3)), st_point(c(.001,2), "XY"))
MULTIPOINTZ(1 2 3, 0.001 2 0.001) 
Warning message:
In (function (..., deparse.level = 1)  :
  number of columns of result is not a multiple of vector length (arg 2)
```

This is not allowed for matrix based geometries: 

```R
m <- rbind(c(0,3),c(0,4),c(1,5),c(2,5))
c(st_linestring(m), st_linestring(cbind(m, 1)))
Error in MtrxSet(x, dim, type = "MULTILINESTRING", needClosed = FALSE) : 
  matrices having unequal number of columns

c(st_multipoint(m), st_multipoint(cbind(m, 1)))
Error in (function (..., deparse.level = 1)  : 
  number of columns of matrices must match (see arg 2)
```

I considered that NA should be inserted rather than recyling, but I also expected that NA would trigger an error and it does not. 

```R
st_point(c(1, NA))
```

It seems XYZ wins over XYM despite input order: 

```R
st_sfc(c(st_point(c(1, 2, 3), "XYM"), st_point(c(1,2,3))))
```

I'm unclear on whether this kind of mixing is desirable, I think it definitely shouldn't be within a feature, but I'm not sure about in one sf object, across features. 

Also, I'm not anticipating an influx of rogue mixing-constructors here, just unsure what the policy is, and I think ` c(st_point(c(1,2,3)), st_point(c(.001,2), "XY"))` needs to error out like linestring does when faced with a mix of input dimensions .

**Comment by edzer** [comment]
Thanks. I am not sure whether I correctly interpret the SF standard that `GEOMETRYCOLLECTION` geometries cannot have `GEOMETRYCOLLECTION`s as a component - it would help if someone could double check.

I first want to see a strong use case in favor of mixing e.g. `XY` and `XYZ` geometries, I'm not the kind of person who gets excited only by the idea that this would be possible: what would it mean to support this?  

Re: `NA` values: In `sp`, we've always forbidden `NA` in geometries, and I still find that one of the best decisions ever. The case for `st_point` is somewhat different (and I may still change it):
```
> st_point()
POINT(NA NA) 
> st_multipoint()
MULTIPOINT() 
```
the issue is that there is not a (proper) WKB representation of an empty point, as opposed to all other geometry types. `GPKG` takes a point with `NA` values (of some sort!). Of course I could make an `st_point()` a `numeric(0)` as data, but that doesn't correspond to the SF standard that points are either `XY`, `XYZ`, `XYM` or `XYZM`. I think they overlooked it when writing the standard. Ideas welcome!

**Comment by mdsumner** [comment]
On the XY/XYZ thing I see 

```
Each geometric object is associated with a Spatial Reference System, which describes the coordinate space in which the geometric object is defined. 
```

which to me is enough, if there's a set-wide SRS then it has to include the Z with the XY if present. If there's a SRS on every feature, it could be different. (Manifold's Geom includes the projection for exactly this reason, so that they are self-contained in a database-context and carry their unit/metadata with them).

I think it's reasonable, and sane, to disallow geometric dimension mixing. There's nowhere to store the metadata for Z (if it's not in the SRS) or M (at all) other than in arbitrary R attributes, right?  

It looks like at least some systems allow nested GEOMETRYCOLLECTION: 

http://gis.stackexchange.com/questions/63784/can-a-geojson-geometrycollection-contain-another-collection

or that it was never finally decided: 

http://www.ogcnetwork.net/node/1029

I think it's reasonable to disallow them, I think other kinds of structure would be much more useful, and that any nested set of GEOMETRYCOLLECTIONs would provide no more structure than a flat list in a single GC. 

I'm looking at http://www.opengeospatial.org/standards/sfa 

Is it important to obtain a copy of the ISO 19125-1:2004 ? We probably have access via our department or I could chase that up if necessary. 

I'm not sure about the point thing, it's a shame that's not consistent.

**Comment by edzer** [comment]
Thanks! PostGIS also supports unique SRS per feature geometry; it is a design decision that we don't go that lane, and I think a pretty sane one.

I never touched the ISO doc - a waste of money?

**Comment by mdsumner** [comment]
Yes, sf is a meaningful layer of these geometries - not an arbitrary bag of any kind of geom blob that a database might deliver. I've just realized that's a helpful way to think about this. I think a nested GEOMETRYCOLLECTION would be a meaningless bag too.  As a layer, we could push sf XYZ into rgl scenes, and being required to have the Z to do that, even if they are all zero, is probably a good idea.  

Probably a waste, I'm just confused about what it is.

**Comment by edzer** [comment]
How can we check that a crs set to a XYZ is a three-dimensional crs?

**Comment by mdsumner** [comment]
Not sure but I'll have a look around. Sometimes I get mixed up with what Eonfusion could do, there you explicitly set a crs on two or three columns - maybe if it's XYZ it's assumed to apply collectively.

**Comment by edzer** [comment]
[this](http://www.gdal.org/classOGRSpatialReference.html#ac16afe94b0d129c0b47e04a6f8b78bef)?

**Comment by mdsumner** [comment]
I'd like to create some to explore more, I though this would work to transform to XYZ: 

```R
example(st_read)
st_transform(nc, "+proj=geocent +ellps=WGS84")
```

I also tried more directly: 

```R
st_multipolygon(nc$geometry[[1]], dim = "XYZ")

```

I presume we have to unpick the structure and rebuild to put in the Z? (Does this fit anywhere else already?)

```
## cast to XYZ by unpicking all component matrices, binding z = 0
example(st_read)

ncz <- nc
st_geometry(ncz) <- st_sfc(lapply(nc$geometry, function(x) st_multipolygon(rapply(x, classes = "matrix", f = function(a) cbind(a, 0), how = "replace"), dim = "XYZ")), crs = st_crs(nc))
ncz <- st_transform(ncz, "+proj=geocent +ellps=WGS84")
```

**Comment by edzer** [comment]
That looks really cool! Do we need a convenience function to add Z and set it to a constant (default 0)?

**Comment by mdsumner** [comment]
I think both of those are good ideas. 

It reminds I haven't checked what this means in simple features, I get the impresssion that some use the Z as an *offset* value, as an extrusion from the surface - it's a nice interpretation for that use-case, but I don't think it's what was intended. It seems to me that all Z's on a polygon feature must either be constant, or at least co-planar, since there's no "bendiness" between the rings, and that's what the triangles and surface forms are for.

**Comment by edzer** [comment]
`+proj=geocent` seems to not be a vertical datum, but rather give you the XYZ coordinates of points on the ellipse, it should work from long/lat only.

When looking in the epsg table, e.g. I see
```
# NTF (Paris) / Lambert zone II + NGF-IGN69 height
<7421> +proj=lcc +lat_1=46.8 +lat_0=46.8 +lon_0=0 +k_0=0.99987742 +x_0=600000 +y_0=2200000 +a=6378249.2 +b=6356515 +towgs84=-168,-60,320,0,0,0,0 +pm=paris +units=m +vunits=m +no_defs  <>
```
but
```
> sf:::crs_pars(st_crs(7421))
$SemiMajor
6378249 m

$InvFlattening
[1] 293.466

$units_gdal
[1] "Meter"

$IsVertical
[1] FALSE

$ud_unit
1 m

```
@rsbivand do you have experience with vertical datums?

**Comment by mdsumner** [comment]
Oh yes sorry, I wasn't thinking clearly about it. It does work from projected coords as well, in the usual transform-to-target way.

**Comment by rsbivand** [comment]
No, no experience of vertical datums. I think that [GRASS](https://grasswiki.osgeo.org/wiki/GIS_Concepts) may have, as they did work on 3D rasters. It rather looks, though, that they haven't touched that for some time - maybe it just works? I guess that working with LiDAR would imply the need to register to a vertical datum - maybe there's something there?

**Comment by etiennebr** [comment]
I'd like to cast a vote for flexibility, although I understand this involves a lot more complexity and a greater effort to keep interfaces clean. I know this is not the current implementation, and it might not be a priority. I'd like to provide an example of collecting heterogeneous data. Having the flexibility to store whatever data in a tidy format really helps. 

I have a project where I receive data from multiple sources (gps, digitization, ...) and multiple parts of the world. I prefer to store data in the original format and run `st_transform()` to latlong when e.g. mapping it at the world scale. This requires per-feature srid support.

Per-feature srid is possible in Postgis, however in my example the data sometimes requires exotic massages to get in a spatial shape (e.g. transform point locations to line using timestamp) and it's much easier to do with R than SQL (or pg/plsql). 

I'm pretty sure having the possibility to store heterogenous dimensions could be useful as well, maybe as a transient state. I have a hard time to figure an analysis tool that could operate on such a dataset without casting to lower dimensions; but maybe I lack imagination. I wonder how Postgis might handle that, but I suspect it might be an incomplete area, which might underscore how difficult it is to support extensively.

**Comment by edzer** [comment]
Let me stress that there is now full flexibility to construct geometry list-columns that have a mix of dimensions, and you could glue CRS (ID, string, or crs objects) to them as attributes, so each of them is unique. This is S3, so there are no rules (as of: formal classes and validation). The only thing is that you can't expect the majority of the functions in `sf` to work with them, sensibly (or meaningfully). You first need to clean up the mess, move to a single dimension and CRS, and then you can continue. I think that is a reasonable requirement. If PostGIS offers something much wilder it doesn't necessarily mean that they thought that this was a good design decision, it can simply mean that a paying customer wanted it. See Paul Ramsey's comment on twitter on the use of `GEOMETRY` as a class for table: you can create them, but there's no software downstream that can do anything with it. Same here. I'm looking forward to see actual use cases, as well as to contributions of this complex yet clean interface.

**Comment by mdsumner** [comment]
@etiennebr You should definitely try these things for yourself, there's no better way to learn and to contribute. If it's outside the scope of sf feel free to ask in other forums or contact me directly.

**Comment by mdsumner** [comment]
> but there's no software downstream that can do anything with it. 

I missed this, being about objects of mixed topology dimension (0D point, 1D line, 2D polygon). There is GDAL,  MapInfo, Manifold, and surely ESRI?  QGIS seems like an exception in this regard, and is unfortunately tied pretty tightly to this limitation shared with shapefiles.   Soon ggplot2, leaflet and mapview will support the equivalent of GEOMETRY. 

Still, simple features itself has no vertex-sharing whatsoever, so it kind of defeats the value in it for a lot of applications with mixed topological types - but I certainly wasn't anticipating how useful it actually is, there's a lot of implications and having this in R opens up a lot of possibilities. 

At any rate, I'm very happy with the balance of (in)-formality and flexibility. This is very good. 

In terms of geometric-dimension, I'm confused about XYZ and what it means for angular coordinates versus planar coordinates versus geocentric coordinates, If there is a guide somewhere it would be excellent. 

I'm following up with some tests for XY / XYZ.

**Comment by edzer** [comment]
Geodesists know what a vertical datum means; see also [here](https://github.com/OSGeo/proj.4/wiki/VerticalDatums). In my reference systems course, for non-geodesists, I use [Iliffe and Lott](https://www.crcpress.com/Datums-and-Map-Projections-For-Remote-Sensing-GIS-and-Surveying/Iliffe/p/book/9780849308840).

**Comment by edzer** [comment]
See also [this thread](https://lists.osgeo.org/pipermail/gdal-dev/2011-August/029856.html)

**Comment by edzer** [comment]
With this commit, we get
```
> library(sf)
Linking to GEOS 3.5.0, GDAL 2.1.0, proj.4 4.9.2
> st_transform(st_sfc(st_point(c(0,0)), crs=4326), st_crs("+proj=geocent"))
Geometry set for 1 feature 
geometry type:  POINT
dimension:      XYZ
bbox:           xmin: 6378137 ymin: 0 xmax: 6378137 ymax: 0
epsg (SRID):    NA
proj4string:    +proj=geocent +ellps=WGS84 +units=m +no_defs
POINTZ(6378137 0 0)
```
i.e., 2D (long/lat) -> 3D (x/y/z), but only when we have +proj=geocent. 

It also fixes a bug where all xyz, xym and xyzm data were (partially?) cut back to xy when passed to gdal internals; see gdal.cpp.
