### ISSUE TITLE
better str for sfc

### ISSUE THREAD

**Issue by faridcher** [edzer/sfr#104]
`str` tended to be a useful command before making sf object out of dataframe. I think a better `str` function for sf deserves attention. right now it prints the whole list structure of sfc object! 
`options(max.print = x)` would work but affects the behavior of `str` on other objects

**Comment by edzer** [comment]
@faridcher close this one now?

**Comment by faridcher** [comment]
I see you have merged my commit for this function; so yes, feel free to close it.
thanks
