### ISSUE TITLE
faster travis?

### ISSUE THREAD

**Issue by mdsumner** [edzer/sfr#107]
I'd like to have a fast travis build that just installs everything as binary, or that builds a minimal GDAL source. 

Has anyone tried that? I've tried but not been successful, is it worth sharing the attempts?  It would be of interest for package developers hoping to rely on sf.

**Comment by nuest** [comment]
You could try out to create a Docker container wir all the libs and R and use that to execute the test. Downloading the image tarball from Docker Hub should be faster than Travis installing everything.

**Comment by edzer** [comment]
See also [here](https://github.com/ropensci/geojsonio/issues/41#issuecomment-251207194). Nice to have, but I see this as a travis issue, not an sfr issue. They have a repo where you can apply for your ppa to be appended to their trusted ppa's, iirc.

**Comment by mdsumner** [comment]
Thanks! I had no idea it was because of not being able to get the unstable binaries.

**Comment by mdsumner** [comment]
Just FYI anyone. 

I finally got this, down to about 3min with all binary installs on Ubuntu "trusty" (14.04). 

https://github.com/dis-organization/depsf/blob/binary/.travis.yml

See here for shortcuts:  https://github.com/ropensci/rgbif/blob/master/.travis.yml 

but also see the GDAL suite for a more comprehensive overview with all kinds of builds: https://github.com/OSGeo/gdal

**Comment by edzer** [comment]
Thanks. Regrettably, I can't get this to work with PostGIS (dependency clash), which would cause a steep drop in code coverage.
