### ISSUE TITLE
CRS with added +init=epsg: slot if known

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#11]
The thread at

https://lists.osgeo.org/pipermail/gdal-dev/2016-May/044474.html

shows that interoperability is harmed when only the p4s is used, not the epsg code (which has authority tags). Could we add an epsg code slot to CRS, default NA, but used when exporting data to resolve to a WKT representation with authority tags?

**Comment by edzer** [comment]
`sfc` objects now have attributes `epsg` (integer) and `proj4string` (character). These should be managed by `st_crs` and `st_crs<-`. Reading data through GDAL however never gives you the epsg ID, it seems, but directly reading EWKB from PostGIS may do so. Haven't tried other spatial databases so far.

**Comment by edzer** [comment]
Update: `sfc` objects now have an attribute `crs` which is a list of class `crs` with list elements `epsg` (length one integer vector: epsg code or NA_integer_) and `proj4string` (length one character vector).

**Comment by edzer** [comment]
we need a vignette on CRS, demonstrating that EPSG's change, and there is not a 1:1 match between all proj4strings and EPSG.
