### ISSUE TITLE
`CPL_crs_pars()` not always return list of 4

### ISSUE THREAD

**Issue by faridcher** [edzer/sfr#111]
```r
nc <- st_read(system.file("shape/nc.shp", package="sf"), "nc", crs = 4267)
sf:::CPL_crs_pars(st_crs(nc)$proj4string)
```
when `crs_pars` is called within `st_distance`:
`sf:::crs_pars(st_crs(nc))`

throws the following error:

> Error in structure(CPL_crs_pars(x$proj4string), names = c("SemiMajor",  : 
>   'names' attribute [4] must be the same length as the vector [3]

**Comment by edzer** [comment]
Sounds like you need to reinstall; no such issue on my side.
