### ISSUE TITLE
Installing sf on a Mac

### ISSUE THREAD

**Issue by behrman** [edzer/sfr#116]
I hope to use sf in a Stanford class I will be teaching starting in Jan. I'm working on instructions for the students to installing sf on a Mac.

The steps I've followed thus far are
1) Install the following frameworks from http://www.kyngchaos.com/software/frameworks
* GDAL 2.1 Complete, including NumPy
* GSL
* FreeType
* cairo
2) Add to ~/.bash_profile
export PATH="$PATH:/Library/Frameworks/GDAL.framework/Programs"
3) install.packages("rgdal")
4) devtools::install_github("edzer/sfr")

After 2), I get from the command line
% gdal-config --version
2.1.2
% gdal-config --libs
-framework GDAL
% gdal-config --cflags
-I/Library/Frameworks/GDAL.framework/Versions/2.1/Headers

But after 4), I get
installing *source* package ‘sf’ ...
configure: CC: clang
configure: CXX: clang++
configure: : 
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘sf’

I have no prior experience with sf, and would welcome assistance in installing it, so I can teach others how to.

Many thanks,

Bill

**Comment by behrman** [comment]
If a macOS version of sf will be available soon on CRAN, that's preferable. Our class won't be starting until 2017 Jan 9.

To answer your question, I tried adding two different GDAL paths to .Reviron and got different fatal compilation errors in each case.

With /Library/Frameworks/GDAL.framework/Programs, the errors were

checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... no
ld: framework not found GDAL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: framework not found GDAL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure: Install failure: compilation and/or linkage problems.

With /Library/Frameworks/GDAL.framework/unix/bin, the errors were

checking proj_api.h usability... no
checking proj_api.h presence... no
checking for proj_api.h... no
configure: error: proj_api.h not found in standard or given locations.
ERROR: configuration failed for package ‘sf’

If sf will be ready soon on CRAN, you can close this issue. I'm happy to wait.

Looking forward to using sf. Thanks for all of your hard work in creating it!

Bill

**Comment by edzer** [comment]
CRAN now has a binary MacOSX version of sf. Install with

    install.packages("sf")

or, in case that tries to install from source, use

    install.packages('sf', type='mac.binary.mavericks', dependencies=TRUE)
