### ISSUE TITLE
Another WKT pkg

### ISSUE THREAD

**Issue by sckott** [edzer/sfr#12]
you mention the wkb package in the readme - i maintain another package for working with WKT data https://github.com/ropensci/wellknown just in case you hadn't seen it and it's of any help

**Comment by edzer** [comment]
Thanks @sckott ! Two questions - first: why do you use

    list('type' = 'Point', 'coordinates' = c(116.4, 45.2))

and not for instance

    list(Point = c(116.4, 52.2))

and second, why can the package generate invalid WKT? My understanding of WKT is that 

    point(data.frame(1, 2, 3))

should generate `point z(1 2 3)` or `point m(1 2 3)`, depending on (and indicating what) the 3rd dim means, but not `point(1 2 3)`, however
```
> point(data.frame(1, 2, 3))
[1] "POINT (1.0000000000000000 2.0000000000000000 3.0000000000000000)"
> lint(point(data.frame(1, 2, 3)))
[1] TRUE
```

**Comment by sckott** [comment]
1. first point, agreed, that makes more sense, opened issue for that, as you can see above
2. thanks for pointing that out. I generally haven't taken into account 3d/4d - opened an issue to address that
