### ISSUE TITLE
plot(..., add=TRUE) silently fails when sf has multiple columns

### ISSUE THREAD

**Issue by etiennebr** [edzer/sfr#120]
I don't know enough about the base plot system to exactly pinpoint where it happens, but I suppose that on the second call, when `add=TRUE`, it plots in a different coordinate system, because it goes through plotting without a notice, but side effect -- seeing polygons -- does not happen. For instance, see https://github.com/edzer/sfr/blob/master/tests/dplyr.R#L17, which doesn't work.

**Comment by edzer** [comment]
Thanks! This example predates the version of `plot` that plots all attributes, and doesn't make sense now. Base plot indeed doesn't let you go through each of the plots (AFAICT) and add to them. I modified the example.
