### ISSUE TITLE
`setAs()` has no definition for class `Spatial`

### ISSUE THREAD

**Issue by etiennebr** [edzer/sfr#129]
When sourcing `sp.R` which contains `setAs("Spatial", "sf", ...)`, `setAs("Spatial", "sfc", ...)`, `setAs("sf", "Spatial", ...)` and `setAs("sfc", "Spatial", ...)`. 

```
in method for ‘coerce’ with signature ‘"Spatial","sf"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"Spatial","sfc"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sf","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sfc","Spatial"’: no definition for class “Spatial”
```
It complains on `devtools::load_all(".")` and `devtools::document(roclets=c('rd', 'collate', 'namespace'))`, which both source these functions (well, all `.R` files).

**Comment by edzer** [comment]
These are messages, not warnings or NOTE's, so we can safely ignore them. I'd also like them to go away, but not at the cost of having to import `sp` without a good reason.

**Comment by etiennebr** [comment]
Yes, this is not a good reason to depend on `sp`. I was wondering if you or *someone* knew a way to attach the namespace only when the package is there. I'm not aware of one, and couldn't find one quickly, but I'd be surprised if `sf`was the first to face this.
