### ISSUE TITLE
rgeos:readWKT study case

### ISSUE THREAD

**Issue by pgiraudoux** [edzer/sfr#13]
I am reporting here on Roger Bivand's advise about a strange behaviour with rgeos:readWKT.

Please consider the attached tmp1 variable (just extracted from QGIS attribute table by copy and paste and read.delim from the clipboard). First unzip tmp1.zip

load("tmp1.Rdata")
library(rgeos)
readWKT(tmp1)
readWKT(as.character(tmp1))
readWKT(gsub(" ","",as.character(tmp1)))

In every case I get:

Error: Unable to parse: Polygon ((987298.45400000002700835 6684766.64900000020861626, 987354.71499999996740371 6684746.2369999997317791, 987430.25699999998323619 6684717.31500000040978193, 987477.16800000006332994 6684712.3030000003054738, 987506.0400000000372529 6684709.22500000055879354, 987529.53000000002793968 6684706.72400000039488077, 987571.87600000004749745 6684731.8880000002682209, 987529.01000000000931323 6684831.39400000032037497, 987503.28200000000651926 6684914.84300000034272671, 987479.98499999998603016 6684960.95500000007450581, 987479.231000000028871 6684966.91200000047683716, 987473.37300000002142042 6684977.03500000014901161, 987466.03700000001117587 6684989.57899999991059303, 987531.43599999998696148 6684992.7900000000372529, 987563.93099999998230487 6685019.06400000024586916, 987634.05099999997764826 6685050.60900000017136335, 987679.39800000004470348 6684986.36400000005960464, 987723.43099999998230487 6685007.84599999990314245, 987765.4599999999627471 6685035.6409

Back to the doc, I found that a possible explanation is that as.character breaks lines in language objects at 500 characters, and inserts newlines. 

In our case, I suppose factors may be coerced to character using as.character, thus will not permit WKT description > 500 characters. Now the question is to get a workaround: many spatial objects are described with more than 500 characters in WKT...

[tmp1.zip](https://github.com/edzer/sfr/files/377311/tmp1.zip)

**Comment by edzer** [comment]
I don't think that this is a language object. PostGIS has no problem with reading this string, using `ST_GeomFromText`.

**Comment by pgiraudoux** [comment]
Hmmm. OK.  Actually, yes, probably not a question linked directly to readWKT but to "how to convey properly copy of QGIS attribute table to readWKT via the clipboard?". Will try and work on the issue ASAP.
