### ISSUE TITLE
Iterating over features in shapefiles

### ISSUE THREAD

**Issue by crazycapivara** [edzer/sfr#134]
I often have to deal with large shapefiles. Therefore, a possibility to just open the file and then iterating over the features would be great in order to only select needed features and not loading complete shapefile into memory.

**Comment by crazycapivara** [comment]
I also do, but sometimes I got shapefiles from other sources I do not want to put into the database. Shapefiles are also great as exchange format to share spatial data with others not having access to the database. At the moment I do stuff like this with python, but I really like the way R handles data and would like to stay with one language. But your sfr package is a really cool approach speeding up reading and writing of spatial data in R, with sp I got some limitations regarding this, why I sometime dropped R for spatial stuff.

**Comment by edzer** [comment]
The open-file and iterate approach is found in [rgdal2](https://github.com/thk686/rgdal2), for sfr I do not have plans to implement such a strategy.

**Comment by rsbivand** [comment]
Could you use `gdalUtils::ogr2ogr` first to subset, then follow through with `sf::st_read`? The subsetting criteria would be the same, and `ogr2ogr` supports OGR and other SQL dialects that would be hard to replicate in sf.

**Comment by crazycapivara** [comment]
Yep, you are right, I also considered that approach by using 'system2("ogr2ogr")' because I was not aware of the gdalUtils package which does more or less the same!? I also installed rgdal2 now, which also seems to work fine, are the feature objects compatible with sf?

**Comment by edzer** [comment]
No, the `rgdal2` feature objects are external pointers; when importing, the package does not try to create R representations that are really useful (as of: having a class).

**Comment by crazycapivara** [comment]
Ah, I see. Yes, I also want to work with R representations and I like your data frame way. So, I will do as @rsbivand suggested. Thanx for great work on the sfr package.

**Comment by mdsumner** [comment]
It's *easy enough* to subvert the CPL_read_ogr logic to short-circuit on an iFeature argument and (rebuild sf to test ...), I just tried this by making a copy of CPL_read_ogr, with the Rcpp Export tag,  setting the out-list, poGeometryV, poFeatureV lengths to 1 and skipping the work in the while loop unless i is the number asked for. 

https://github.com/edzer/sfr/pull/135

@edzer Would you consider something like this variant of st_read to short-circuit on one feature?  I'll definitely use this but will just make it external if needed. I want to be able to generate different kinds of database storage from scratch, and not always with a pre-existing OGR source.

**Comment by edzer** [comment]
I can see this could work, and should be easily extendable to reading a given set of features. But how do you determine which set of features you want to read? I understand the demand, but fail to see the complete use case / work flow.

**Comment by mdsumner** [comment]
In my use cases I only need to know the maximum number of features, I want to bite off manageable chunks and push them elsewhere - maybe with tests on the way for the ones to keep track of.  (Another option would be a no-geometry read, so you could find the ones to pull in on subsequent reads based on their attributes - though for some data sources that wouldn't be a performance improvement, necessarily. )

**Comment by edzer** [comment]
OK, we have `st_layers` to do feature counts per layer; manageable chunks sounds like reading sets, rather than single features. For reading attributes, would you want to use `sf_read`, or rather `read.dbf` (OP), or opening a database table straight with `DBI`?

**Comment by mdsumner** [comment]
Admittedly the performance of per-feature read does seem pretty woeful, far worse than I expected.

Maybe this should be about exposing the ExecuteSQL function instead, possibly combined with st_read, with a sql arg run against the data source before transferring features.  Users will have to know that different drivers have different offsets for the virtual "FID", but then the raw st_read+ExecuteSQL could be wrapped for different use-cases. 

This is on my radar anyway - I started on a dplyr-backend using rgdal2 before sf got read-capabilities and the classes were defined, before it was clear where the queried features would go. 

I'm happy to try all this before asking for any more of sf, if it's performant for chunks then I'll come back with specifics.

**Comment by edzer** [comment]
@mdsumner the performance loss here was to be expected, since many OGR drivers don't offer random access, but really have to read the first 999 features to read feature 1000. 

@crazycapivara the best `sf` has to offer now is `st_read_db`, which works for simple feature database drivers (we can now read postgis, sqlite, spatialite, and gpkg without going through OGR/GDAL), this lets you read the outcome from a sql query; if you're smart, the db does the (spatial) indexing.

Otherwise, I'd be happy to close this issue.

**Comment by mdsumner** [comment]
I was going to say yes close, and then this: 

https://trac.osgeo.org/gdal/wiki/rfc66_randomlayerreadwrite

https://lists.osgeo.org/pipermail/gdal-dev/2017-May/046606.html

(Still, I am happy for it to be closed, better treated as introduction of new GDAL features if/when appropriate).

**Comment by crazycapivara** [comment]
I am also happy for it to be closed.
