### ISSUE TITLE
Unable to reproduce some vignette examples

### ISSUE THREAD

**Issue by dieza** [edzer/sfr#136]
par(mar = rep(0,4))
plot(nc[1])
plot(nc[1,1], col = 'red', add = TRUE)
Returns an not very nice graph consisting in as may square as counties I guess
<img width="752" alt="captura de pantalla 2016-12-28 a les 20 50 04" src="https://cloud.githubusercontent.com/assets/3057651/21530239/9654e0bc-cd3f-11e6-956e-a9ded303c0e8.png">
#sessionInfo
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.1

locale:
[1] ca_ES.UTF-8/ca_ES.UTF-8/ca_ES.UTF-8/C/ca_ES.UTF-8/ca_ES.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sp_1.2-3          RPostgreSQL_0.4-1 DBI_0.5-1         sf_0.2-7         

loaded via a namespace (and not attached):
[1] rgdal_1.1-10    tools_3.3.2     Rcpp_0.12.8     grid_3.3.2      lattice_0.20-34

**Comment by edzer** [comment]
This is much better in 0.2-8, can you install from github?
![x](https://cloud.githubusercontent.com/assets/520851/21530346/76d966b2-cd40-11e6-92cc-5c60a1d4030f.png)

**Comment by dieza** [comment]
Thanks, working now but I'm still unable to install from github.
