### ISSUE TITLE
Improve st_cast() guesswork

### ISSUE THREAD

**Issue by etiennebr** [edzer/sfr#144]
As discussed in #139, I would expect `st_cast_default()` to coerce geometry to MULTI* when presented a mix of types: 
```r
st_sfc(st_point(c(0,1)), st_multipoint(matrix(1:10,,2))) %>% st_cast() %>% class()
# [1] "sfc_GEOMETRY" "sfc"  
```
Would it make sense to make this the default:
```r
st_sfc(st_point(c(0,1)), st_multipoint(matrix(1:10,,2))) %>% st_cast("MULTIPOINT") %>% class()
# [1] "sfc_MULTIPOINT" "sfc"  

```
I'd be happy to integrate the #139 (`st_multi()`) logic :) to `st_cast()` as I think it would be convenient, but I might overlook something, or maybe there's another function for that purpose ?

**Comment by edzer** [comment]
Yes, that makes sense.

**Comment by etiennebr** [comment]
This might be in conflict with #110, #138. I think there should be a conservative way to `st_cast` that would pop an error when going to a higher dimension point > line > polygon and only allow polygon > line > point.
