### ISSUE TITLE
wiki page for travis-ci?

### ISSUE THREAD

**Issue by mpadge** [edzer/sfr#156]
I've tried a bunch of `.travis.yml` configurations in a minimal [`R` package with `sf` dep](https://github.com/mpadge/sftest), some of which work, some of which don't. In the words of @Robinlovelace, I ['imagine this will be useful for others'](https://github.com/osmdatar/osmdata/issues/28). If you also think it'd be useful, I'll put some short notes in an `sfr` wiki page - otherwise, if you'd rather keep the repo clean, just close the issue.

**Comment by edzer** [comment]
No: I find this too meta, and not related to sf as such, to put on a wiki, it would be the first wiki entry which would give a strange impression. Besides that, all travis experiences seem to have a very short half-life, these days.
