### ISSUE TITLE
RTriangle alternative to GEOS for triangulate?

### ISSUE THREAD

**Issue by mdsumner** [edzer/sfr#163]
We could use RTriangle as an alternative to st_triangulate, to avoid the GEOS 3.4.0 requirement.   (The license might be a problem: 	CC BY-NC-SA 4.0). 

There are many other Delaunay triangulators on CRAN that we could use, but this one has the added benefits over all the others in having constrained triangulations, breaking the criterion where needed to mesh input line segments, and the ability to apply other requirements on triangles like maximum area, minimum internal angles, and more. 

With st_triangulate we could break multipolygons up into parts and triangulate those separately, and filter out triangles from holes and concavities with point in poly test, but there still will often be edges that aren't in the Delaunay mesh. RTriangle gives an exact decomposition to triangles for any multipolygon, and there aren't many available implementations for that, this is the only one in R that I know of. 

I've done a basic example here: 

https://github.com/mdsumner/sfr/blob/constrained-triangulation/R/rt_triangulate.R

That relies on `dplyr` just for bind_rows, but that can be replaced with base. 

It's a bit quicker to short-circuit the extra checks done by `st_polygon`.

I use this in mesh-indexed form elsewhere, but GEOMETRYCOLLECTIONs of triangle polygons could be pretty useful. Perhaps it's of interest in sf itself.

**Comment by edzer** [comment]
That license is a no-go. Remember `gpclib`?

**Comment by mdsumner** [comment]
A no-go for what, CRAN?  (I'm confused)  https://CRAN.R-project.org/package=RTriangle

**Comment by edzer** [comment]
I got that one wrong; of course, gpclib is also still there. 

In any case, we don't want an NC clause tainting the rights to use `sf`; you'd have to do it in a package deriving from sf.

**Comment by mdsumner** [comment]
Ok no problem.

**Comment by mdsumner** [comment]
implemented here: https://github.com/r-gris/sfct
