### ISSUE TITLE
sf + shinyapps.io stumbling block

### ISSUE THREAD

**Issue by tiernanmartin** [edzer/sfr#173]
There is currently a "gotcha" for `sf` users who want to publish a shiny app using `sf` to the shinyapps.io server: the server doesn't run GDAL 2.x.

I have [raised this problem](https://groups.google.com/d/msg/shinyapps-users/vsus6NQSSso/YzAmIm4PBgAJ) with the shinyapps team and [their response](https://groups.google.com/d/msg/shinyapps-users/vsus6NQSSso/oT-NIJQdFAAJ) was to suggest that I submit a PR to [rstudio/shinyapps-package-dependencies](https://github.com/rstudio/shinyapps-package-dependencies) with an installer script for the [Ubuntu GIS PPA](https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa?field.series_filter=trusty).

I'd like to take care of that myself, but unfortunately it is beyond my skillset. If any of the `sf` devs wanted to take a crack at it for the good of the order, I'm sure many entry-level `sf` users like myself would be grateful.

**Comment by edzer** [comment]
Will check.

**Comment by edzer** [comment]
PR added: https://github.com/rstudio/shinyapps-package-dependencies/pull/72

**Comment by edzer** [comment]
Should work staring [next week](https://github.com/rstudio/shinyapps-package-dependencies/pull/72#issuecomment-272471157).
