### ISSUE TITLE
Licensing of projection metadata and OGC standards

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#181]
Just a heads-up with respect to an on-going [discussion](http://lists.maptools.org/pipermail/proj/2017-January/007590.html) about licensing of content, use and distribution that started on the proj4 list. The underlying issue is that, say, a mapping or geodetic authority does not want to use a license that permits changes, among these EPSG. SF is another. We implement SF and link to documents, probably OK. We distribute proj4 and GDAL copies of EPSG content in Windows and OSX CRAN - is this questionable? IANAL ...

**Comment by edzer** [comment]
Surely an issue, thanks for raising!
