### ISSUE TITLE
Feature request: function to sample points in polygon

### ISSUE THREAD

**Issue by Robinlovelace** [edzer/sfr#182]
So far there is `st_line_sample()` for sampling points from lines.

Any ideas on the polygonal equivalent, e.g. `st_poly_sample()`?

Also I suspect packaging these in a polymorphic metafunction, e.g. `st_sample()`, could be useful. Will allow myself and @virgesmith to switch completely to **sf** now he's got the deps sorted!

**Comment by edzer** [comment]
It's still not ideal what we have, but it works as documented.

**Comment by Zedseayou** [comment]
@Robinlovelace did you find any way to approach this? I thought about just taking random points inside a bounding box and checking to make sure the point was inside the polygon, but not sure if that's robust
