### ISSUE TITLE
Duality of geometry column

### ISSUE THREAD

**Issue by etiennebr** [edzer/sfr#183]
I see this duality with the geometry column: it's sticky (which is the basis of `sf` class) and it's hidden most of the time, so the user doesn't have to care for it. But it's still there, so some functions care about it. Anyways, I don't necessarily want to launch a philosophical debate, but I personally want to keep that in mind when using or writing functions for `sf`. I also think it would be a good practice to handle the duality in a uniform interface. 

First [example](https://github.com/edzer/sfr/commit/b30de717f77756f705899057a2eb4e886d90b210#commitcomment-20526051):
```r
sf1 <- st_sf(a = c("x", "y"), geom = st_sfc(st_point(3:4), st_point(3:4)))
sf1[names(sf1)]
#  Error: length(setdiff(names(value), nv)) == 0 is not TRUE 
sf1[setdiff(names(sf1), "geom")]
# Simple feature collection with 2 features and 1 field
# geometry type:  POINT
# dimension:      XY
#   a       geom
# 1 x POINT(3 4)
# 2 y POINT(3 4)
```

Second example is with `dplyr` functions:
```r
sf1 %>% select(-geom)
# Simple feature collection with 2 features and 1 field
# geometry type:  POINT
# dimension:      XY
#   a       geom
# 1 x POINT(3 4)
# 2 y POINT(3 4)
```

It also has the side effect that `count()` unions all the groups, which adds quite a lot of computation and doesn't necessarily follow the name of the function. For this one, maybe it's a great feature, I don't know, but I was surprised.
```r
sf1 %>% count(a)
# Simple feature collection with 2 features and 2 fields
# geometry type:  POINT
# dimension:      XY
#   a n       geom
# 1 x 1 POINT(3 4)
# 2 y 1 POINT(3 4)
```

In the first example, I think it should simply ignore the geometry. In the second example, it's trickier, but I'd go for removing the geometry, but this changes the class, which is bad. So I don't know. For the last one, maybe add a `drop_geometry` argument to non-spatial functions (i.e. all dplyr functions)? Otherwise, there's no easy way to drop the geometry other than casting to `data.frame`.

**Comment by edzer** [comment]
All good points, and open for discussion. 

Adding to this: it's right now pretty easy to add a second geometry column, 
```
> sf1[["geom2"]] = st_sfc(st_point(3:4), st_point(3:4))
> sf1
Simple feature collection with 2 features and 2 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: 3 ymin: 4 xmax: 3 ymax: 4
epsg (SRID):    NA
proj4string:    NA
  a       geom      geom2
1 x POINT(3 4) POINT(3 4)
2 y POINT(3 4) POINT(3 4)
```
(which PostGIS and GDAL also allow) but I feel it is a better idea to not allow this, since any geometry operation on such an object is ambiguous.

**Comment by etiennebr** [comment]
Yes, at that point it is a choice. I would prefer to have a geometry column that I have to mention explicitly because it's closer to other variable behavior. Stickiness for me doesn't outweigh the benefits, but I understand why this is useful to many people (including me). In many applications, it's just straightforward. On the other hand, it adds some burden to the development. 

If I want an explicit geometry column, I use`%>% as_tibble`. Then it's possible to have multiple geometry columns and requires explicit mention. This describes the workflow I came up until now.

**Comment by edzer** [comment]
How about the following idea:
* `data.frame` or `tibble` can have as many geometry columns as you want, they don't care
* `sf` objects can also have this, but in addition have an attribute `sf_column` which points to the geometry column to be "active", and used in all operations that involve geometry
* you can switch between active geometries, e.g. in the example above by
```R
st_geometry(sf1) = "geom"
st_geometry(sf1) = "geom2"
```
* except for trivial cases, many operations on `sf` objects may drop secondary geometries.

**Comment by etiennebr** [comment]
> data.frame or tibble can have as many geometry columns as you want, they don't care

I agree

> sf objects can also have this, but in addition have an attribute sf_column which points to the geometry column to be "active", and used in all operations that involve geometry

I think that would be great. Could we call it "default" geometry column?. 

> you can switch between active geometries, e.g. in the example above by

That's a good idea. I'm not clear on the implications/interface, I'd need to think about it; but here is a couple of questions I have. What about having a `st_default_geometry(sf1)` and `st_set_default_geometry("geom2")` rather than overloading `st_geometry`. Do you see any advantage?

Would that mean an optional `geometry_column` argument in each `sf` function to specify the column to operate on? Like `st_geometry(sf1, "geom2")`. Is it possible to harness that feature to have these two column interact somehow?

**Comment by edzer** [comment]
I think "active" is better since non-active ones are simply ignored; this is not what "default" implies. I see the active geometry as _the_ geometry, since all others are simply columns like any other column. Hence, `set_geometry` would be appropriate. All functions operating on geometry will operate on the active geometry only, no need (or possibility) to set these for each function. Simply change which one is active.

Anyway, this is all pretty futuristic.

**Comment by edzer** [comment]
See also #257

**Comment by faridcher** [comment]
multiple geometry with `merge` and `st_join` don't work yet:

```r
a = st_sf(a = 1:4,
          geom = st_sfc(st_point(c(1,1)), st_point(c(2,2)), st_point(c(3,3)), st_point(c(4,4))))
b = st_sf(a = 11:14,
          geom = st_sfc(st_point(c(10,10)), st_point(c(2,2)), st_point(c(2,2)), st_point(c(3,3))))

cbind(a,b) #works
merge(a,b) #error
st_join(a,b) #keeps geom of a. why not keep  both and first be set as active
```

**Comment by tim-salabim** [comment]
Regarding `st_join`, that would potentially be quite some overhead. E.g. for a = a few million pints and b = a few large polygons, you'd end up with a few million large polygons.
