### ISSUE TITLE
Shiny Support (Question)

### ISSUE THREAD

**Issue by spencerbell** [edzer/sfr#186]
Is sf intended to work with shiny?

**Comment by spencerbell** [comment]
Keep receiving Warning: Error in CPL_read_ogr: Open failed.

Is this on me or does st_read not work in shiny?

server.R
```
library(shiny)
library(sf)
library(leaflet)
options(shiny.maxRequestSize=30*1024^2) 
# use the below options code if you wish to increase the file input limit, in this example file input limit is increased from 5MB to 9MB
# options(shiny.maxRequestSize = 9*1024^2)

shinyServer(function(input,output){
  
  # This reactive function will take the inputs from UI.R and use them for read.table() to read the data from the file. It returns the dataset in the form of a dataframe.
  # file$datapath -> gives the path of the file
  
  
  data <- reactive({
    file1 <- input$file
    if(is.null(file1)){return()} 
    st_read(file1$datapath)    
  })
  
  # this reactive output contains the summary of the dataset and display the summary in table format
  output$filedf <- renderPlot({
    if(is.null(data())){return ()}
    plot(data)
  })
  
  output$map <- renderLeaflet({
    leaflet(data())  %>% addTiles() %>% 
      addPolygons()
  })
  
  # the following renderUI is used to dynamically generate the tabsets when the file is loaded. Until the file is loaded, app will not show the tabset.
  output$tb <- renderUI({
      tabsetPanel(tabPanel("About file", plotOutput("filedf")),
                  tabPanel("Map", leafletOutput("map")))
  })
})
```

ui.R

```
library(shiny)
shinyUI(fluidPage(
  titlePanel("File Input"),
  sidebarLayout(
    sidebarPanel(
      fileInput("file","Upload the file", multiple=TRUE), # fileinput() function is used to get the file upload contorl option
      helpText("Default max. file size is 5MB"),
      tags$hr()
    ),
    mainPanel(
      uiOutput("tb")
    )
    
  )
))
```

**Comment by edzer** [comment]
Shapefiles consist of at least three files, are they all uploaded?

**Comment by spencerbell** [comment]
Yes, I've tried multiple combinations including the mandatory files (.shp, .shx, .dbf) and then also adding .prj, .cpg, .sbn, .shx and .shp.xml.

Do the files need to be zipped instead of having fileInput accept multiple files?

**Comment by edzer** [comment]
No they just have to be in the same directory. Can you import them locally with `st_read`?

**Comment by edzer** [comment]
what is in `file1$datapath`?

**Comment by spencerbell** [comment]
When I run `st_read` locally I only need to reference the path the shapefile(not the other essential files .dbf and .shx) the below code works fine locally.
`phl <- st_read("C:/R/GitCap/cap/Philly_MSA_BG.shp")`

`file1$datapath` is the path to the shapefile within shiny, I keep getting this error 

> Cannot open data source C:\Users\sbell\AppData\Local\Temp\RtmpETWb1d\da496b9ba401043b360025b8\0

**Comment by edzer** [comment]
What if you replace all \ with / ? Do you run sf from CRAN, or the dev version from GH?

**Comment by spencerbell** [comment]
dev version.

Not sure how to change the temporary filepath, I tried
```
  data <- reactive({
    file1 <- input$file
    if(is.null(file1)){return()}
    gsub("\\", "/", file1$datapath)
    st_read(file1$datapath)    
  })
```
but that gave another error

> Error in sourceUTF8(serverR, envir = new.env(parent = globalenv())) : 
>   Error sourcing C:\Users\sbell\AppData\Local\Temp\RtmpETWb1d\file22ec4c2c6647
> Warning: Error in gsub: invalid regular expression '\', reason 'Trailing backslash'

**Comment by edzer** [comment]
both
> Error sourcing C:\Users\sbell\AppData\Local\Temp\RtmpETWb1d\file22ec4c2c6647

and

> C:\Users\sbell\AppData\Local\Temp\RtmpETWb1d\da496b9ba401043b360025b8\0

don't seem to point to shapefiles, as you said, these should end in `.shp`.

**Comment by tim-salabim** [comment]
This works for me (apart from the issue that leaflet still cannot handle sf data properly):

```r
library(shiny)
library(sf)
library(leaflet)
options(shiny.maxRequestSize=30*1024^2)
# use the below options code if you wish to increase the file input limit, in this example file input limit is increased from 5MB to 9MB
# options(shiny.maxRequestSize = 9*1024^2)

server <- shinyServer(function(input,output){

  # This reactive function will take the inputs from UI.R and use them for read.table() to read the data from the file. It returns the dataset in the form of a dataframe.
  # file$datapath -> gives the path of the file


  data <- reactive({
    file1 <- input$file
    if(is.null(file1)){return()}
    layer <- rgdal::ogrListLayers(input$file$name)
    fls <- paste0(layer, c(".shp", ".dbf", ".shx", ".prj"))
    file.copy(from = fls, to = tempdir())
    print(tempdir())
    print(fls)
    st_read(paste(tempdir(), fls[1], sep = "/"))
  })

  # this reactive output contains the summary of the dataset and display the summary in table format
  output$filedf <- renderPlot({
    if(is.null(data())){return ()}
    plot(data())
  })

  output$map <- renderLeaflet({
    leaflet(data())  %>% addTiles() %>%
      addPolygons()
  })

  # the following renderUI is used to dynamically generate the tabsets when the file is loaded. Until the file is loaded, app will not show the tabset.
  output$tb <- renderUI({
    tabsetPanel(tabPanel("About file", plotOutput("filedf")),
                tabPanel("Map", leafletOutput("map")))
  })
})


library(shiny)
ui <- shinyUI(fluidPage(
  titlePanel("File Input"),
  sidebarLayout(
    sidebarPanel(
      fileInput("file","Upload the file", multiple=TRUE), # fileinput() function is used to get the file upload contorl option
      helpText("Default max. file size is 5MB"),
      tags$hr()
    ),
    mainPanel(
      uiOutput("tb")
    )

  )
))

shinyApp(ui, server)
```
What I'm doing here is copy all relevant files explicitly to `tempdir()`. The leaflet panel will not work (at least for the polygon data I tried) as sf support is still not quite there yet. However, replacing `# this reactive output contains the summary of the dataset and display the summary in table format
  output$filedf <- renderPlot({
    if(is.null(data())){return ()}
    plot(data)
  })`  with `# this reactive output contains the summary of the dataset and display the summary in table format
  output$filedf <- renderPlot({
    if(is.null(data())){return ()}
    plot(data())
  })` shows at least the static plot which means the data was read properly.

**Comment by spencerbell** [comment]
Yes! This is fantastic. 

It would be nice however if it worked with Leaflet.  How is that coming along, can I help in anyway?

**Comment by spencerbell** [comment]
Actually, when I used your code it gave me an error `length(dsn) == 1 is not TRUE` 

I used the code below and got it to plot, still not in leaflet however.

ui.R
```
library(shiny)
options(shiny.maxRequestSize=30*1024^2)
shinyUI(pageWithSidebar(
  
  headerPanel("Shapefile plot"),
  sidebarPanel(
    fileInput('inputdata', 'Input shapefile',accept=c('.shp','.dbf','.sbn','.sbx','.shx',".prj"), multiple=TRUE)),
  mainPanel(
    plotOutput("SHPplot")
  )
))
```

server.R
```
library(sf)

server = function(input, output) {
  
  output$SHPplot <-  renderPlot({
    
    myshape<- input$inputdata
    if (is.null(myshape)) 
      return(NULL)       
    dir<-dirname(myshape[2,4])
    
    for ( i in 1:nrow(myshape)) {
      file.rename(myshape[i,4], paste0(dir,"/",myshape[i,1]))}
    
    getshp <- list.files(dir, pattern="*.shp", full.names=TRUE)
    shape <- read_sf(getshp)
    print(getshp)
    plot(shape)
    
  })
}
```

**Comment by tim-salabim** [comment]
have you tried with a point data set? leaflet still has problems with sf polygons and linestrings

**Comment by spencerbell** [comment]
Yes, point features work. However, for my application I really need polylines/polygons, does this mean I still need to use sp?

**Comment by tim-salabim** [comment]
For the moment yes. Though it may change any day. Best is to watch leaflet repo on github

**Comment by spencerbell** [comment]
Alright, I appreciate the help, I'll be watching the leaflet repo :)
