### ISSUE TITLE
Null values in OGR

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#192]
Have I mentioned this GDAL [RFC](https://trac.osgeo.org/gdal/wiki/rfc67_nullfieldvalues)? Due for 2.2 ...

**Comment by edzer** [comment]
Thanks!

**Comment by edzer** [comment]
Soo, we need to sort out what to do when writing NA values: should the be left unset (like not) or assigned NULL (the new thing)? NULL setting might only work for a limited number of drivers?

**Comment by rsbivand** [comment]
Yes, conditionally on the RFC being accepted. See also this [thread](https://lists.osgeo.org/pipermail/gdal-dev/2017-January/045903.html). Even so, it will mean `#ifdef ` to split between NULL-capable GDAL and earlier. Should we ask Even to provide a function indicating the capability?

**Comment by edzer** [comment]
That function would have to be evaluated inside an `#ifdef` directive, I don't see the benefits.

**Comment by rsbivand** [comment]
Right, maybe sometime FOSS need to provide a capabilities() function from the start, to which new ones can be added incrementally in query mode?
