### ISSUE TITLE
The purpose of "overwrite=TRUE" in st_write

### ISSUE THREAD

**Issue by eivindhammers** [edzer/sfr#195]
In #87 I see `overwrite=TRUE` being used in `st_write`. However, this argument is undocumented, and its purpose seems ambiguous for drivers where the `dsn` can contain several layers, like GPKG. Forgive me if I'm mistaken, but I can't see the (...) arguments passed on to `CPL_write_ogr` anywhere in the definition of `st_write`, so adding `overwrite=TRUE` will just be ignored?

The example below illustrates that `overwrite=FALSE` neither complains that a `.gpkg` with the same name already exists, nor does it add a second layer.

```R
library(sf)
fname <- system.file("shape/nc.shp", package="sf")
nc <- st_read(fname)
file <- tempfile(fileext = ".gpkg")
st_write(nc, dsn = file, layer = "layer1", overwrite = TRUE)
st_write(nc, dsn = file, layer = "layer2", overwrite = FALSE)
st_layers(file)
```

`st_layers(file)` returns 
```R
Driver: GPKG 
Available layers:
  layer_name geometry_type features fields
1     layer2 Multi Polygon      100     14
```

**Comment by edzer** [comment]
Bad example; `overwrite` is absorbed by `...`, which is ignored for `st_write`. I now added checks, and fixed the docs of `st_write`.

**Comment by eivindhammers** [comment]
Ok, thanks for clarifying. Adding an `overwrite_layer` option would be a welcome enhancement, though.

**Comment by edzer** [comment]
with default set to `TRUE` or `FALSE`? I find the comments in `rgdal::writeOGR` somewhat patronizing, also in the context of the rest of R, where e.g. `write.table` also does not have this option. I am inclined to assume that people who use R know they take a risk.

**Comment by rsbivand** [comment]
It copies `ogr2ogr`, which needs `-overwrite` given to overwrite an existing layer.

**Comment by eivindhammers** [comment]
Default set to `FALSE` imho.
