### ISSUE TITLE
Spatial join based on proximity (closest)

### ISSUE THREAD

**Issue by wgrundlingh** [edzer/sfr#200]
ArcMap allows for a [spatial join with the parameter CLOSEST](http://pro.arcgis.com/en/pro-app/tool-reference/analysis/spatial-join.htm).

Would it be possible to implement this as a feature via something like st_closest(x, y, ...)?

**Comment by edzer** [comment]
There is, afaics, not a function in [GEOS](https://geos.osgeo.org/doxygen/geos__c_8h_source.html) that we can use for this, so the implementation would have to use `st_distance`, and then select the closest. So possible yes, but it wouldn't scale nicely, nor be efficient.

**Comment by etiennebr** [comment]
I believe an equivalent to postgis `st_dwithin` could be useful for a spatial join based on proximity, but it doesn't solve your immediate problem. I'd be interested to know how k-NN packages scale that problem?

**Comment by Robinlovelace** [comment]
If two sets of points are represented as matrices I guess that would work. There are loads of options including `knn()` in base R and this one: https://github.com/davpinto/fastknn

Appreciate this is closed and not asking as a feature request but just out of curiosity would that be possible?

**Comment by Robinlovelace** [comment]
Update: I've been using the **nabor** package and it works great on 2 sets of matrices: https://cran.r-project.org/package=nabor

That would be my default strategy and, having used it in **stplanr** I guess it would be fast and scalable, and really useful, either as `st_nearest(x, y)` which could go straight into `st_join()` or as a closest parameter as the original post suggested.

**Comment by ratnanil** [comment]
I think this would be a great feature (see, [this question](https://gis.stackexchange.com/a/251291 )and [this question](https://stackoverflow.com/a/49200653))

**Comment by kendonB** [comment]
See here: https://github.com/r-spatial/sf/issues/990#issuecomment-468575158

**Comment by ratnanil** [comment]
Here's an example of a spatial join using `st_nearest_feature` (join the nearest town to each highway segment):

```r
library(sf)

test3 <- system.file("sqlite/test3.sqlite", package="sf")

towns <- read_sf(test3, "Towns")
highways <- read_sf(test3, "Highways")

towns_joined <- st_join(towns, highways, st_nearest_feature)

towns_joined

Simple feature collection with 8101 features and 7 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 319224 ymin: 3934674 xmax: 1308585 ymax: 5214373
Projected CRS: WGS 84 / UTM zone 32N
# A tibble: 8,101 × 8
   Name.x  Peoples Local…¹ County Region           Geometry PK_UID Name.y 
 * <chr>     <int>   <int>  <int>  <int>        <POINT [m]>  <int> <chr>  
 1 Brozolo     435       1      0      0 (427002.8 4996361)     10 Unknown
 2 Campig…    1284       1      0      0 (367470.5 4962414)     10 Unknown
 3 Canisc…     274       1      0      0 (390084.1 5025552)     10 Unknown
 4 Cavagn…    2281       1      0      0   (425247 5000248)     10 Unknown
 5 Maglia…    1674       1      0      0 (426418.9 4957737)     10 Unknown
 6 Mango      1334       1      0      0 (432661.5 4948470)     10 Unknown
 7 Manta      3363       1      0      0 (379960.2 4941389)     10 Unknown
 8 Marene     2703       1      0      0   (399494 4946145)     10 Unknown
 9 Margar…    1297       1      0      0 (395282.6 4917524)     10 Unknown
10 Martin…     667       1      0      0 (370131.2 4942846)     10 Unknown
# … with 8,091 more rows, and abbreviated variable name ¹​LocalCounc
# ℹ Use `print(n = ...)` to see more rows
```


<details>
<summary>visualize</summary>

```r
library(ggplot2)

towns_joined_subset <- st_intersection(towns_joined, st_as_sfc(st_bbox(highways)))

ggplot(towns_joined_subset, aes(colour = as.factor(PK_UID))) +
  geom_sf() +
  geom_sf(data = highways) +
  theme(legend.position = "none") 
```

</details>



![image](https://user-images.githubusercontent.com/12532091/191970215-2b57bb7c-487c-40fc-8469-aa0297565f73.png)
