### ISSUE TITLE
Add option to return first/last geometry when intersecting

### ISSUE THREAD

**Issue by wgrundlingh** [edzer/sfr#201]
Currently, `st_intersects(x, y)` returns *all* intersections of `y` with `x` (I got this much from reading the definition of `gIntersection` on [page 22](https://cloud.githubusercontent.com/assets/1776164/22574562/85b14552-e964-11e6-85c1-930d5451911c.png) of the [`rgeos`](https://cran.r-project.org/package=rgeos) [documentation](https://cran.r-project.org/web/packages/rgeos/rgeos.pdf)). Would it be possible to add an option that would return the *first* or *last* intersection in the case where multiple intersections are found? Let's call this option `return_intersects` with options {`first`, `last`, `all`} (`all` being the default, say).

The image below shows a data frame after an intersection between two geographies:

![image](https://cloud.githubusercontent.com/assets/1776164/22574294/073e5ecc-e963-11e6-9183-e7f8cfdf4164.png)

Entry 4235 of `x` matched (intersected with) two features in `y`: 53 and 56. In order to use the intersections in an *index* elsewhere, one would first have to manipulate the output to extract a proper index. An option would make this indexing easier.

**Comment by edzer** [comment]
Correct by accident, but I'd recommend to read the documentation of `st_intersects`. The solution to your problem of getting the first is:
```R
sapply(x, function(y) { if (length(y)) y[1] else NA })
```
I don't see how the first or last are of particular interest, and am reluctant to make such options. I see more interest in whether a particular intersection is 0-, 1- or 2-dimensional (point/line/area).

**Comment by wgrundlingh** [comment]
As far as I can tell, `st_intersects` in the [`sf`](https://cran.r-project.org/package=sf) [documentation](https://cran.r-project.org/web/packages/sf/sf.pdf), mentions exactly the same as what is mentioned in the [`rgeos`](https://cran.r-project.org/package=rgeos) [documentation](https://cran.r-project.org/web/packages/rgeos/rgeos.pdf):

![image](https://cloud.githubusercontent.com/assets/1776164/22608947/db7c99dc-ea13-11e6-98f6-6f5ff46f91a5.png)

Am I missing your point here?

I use(d)

```
lapply(x, first) # or lapply(x, last)
```

which provides the first or last of any entry in the intersection. The particular interest here could be that one deals with messy shape files where edges aren't coincident, thereby creating an overlap and possibly multiple intersections.

**Comment by edzer** [comment]
My point is that it is in general a bad idea to try to understand function _a_ by reading documentation of function _b_. It worked this time, but if you had asked for a dense intersection matrix, it would not have worked out:
```R
> library(sf)
> library(rgeos)
> a = st_sfc(st_point(0:1), st_point(2:3))
> b = st_sfc(st_point(0:1))
> st_intersects(a,b,sparse=FALSE)
      [,1]
[1,]  TRUE
[2,] FALSE
> gIntersects(as(a, "Spatial"),as(b, "Spatial"),TRUE)
     1     2
1 TRUE FALSE
```
I don't get your point why a particular (e.g. first or last) intersection is of more interest than any other, and why an option to select a particular index would make sense.

**Comment by wgrundlingh** [comment]
Understood. How about an alternative option then...

ArcGIS describes their [Spatial Join](http://pro.arcgis.com/en/pro-app/tool-reference/analysis/spatial-join.htm) tool as having the option to join using a "one to one" or "one to many" relationship ([here](http://webhelp.esri.com/arcgisdesktop/9.2/index.cfm?TopicName=Spatial_Join_(Analysis)) is a more descriptive view on that). The default for `sf` is "one to many".

Other choices might be to create an `st_join` function that performs similar to ArcGIS's Spatial Join, where one can specify the type of join to perform (like `st_intersect`, or `st_contains`, ...). *There* one can specify something related to either "one to one" or "one to many". One to one here could include options like `first`, `last`, "average of some field" or whatever.

**Comment by edzer** [comment]
You're four days behind; see https://github.com/edzer/sfr/commit/3f7c25dbae8972a3ce031e4823dcf943ca69b98e

**Comment by wgrundlingh** [comment]
That's hilarious...! :)

I haven't updated the package yet. So, would the following be possible?

````
st_join(a, b, left = TRUE, FUN = first)
````

**Comment by edzer** [comment]
No, for the reasons I gave above. How about installing first, then reading the docs?

**Comment by wgrundlingh** [comment]
@edzer I did read the most recent documention on CRAN as well as the diffs of [`join.R`](https://github.com/edzer/sfr/commit/3f7c25dbae8972a3ce031e4823dcf943ca69b98e); it mentions that "`FUN` is passed to `aggregate`". The markdown points to `\link[stats]{aggregate}`, but clicking on the PDF link doesn't do anything...

**Comment by edzer** [comment]
If you'd define 
```r
first = function(x) head(x,1)
```
then `st_join` with `FUN=first` might as well do what you want.
