### ISSUE TITLE
st_write doesn't seem to support append option for GeoJSON driver

### ISSUE THREAD

**Issue by tim-salabim** [edzer/sfr#204]
From the [GDALDriver Class Reference](http://www.gdal.org/classGDALDriver.html) I see that an option to append to an existing file should exist via `papszOptions`. I have no idea how the gdal drivers are handled internally by **sf** but I thought that `dataset_options = "APPEND_SUBDATASET=YES"` should work but it doesn't:

```r
library(sf)
library(mapview) # for a small point dataset

brew <- st_as_sf(breweries91)

st_write(obj = brew, dsn = "brew.geojson")
st_write(obj = brew, dsn = "brew.geojson", 
         dataset_options = "APPEND_SUBDATASET=YES")
```
creates an error
```
Writing layer `brew.geojson' to data source `/home/ede/brew.geojson' using driver `GeoJSON'
options:        APPEND_SUBDATASET=YES 
Creation of dataset /home/ede/brew.geojson failed.
Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
  Creation failed.
In addition: Warning message:
In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 6: The GeoJSON driver does not overwrite existing files.
``` 
Trying the same with geopackage driver reveals a different error:
```r
st_write(obj = brew, dsn = "brew.gpkg")
st_write(obj = brew, dsn = "brew.gpkg", 
         dataset_options = "APPEND_SUBDATASET=YES")

Writing layer `brew.gpkg' to data source `/home/ede/brew.gpkg' using driver `GPKG'
options:        APPEND_SUBDATASET=YES 
Creation of dataset /home/ede/brew.gpkg failed.
Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
  Creation failed.
In addition: Warning message:
In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 1: A file system object called '/home/ede/brew.gpkg' already exists.
```
My knowledge of GDAL internals is too limited to understand what's failing here, so I am hoping that someone could shed some light on the question whether appending features to an existing geojson file is/should/will be possible with `st_write`?

**Comment by edzer** [comment]
Thanks, that is as far as I got too. The [R code](https://github.com/edzer/sfr/blob/master/R/read.R#L129-L131) seems to pass this on to the [GDAL call](https://github.com/edzer/sfr/blob/master/src/gdal_write.cpp#L129) to driver->Create, which returns an error in both cases. 

@rouault, are we on rightly wondering what is going on here, or is this expected behavior?

**Comment by rouault** [comment]
APPEND_SUBDATASET is only for a few GDAL / raster drivers.
For GeoJSON, starting with GDAL 2.1, you can open the dataset in update mode and add new features to the existing layer (since there's a single layer per geojson file).

**Comment by edzer** [comment]
Thanks! The [docs](http://www.gdal.org/classGDALDriver.html#adb7bff9007fa5190d6cf742cf76942a8) of `GDALDriver::Create` suggest that I can pass `APPEND_SUBDATASET=YES` to `papszOptions`, and that is what I do. With GDAL 2.1, however I get the same error as Tim:
```r
Creation of dataset /home/edzer/git/sfr/src/brew.geojson failed.
Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
  Creation failed.
In addition: Warning message:
In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 6: The GeoJSON driver does not overwrite existing files.
```
meaning, `GDALDriver::Create` returned `NULL`. Does it make sense to try `GDALOpen(file, GA_Update)` instead?

**Comment by edzer** [comment]
With this commit, I can update GeoPackage files:
```r
> library(sf)
Linking to GEOS 3.5.0, GDAL 2.1.0, proj.4 4.9.2
> library(mapview) # for a small point dataset
Loading required package: leaflet
> 
> brew <- st_as_sf(breweries91)
> 
> unlink("brew.gpkg") # remove
> st_write(obj = brew, dsn = "brew.gpkg")
Writing layer `brew.gpkg' to data source `brew.gpkg' using driver `GPKG'
features:       32
fields:         7
geometry type:  Point
> st_write(obj = brew, dsn = "brew.gpkg", layer = "foo1", update = TRUE)
Writing layer `foo1' to data source `/home/edzer/git/brew.gpkg' using driver `GPKG'
Updating /home/edzer/git/brew.gpkg
features:       32
fields:         7
geometry type:  Point
> st_write(obj = brew, dsn = "brew.gpkg", layer = "foo2", update = TRUE)
Writing layer `foo2' to data source `/home/edzer/git/brew.gpkg' using driver `GPKG'
Updating /home/edzer/git/brew.gpkg
features:       32
fields:         7
geometry type:  Point
> st_layers("brew.gpkg")
Driver: GPKG 
Available layers:
  layer_name geometry_type features fields
1  brew.gpkg         Point       32      7
2       foo1         Point       32      7
3       foo2         Point       32      7
```
but haven't succeeded for the GeoJSON case. Also, neither of them seems to recognize `APPEND_SUBDATASET=YES`.

**Comment by tim-salabim** [comment]
FWIW, my specific problem with appending `st_write` was solved using `file.append`. Though this doesn't work for appending GeoJSON to GeoJSON, I simply needed to append a valid GeoJSON object to a text file starting with the line `var data = ` so that I can pass this as a predefined variable to JavaScript.

**Comment by dvictori** [comment]
I'm trying to do something similar for Geopackages. I can add new layers to a existing geopackage file but I cannot append data to an existing layer. Is this a limitation from GDAL side? Because ogr2ogr has a `-append` option.

**Comment by rouault** [comment]
> Is this a limitation from GDAL side? Because ogr2ogr has a `-append` option.

No, not a GDAL limitation: as you rightly pointed out, if ogr2ogr can do it, then this is possible by GDAL :-)

**Comment by dvictori** [comment]
But this issue is closed. Does this means that it's possible to append data to a GPKG layer using `st_write` and I'm doing something wrong? Or is this append option not available?

**Comment by edzer** [comment]
It means that append is not available. If you need ogr2ogr support from inside sf, try 
```r
sf::gdal_utils("vectortranslate", "infile", "outfile", c("-x", "xopt", "-y", "yopt"))
```
See also https://twitter.com/RogerBivand/status/1098527281583144961

**Comment by dvictori** [comment]
Great! I'll look at it. But from what I understood, "infile" must be a file on disk (a file path). Or could it be a sf object?

What I'm trying to do is open 5600 municipal shapefiles, one at a time, do some processing and write the output to a single table in a GPKG (creating a country wide layer)

I could do the merging inside R but I'm not sure I have the memory to handle this. `st_write` won't append so from what I understand, in order to use `gdal_utils` I would need to write a temporary file to disk and then send it to a GPKG.  Or am I missing something?

**Comment by edzer** [comment]
No, a file on disk.
