### ISSUE TITLE
Bad error message on st_intersects given object with Z dimension

### ISSUE THREAD

**Issue by jsta** [edzer/sfr#206]
I was getting the following error when running `st_intersects`:

> Error in CPL_geos_is_valid(st_geometry(x)) : 
  IllegalArgumentException: Points of LinearRing do not form a closed linestring

This sent me down a rabbit-hole of geometry repair tools but it turns out that simply running `st_zm` fixed the error. Should `st_intersects` check for a Z dimension and return a more informative error?

**Comment by edzer** [comment]
I don't see how `st_intersects` calls that function; could you pls provide a reproducible example?

**Comment by jsta** [comment]
```
zpoly <- st_polygon(list(matrix(c(398000.0, 7542000.0, 279.9, 398000.0, 7541990.0, 281.0, 398010.0, 7541990.0, 280.4, 398010.0, 7542000.0, 279.4, 398000.0, 7542000.0, 279.9), ncol = 3, byrow = TRUE)))
xypoint <- st_point(c(398005, 7541999))
st_intersects(zpoly, xypoint)
```
> Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, sparse,  : 
  IllegalArgumentException: Points of LinearRing do not form a closed linestring
```
poly <- st_zm(zpoly)
st_intersects(poly, xypoint)
```
>[[1]]
> [1] 1

**Comment by edzer** [comment]
Thanks - the error was a bit deeper down, but should be fixed now. In case of measured geometries ("XYM" or "XYZM") we still get an error, looks like GEOS doesn't like those.
