### ISSUE TITLE
st_read_db() from view or materialized view

### ISSUE THREAD

**Issue by balazsdukai** [edzer/sfr#212]
When I query a postgres view or materialized view with `st_read_db()` I get an error saying:
`Error: 'public.view' does not exist.`
However, I can read tables without problems. Also, `RPostgreSQL::dbReadTable()` works fine in all cases. I haven't found related info in the documentation so I wonder if I have missed a switch somewhere...
All relations are in the public schema.

**Comment by edzer** [comment]
@etiennebr do you an idea?

**Comment by etiennebr** [comment]
I'll have a look. I haven't tested views yet.
