### ISSUE TITLE
st_read_db and SQlite DB

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [edzer/sfr#216]
Attempt to read from a sample sqlite db will fail while trying to read from an unexistent schema.

```R
link <- "https://www.gaia-gis.it/spatialite-2.3.1/test-2.3.zip"
temp <- tempfile()
download.file(link, temp)
tdir <- tempdir()
utils::unzip (temp, exdir = tdir)
unlink(temp)
db <- file.path(tdir, "test-2.3.sqlite")
dbcon <- dbConnect(dbDriver("SQLite"), db)
dbListTables(dbcon)
dbListFields(dbcon, "HighWays")
dbReadTable(dbcon, "HighWays", geom_column = 'Geometry' )
dbReadTable(dbcon, "geometry_columns")
lin = st_read_db(dbcon, "HighWays", geom_column = 'Geometry')
```
```R
> lin = st_read_db(dbcon, "HighWays", geom_column = 'Geometry')
Error in rsqlite_send_query(conn@ptr, statement) : 
  no such table: information_schema.views
```

**Comment by edzer** [comment]
Maybe related to #212, where we moved towards PostGIS representations?

**Comment by PauloEduardoCardoso** [comment]
I see. so reading directly from sqlite will fall out of scope?

**Comment by edzer** [comment]
My initial plan was to be DBI compliant, but it looks like we're not yet there.

**Comment by edzer** [comment]
Do you happen to know where I can find how the binary geom blobs of sqlite are encoded? Is this ISO wkb?

Have you tried
```r
> hw = st_read("test-2.3.sqlite", "HighWays")
Reading layer `HighWays' from data source `/tmp/test-2.3.sqlite' using driver `SQLite'
converted into: LINESTRING
Simple feature collection with 775 features and 1 field
geometry type:  LINESTRING
dimension:      XY
bbox:           xmin: 495683.4 ymin: 4159367 xmax: 1305516 ymax: 5139898
epsg (SRID):    32632
proj4string:    +proj=utm +zone=32 +datum=WGS84 +units=m +no_defs
```

**Comment by edzer** [comment]
Found [this](https://www.gaia-gis.it/gaia-sins/BLOB-Geometry.html) as to my first question.

**Comment by etiennebr** [comment]
I think this is what you are looking at @edzer, and you'll probably be faster than me; if we could get wkb parsing to work, then adding support for SQLite relatively easy.

From the example above, if this could work:
```r
hw <- dbReadTable(dbcon, "HighWays", geom_column = 'Geometry' )
fc <- st_as_sfc(structure(hw[["Geometry"]], class = "WKB"))
```

**Comment by edzer** [comment]
This now works.

<details>

```r
> library(sf)
Linking to GEOS 3.5.1, GDAL 2.1.3, proj.4 4.9.2, lwgeom 2.3.2 r15302
> library(RSQLite)
> db <- "test-2.3.sqlite"
> dbcon <- dbConnect(dbDriver("SQLite"), db)
> dbListTables(dbcon)
[1] "HighWays"          "Regions"           "Towns"            
[4] "geom_cols_ref_sys" "geometry_columns"  "spatial_ref_sys"  
[7] "sqlite_sequence"  
> dbListFields(dbcon, "HighWays")
[1] "PK_UID"   "Name"     "Geometry"
> hw = dbReadTable(dbcon, "HighWays")
> st_as_sfc(hw$Geometry, spatialite = TRUE)
Geometry set for 775 features 
geometry type:  LINESTRING
dimension:      XY
bbox:           xmin: 495683.4 ymin: 4159367 xmax: 1305516 ymax: 5139898
epsg (SRID):    32632
proj4string:    +proj=utm +zone=32 +datum=WGS84 +units=m +no_defs
First 5 geometries:
LINESTRING(668540.706868592 4858267.85756248, 6...
LINESTRING(671365.867441752 4854173.7708021, 67...
LINESTRING(671417.575852571 4854175.10324393, 6...
LINESTRING(683100.868826631 4849547.00816066, 6...
LINESTRING(683428.354612234 4849327.04600966, 6...
> 
> tn = dbReadTable(dbcon, "Towns")
> st_as_sfc(tn$Geometry, spatialite = TRUE)
Geometry set for 8101 features 
geometry type:  POINT
dimension:      XY
bbox:           xmin: 319224 ymin: 3934674 xmax: 1308585 ymax: 5214373
epsg (SRID):    32632
proj4string:    +proj=utm +zone=32 +datum=WGS84 +units=m +no_defs
First 5 geometries:
POINT(427002.77 4996361.33)
POINT(367470.48 4962414.5)
POINT(390084.12 5025551.73)
POINT(425246.99 5000248.3)
POINT(426418.89 4957737.37)
> 
> re = dbReadTable(dbcon, "Regions")
> st_as_sfc(re$Geometry, spatialite = TRUE)
Geometry set for 109 features 
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: 312380.6 ymin: 3933596 xmax: 1311407 ymax: 5220663
epsg (SRID):    32632
proj4string:    +proj=utm +zone=32 +datum=WGS84 +units=m +no_defs
First 5 geometries:
MULTIPOLYGON(((752912.250296859 5028764.9890508...
MULTIPOLYGON(((751705.496715354 5029084.6555139...
MULTIPOLYGON(((766247.780711283 5036335.2991564...
MULTIPOLYGON(((750594.839945831 5026719.0243425...
MULTIPOLYGON(((554955.581882933 4911801.6754486...
```
</details>

note that:
* `st_as_sf` now understands a list with raw vectors as wkb (what else could it be?)
* `srid` seems to be always present in the spatialite geom blobs, but might be not an EPSG and may have to be resolved from the `geometry_columns` table, however, @PauloEduardoCardoso, I don't see any `proj4string` field in this table - is it only there when needed?
* the `spatialite=TRUE` is needed, because regrettably spatialite doesn't have a magic flag, like GPKG does
* differences between WKB and spatialite geom blobs make the code pretty ugly
* I have only tested for the geoms in the example above, not for the other 4, nor XYM/XYZ/XYZMs; other examples are welcome.

**Comment by edzer** [comment]
@etiennebr sqlite spatial tables are described [here](https://trac.osgeo.org/fdo/wiki/FDORfc16).

**Comment by edzer** [comment]
I also found out that [regular sqlite spatial tables](http://gdal.org/drv_sqlite.html) have simple ISO wkb blobs, decribed [here](https://trac.osgeo.org/fdo/wiki/FDORfc16), whereas spatialite have the complicated, deviating once. 

Note to self: to get spatialite working on ubuntu, I had to
```r
sudo apt-get install libsqlite3-mod-spatialite
```
then,
```
sqlite3 test3.sqlite
```
and load the spatial extension lib by
```
SELECT load_extension('mod_spatialite');
select asText(Geometry) from Regions limit 2;
MULTIPOLYGON(((752912.250297 5028764.989051, 753066.871935 5028928.677375, 753417.249537 5028775.949135, 753828.826422 5027429.54477, 752992.3308 5028072.927877, 752912.250297 5028764.989051)))
MULTIPOLYGON(((751705.496715 5029084.655514, 752144.84104 5029157.835014, 752606.195218 5028409.738962, 752877.630294 5027564.481467, 752928.785333 5026778.301798, 752674.997028 5026802.078917, 752383.649393 5027111.72308, 752307.454954 5027708.43772, 752424.18133 5028059.051117, 751491.753571 5028763.71405, 751455.937063 5028950.744019, 751705.496715 5029084.655514)))

```

**Comment by rsbivand** [comment]
Right, spatialite has big ambitions to be THE GIS, for example building in GEOS. I've always found it fragile from version to version, and stayed with the SQLite driver without the extensions - works solidly with no unneeded extra functionality.

**Comment by edzer** [comment]
Yes, it is incredibly feature rich. Of some interest might be its [topology](https://www.gaia-gis.it/fossil/libspatialite/wiki?name=topo-start) support (many pages docs), which seems to be built on the same code base as [postgis topology](http://postgis.net/docs/doxygen/2.4/d6/d03/lwgeom__topo_8c.html), and done by strk?

Linking to liblwgeom seems of similar [complexity](https://github.com/edzer/sfr/blob/master/src/lwgeom.cpp) as linking to GEOS and gdal, and it's all C. @mdsumner .

**Comment by mdsumner** [comment]
Spatial is not special, trying to find the extended discussion by SQLite author, it's good.

**Comment by jancgreyling** [comment]
Hallo, I'm trying to read a spatial table from a SQLite database using your example: 

features <- dbReadTable(db, "features")
shape <- st_as_sfc(features$Geometry, spatialite = TRUE)

but I'm getting the following error:

Error in CPL_read_wkb(x, EWKB, spatialite) : 
  reading non-native endian spatialite geometries not supported

Any ideas on what the error might be? I guess it has something to do with the structure of the Geometry variable:

 $ Geometry      : blob [1:721008] 
  ..$ : raw  74 52 4f 6c ...
  ..$ : raw  74 4a 26 6c ...
(and so forth)

**Comment by edzer** [comment]
The error indicates the file was created on a machine with a different endian-ness as the one you're using to read it. If this doesn't help, please provide a reproducible example (on a new issue), where you also explain why you don't use `st_read()`.

**Comment by jancgreyling** [comment]
I have tried st_read but get the following error:

features <- st_read(db, "features")
wkbType: 1380936841
Error in inherits(sfc, "try-error") : object 'sfc' not found

The database attached. Thank you for your help @edzer. I really appreciate it. sf is amazing!

https://we.tl/t-dzE5MDn3Oo

**Comment by edzer** [comment]
Which command did you use to create `db`?

**Comment by jancgreyling** [comment]
sqlite.driver <- dbDriver("SQLite")
db <- dbConnect(sqlite.driver,
                dbname = "Data/MP-cadastral.db")

**Comment by edzer** [comment]
I can reproduce your issue. It says that this is not supported: bad luck!

**Comment by etiennebr** [comment]
Merging the example with your code works for me:
``` r
library(DBI)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1

link <- "https://www.gaia-gis.it/spatialite-2.3.1/test-2.3.zip"
temp <- tempfile()
download.file(link, temp)
tdir <- tempdir()
utils::unzip (temp, exdir = tdir)
unlink(temp)
db <- file.path(tdir, "test-2.3.sqlite")
dbcon <- dbConnect(RSQLite::SQLite(), db)
features <- dbReadTable(dbcon, "HighWays")
shape <- st_as_sfc(features$Geometry, spatialite = TRUE)

#> Geometry set for 775 features 
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: 495683.4 ymin: 4159367 xmax: 1305516 ymax: 5139898
#> projected CRS:  WGS 84 / UTM zone 32N
#> First 5 geometries:
#> LINESTRING (668540.7 4858268, 668545.9 4858270,...
#> LINESTRING (671365.9 4854174, 671404.1 4854163)
#> LINESTRING (671417.6 4854175, 671496.3 4854072,...
#> LINESTRING (683100.9 4849547, 683095.9 4849540,...
#> LINESTRING (683428.4 4849327, 683424.8 4849329,...
```

<sup>Created on 2020-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As @edzer mentioned, it's probably an issue with your local endian-ness being different from the source.

**Comment by jancgreyling** [comment]
Many thanks! Much appreciated. I will try to find an alternative data source.
