### ISSUE TITLE
Plotting an sf object that has 100+ variables causes issues

### ISSUE THREAD

**Issue by Robinlovelace** [edzer/sfr#219]
Problem: if you plot a simple spatial object that contains 100+ variables, you get something like this (I'm using this test dataset to teach to students tomorrow):

![image](https://cloud.githubusercontent.com/assets/1825120/23002129/f55d51bc-f3e0-11e6-9764-1d59a5056766.png)

I find it un-useful (for want of a better word) that the default behaviour of one of the most commonly used functions in the future go-to spatial data paradigm allows this, especially when large, multi-variable spatial datasets are increasingly common. Not only does the image provide little useful visual information, it also takes an age (potentially forever if the spatail extent of those zones was a country and not a single city - Harrogate). This issue is made worse by the fact that many new users won't know how to plot only for one var (e.g. `x[1]` or `x[,1]`).

These thoughts about the issue illustrated above lead me to think of potential solutions outlined below:

- Print a message/warning if multiple variables are plotted explaining how to stop that or suggesting alternative plotting methods (e.g. with **tmap** or **mapview**).
- Set an upper limit (e.g. 3) on the number of 'small multiples' that `plot.sf()` will create by default.
- Update the documentation to explain this behaviour, why it was implemented like this and how to get around it when working with many vars.

There may be other solutions and some may not think this is an issue but I'm confident that it is sufficiently detrimental to some (especially new) R-spatial users as to discourage them from using sf at least for the time being.

**Comment by Robinlovelace** [comment]
Update: when I re-ran the function on the dev version of **sf** I got the following Warning - may be unrelated but thought it worth mentioning:

```
Warning message:
In is.na(names(ret)) :
  is.na() applied to non-(list or vector) of type 'NULL'
```

**Comment by edzer** [comment]
It's a good idea to think abou this - you're clearly the first one to try this out with so many vars. What about a default argument to `plot`, say, `max.plot = 15`?

**Comment by Robinlovelace** [comment]
This looks much better and I'd happily consider that as 'fixed for now', the warning message makes sense too:

```
Warning message:
In plot.sf(h_sel) : plotting the first 15 out of 123 attributes
```


![image](https://cloud.githubusercontent.com/assets/1825120/23015663/9c643c60-f42b-11e6-8764-9f8f4509076d.png)

**Comment by Robinlovelace** [comment]
Still think 15 is excessive though - how's 6 or 9 as a compromise?

**Comment by Nowosad** [comment]
Maybe 6 is the best number (the same as a number of rows shown by `head` function)?

**Comment by edzer** [comment]
I set it down to 9, but have it go up to fill the device if it hasn't been set (meaning that you get 10 for `nc`, but potentially 9 for some more square shaped bboxes; having two columns, one with 5 and one with 4 looks very odd).
