### ISSUE TITLE
scales?

### ISSUE THREAD

**Issue by hrbrmstr** [edzer/sfr#22]
I have heard through the grapevine (I'm still on a twitter sabbatical) that there's need of a ggplot scale for something geo-related (I'm assuming geo-related). Is this something @thomasp85 or I can help with?

**Comment by thomasp85** [comment]
See thomasp85/ggforce#8 - I was wondering why you had gone so silent...

**Comment by edzer** [comment]
Not directly spatial related - only in the larger [scheme of things](http://r-spatial.org/r/2016/09/26/future.html).

**Comment by hrbrmstr** [comment]
cool. i'll close this and follow it on @thomasp85's issue tracker. thx.
