### ISSUE TITLE
plot(y, add = T) fails when x has multiple layers

### ISSUE THREAD

**Issue by Robinlovelace** [edzer/sfr#221]
This will also be problematic if the initial `plot(x)` has multiple layers/facets I imagine.

Here's my code (sorry not reproducible):

```r
plot(stns[1])
plot(harrogate_oac[1], add = T)  # no problem with 1 variable
```

![image](https://cloud.githubusercontent.com/assets/1825120/23070850/523e852e-f524-11e6-956b-17bfb616182d.png)

```r
plot(stns[1])
plot(harrogate_oac, add = T)  # problem with multiple vars
```

![image](https://cloud.githubusercontent.com/assets/1825120/23071072/1a74d368-f525-11e6-86b4-e008d795e364.png)

**Comment by edzer** [comment]
Would you want that to raise an error, or a warning?

**Comment by edzer** [comment]
an error: fixed in https://github.com/edzer/sfr/commit/baab00bf6c60c7da2dc2ee19b8839d591b9f806b

**Comment by Robinlovelace** [comment]
I'd want it to work.

I think the default behaviour with `plot(y, add = TRUE)` should be that it plots one layer (layer 1 I guess or with no data) over the top of the previous plot, as with sp. It's a great way to explore the spatial relationships between datasets without any fancy visualisation packages like the excellent (but hefty) **mapview**.

What would your preferred behaviour be? And how should this map to cases where many (for example 9) multiples are plotted?

I think plotting y 9 times on x with no data or the data from layer 1 would be my preferred solution but don't know how hard that would be to implement.

**Comment by Robinlovelace** [comment]
Happy to say the specific issue is fixed now for my use case:

![image](https://cloud.githubusercontent.com/assets/1825120/23093386/71cdf4dc-f5d9-11e6-8e11-85ccacfb250f.png)

**Comment by edzer** [comment]
Great, thanks!

**Comment by tim-salabim** [comment]
@Robinlovelace could you maybe elaborate on what you mean by 'hefty'? I'd love to improve the package on a level beyond fixing errors (which is pretty much the only feedback I get) so I'd be very interested in your thoughts.

**Comment by Robinlovelace** [comment]
I mean it requires more dependencies (aside from the minor dependencies of dev versions of GDAL and GEOS **sf** side ; ) and a little more system resource and user headspace to use than trust `plot(x)`.

Peaking at the `DESCRIPTION` it seems that **mapview** has many deps. That's not a criticism - **stplanr** has loads. That's roughly what I mean by hefty in this context.

I don't have any feedback on that side of it and don't think it needs to be more lightweight.

**Comment by Robinlovelace** [comment]
In case it's useful, this is how I divide my plotting time:

- First peak: `plot`
- Interactive exploration: `mapview`
- Publication-ready maps: `qtm` and co

There's a little overlap, but overall think those approaches complement each other really well.

**Comment by Robinlovelace** [comment]
In case it's useful, this is how I divide my plotting time:

- First peak: `plot`
- Interactive exploration: `mapview`
- Publication-ready maps: `qtm` and co

There's a little overlap, but overall think those approaches complement each other really well.

**Comment by tim-salabim** [comment]
Cool, thanks for the clarification.
