### ISSUE TITLE
[dplyr compatibility] bind_rows with sf objects fails

### ISSUE THREAD

**Issue by tiernanmartin** [edzer/sfr#223]
``` r
library(tidyverse)
library(sf)

demo(nc, ask = FALSE)

bind_rows(nc[1:50, ], nc[51:100, ])
#> Error in .subset2(x, i, exact = exact): attempt to select less than one element in get1index
```

**Comment by tiernanmartin** [comment]
Related to #42

**Comment by edzer** [comment]
This is also related to https://github.com/edzer/sfr/issues/92 ; `bind_rows` is not a generic, and neither calls it one, so we can't make that work here. Maybe raise the issue with `dplyr`? `rbind` works for `sf` objects, anything against that?

**Comment by tiernanmartin** [comment]
Got it. I've raised an issue at the`dplyr`repo and in the meantime I can certainly use `rbind`.

**Comment by tiernanmartin** [comment]
Looks like this is a broader issue with `bind_rows` - see https://github.com/hadley/dplyr/issues/2457

**Comment by edzer** [comment]
Closing, as this is a dplyr issue.
