### ISSUE TITLE
Vignette build fail

### ISSUE THREAD

**Issue by Robinlovelace** [edzer/sfr#225]
Error message just tried (this happens if those files already exist in the vignettes folder):

```
Quitting from lines 459-460 (sf1.Rmd) 
Error: processing vignette 'sf1.Rmd' failed with diagnostics:
Dataset already exists.
```

**Comment by edzer** [comment]
This should not happen when your build system runs the `cleanup` script properly, which it should; I don't see why we should add this code to the vignette, or why a vignette should be run twice in the same directory.

**Comment by Robinlovelace** [comment]
OK fair enough - will remove that part.

**Comment by Robinlovelace** [comment]
Job done.
