### ISSUE TITLE
Transforming an empty sf object crashes RStudio

### ISSUE THREAD

**Issue by wgrundlingh** [edzer/sfr#228]
The following code example causes RStudio to crash:

```
library(dplyr)
library(sf)
nc = st_read(system.file('shape/nc.shp', package='sf')) %>%
  filter(AREA == 0)
  
nc %>% st_transform(4326)
```

The hypothetical situation is forced by creating a simple feature that doesn't have any observations (or features) in it. However, it is likely that in some circumstances an empty sf object will be processed, so a check should be built in to avoid this catastrophic failure.

**Comment by edzer** [comment]
This was corrected a few hours before you sent this in https://github.com/edzer/sfr/commit/aa45bda2cc77d76ca320e8426cb4f2280d809ffd (see changes to gdal.cpp).

**Comment by etiennebr** [comment]
Works for me. I think this issue can be closed.
