### ISSUE TITLE
Preserve field names when writing to shape file

### ISSUE THREAD

**Issue by wgrundlingh** [edzer/sfr#230]
Some of my `sf` object fields are lengthy, and I'd like to preserve that. However, writing (`st_write`) to `shp` with the `layer_options` set to `LAUNDERED = NO` (in order to preserve the field names) doesn't work.

Consider the following example:

```
library(dplyr)
library(sf)

nc <- st_read(system.file('shape/nc.shp', package = 'sf'))
nc <- nc %>% rename(VERYLONGNAME = NAME)

st_write(
  obj = nc,
  dsn = 'C:/temp/nc.shp',
  layer_options = c('LAUNDERED = NO') # Preserve field names
)
```

`gdal` complains with the following warnings:

```
Warning messages:
1: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Message 6: dataset C:\Temp\nc.shp does not support layer creation option LAUNDERED 
2: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Message 6: Normalized/laundered field name: 'VERYLONGNAME' to 'VERYLONGNA'
```

The [`gdal` reference manual](https://cran.r-project.org/web/packages/rgdal/rgdal.pdf) mentions that

> `layer_options`
> a character vector of options, which vary by driver, and should be treated as experimental

as part of the `writeOGR` function. Not sure whether there is a way around this.

Is there a way to *force* `LAUNDERED = NO`?

**Comment by edzer** [comment]
First of all, you're looking in the wrong documentation (of package rgdal, not sf). Second, the [gdal shapefile driver docs](http://www.gdal.org/drv_shapefile.html) don't mention an option LAUNDERED, I only see LAUNDER for the SQLite driver. Third, it is well known that shapefiles (using .dbf for attributes) has a small field name length limit. 

It's the right time to ditch shapefiles. Try GeoPackage.

**Comment by wgrundlingh** [comment]
@edzer Some feedback:

1. The [documentation of `sf`](https://cran.r-project.org/web/packages/sf/sf.pdf) mentions this regarding `layer_options`:

    > `layer_options`
    > character; driver dependent layer creation options; multiple options supported

    without much more information. I went the one step further to see whether the `gdal` documention mentioned anything more.

2. Thanks for this reference!

3. Good to know. Using `sf` from a programming point of view without much knowledge of attribute specifications particular to DBF is what I was missing here. I guess it is not that well known then.

4. [GeoPackage](http://www.geopackage.org/). That's good to see. It's supported by QGIS and Esri (ArcGIS) - awesome! For those interested in this, the following writes to the GeoPackage format:

    ```
    st_write(
      obj = nc,
      dsn = 'C:/temp/nc.gpkg'
    )
    ```

**Comment by edzer** [comment]
@wgrundlingh for point 1, it will help if you understand the difference between GDAL and R package rgdal.

**Comment by wgrundlingh** [comment]
@edzer I guess I need to do more research. Yes, I've only been introduced to `sf` (and it's relationships) recently and am new to GIS in R.
