### ISSUE TITLE
as_Spatial not exported

### ISSUE THREAD

**Issue by happyshows** [edzer/sfr#232]
Hi,

I was looking for a conversion function to sp class. Found as_Spatial in help but it's not exported.

**Comment by edzer** [comment]
as(x, "Spatial")

On 25 February 2017 05:20:54 CET, Shows Le <notifications@github.com> wrote:
>Hi,
>
>I was looking for a conversion function to sp class. Found as_Spatial
>in help but it's not exported.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/edzer/sfr/issues/232

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by happyshows** [comment]
cool thx
