### ISSUE TITLE
Conversion to sp seems not to work for POLYGON object

### ISSUE THREAD

**Issue by virgesmith** [edzer/sfr#233]
```
poly1Pts = matrix(c(0,0,10,5,5,10,0,0),ncol=2, byrow=TRUE)
poly1 = st_polygon(list(poly1Pts))
poly1_sp = as(poly1, "Spatial")

Error in as(poly1, "Spatial") : 
  no method or default for coercing “XY” to “Spatial”
```

**Comment by edzer** [comment]
try:
```r
poly1_sp = as(st_sfc(poly1), "Spatial")
```

**Comment by virgesmith** [comment]
Edzer

Thanks , that works. But any reason why it shouldn’t it work on a single feature as well as a collection?

As background we’re comparing the sp::sample.Polygon with my initial attempt at an sf implementation…

Thanks
Andrew

(PS Was Robin, not me, reporting this issue)

**Comment by edzer** [comment]
single feature geometry (`sfg`) objects do not map to a `Spatial` counterpart, as they have no CRS and bounding box.

**Comment by Robinlovelace** [comment]
I think `as(object_generated_by_sf, "Spatial")` will be a very common and useful command for people getting up-to-speed with **sf**. I therefore think it would be really useful if `poly1_sp = as(poly1, "Spatial")` in the OP worked.

What do you think of making **sf** convert it to a feature collection by default if it lacks a bb, e.g. with this kind of illustrative conditional construct:

```r
if(is(x, "sfg")){
  as(st_sfc(x), "Spatial")
} else {
  as(x, "Spatial")
}
```

**Comment by edzer** [comment]
I tried to set a coerce method (`setAs`), but it looks like it's not that trivial.

**Comment by Robinlovelace** [comment]
Hmmm. Anyone know a way round this? A bit over my head.
