### ISSUE TITLE
unlist.sfg

### ISSUE THREAD

**Issue by mdsumner** [edzer/sfr#235]
This internal method caught me out until I realized it was hiding what I expected from `unlist(x, recursive = FALSE)`

Can this be renamed to a specific internal function? Something like "sfg_as_matrix()".  

To get what I want I have to `unclass`, 

```R
p1 <- rbind(c(0,0), c(1,0), c(3,2), c(2,4), c(1,4), c(0,0))
p2 <- rbind(c(1,1), c(1,2), c(2,2), c(1,1))
pol <-st_polygon(list(p1,p2))
p3 <- rbind(c(3,0), c(4,0), c(4,1), c(3,1), c(3,0))
p4 <- rbind(c(3.3,0.3), c(3.8,0.3), c(3.8,0.8), c(3.3,0.8), c(3.3,0.3))[5:1,]
p5 <- rbind(c(3,3), c(4,2), c(4,3), c(3,3))
mpol <- st_multipolygon(list(list(p1,p2), list(p3,p4), list(p5)))

## without the unclass we get an ungrouped matrix
unlist(unclass(mpol), recursive = FALSE)
```

**Comment by edzer** [comment]
Good idea; this is now in https://github.com/edzer/sfr/commit/928905bb4130c13d9d1a24b8c2745dfc28dd9868 - I renamed the `unlist.sfg` method to `as.matrix.sfg`, since that's what it does.
