### ISSUE TITLE
Feature request: optional scale bar in plots

### ISSUE THREAD

**Issue by Robinlovelace** [edzer/sfr#236]
This plot of school accessibility by time bands in Harrogate, that I'm teaching in Leeds, demonstrates the utility of the facet plots, which I think would be even more useful if the scale were known (e.g. it's not immediately clear which colours are high):

![image](https://cloud.githubusercontent.com/assets/1825120/23385893/ef7a8508-fd4a-11e6-9ce4-04d5c690bf90.png)

Clearly not a priority but thought more feedback on `plot.sf` may be useful at some point..

**Comment by edzer** [comment]
I'd be happy to consider PRs for this, but wrote my view [here](https://stat.ethz.ch/pipermail/r-sig-geo/2017-February/025463.html). Go for ggplot to get equal scales, and scale bars.

**Comment by tim-salabim** [comment]
So does this mark the end of lattice based spatial vis?

**Comment by Robinlovelace** [comment]
OK, closing for now as it seems it's been discussed before. Can always re open if this issue rears its ugly (or hopefully beautiful) dataviz head again!

**Comment by edzer** [comment]
@tim-salabim not sure; revisiting the `spplot` code is not something I look forward to, rewriting it is not trivial. Let's see how far `ggplot` can take us.

**Comment by tim-salabim** [comment]
@edzer maybe me and @fdetsch can help out with lattice based plotting.

**Comment by edzer** [comment]
@tim-salabim help is always welcome!

@Robinlovelace I just rediscovered [this](http://r-spatial.org/r/2016/03/08/plotting-spatial-grids.html) blog post - doesn't look terribly hard to port to sf's base plot.

**Comment by Robinlovelace** [comment]
Cool - vizualisation is vital but probably after more structural (e.g. sampling) and bike shed painting (e.g. C++ code tidy) issues have been painted ; )
