### ISSUE TITLE
Make read_sf more consistent?

### ISSUE THREAD

**Issue by hadley** [edzer/sfr#237]
I think there are two minor changes to the defaults that would make `read_sf()` slightly more consistent with the other `read_` functions in the tidyverse:

* Set `stringsAsFactors = FALSE` (and don't expose it as an argument)
* Default to `quiet = TRUE`

**Comment by edzer** [comment]
Changed the defaults; I don't see why removing user choice (not exposing `stringsAsFactors`) would be a good idea.

**Comment by hadley** [comment]
I think it's mostly a good idea because it decreases the cognitive load on the user.
