### ISSUE TITLE
Feature request: NSE in st_buffer and others

### ISSUE THREAD

**Issue by etiennebr** [edzer/sfr#242]
To mimic dplyr behavior, what about using non-standard evaluation in e.g. `st_buffer`. 
```r
sf <- mutate(sf, radius = sample(1:10))
st_buffer(sf, radius)
# or
st_buffer(sf, ~radius)
# rather than
st_buffer(sf, sf$radius)
```

Other function allowing a vector of length of `sf` could benefit from that. I'd be happy to work on it, once we settle on a solution.

**Comment by edzer** [comment]
The problem with 
```r
st_buffer(sf, radius)
```
is where to search for `radius` _first_: in `sf`, or in `.GlobalEnv`?

I don't see a strong cognitive gain in using `~radius` over `sf$radius`; if you do, be my guest.

**Comment by tiernanmartin** [comment]
Here's how you might use `st_buffer` in a `dplyr` chain:

``` r
demo(nc,ask = FALSE, verbose = FALSE)
        
nc %>% 
    mutate(RADIUS = sample(1:10, n(), replace = TRUE)) %>% 
    mutate(geom = st_buffer(geom,RADIUS))
```
The NSE works because `st_buffer` is called within the `mutate` environment.

**Comment by etiennebr** [comment]
@tiernanmartin do you think having NSE outside of dplyr would be useful? I tend to use dplyr a lot, but when I'm not using it, my brain doesn't switch and I expect NSE. 

@edzer I'd implement it as [@hadley is suggesting](https://cran.r-project.org/web/packages/dplyr/vignettes/nse.html), so it looks at `.GlobalEnv` after the data provided. It would also introduce a dependency on lazyeval package, is it a blocker?

**Comment by tiernanmartin** [comment]
@etiennebr yes I also find it mentally taxing to switch back and forth between a piped workflow with NSE and a more base workflow in the `.GlobalEnv`.

It seems to me that if verbs like `st_buffer` receive an object of class `sf` in their `x` argument then NSE would be useful to implement. That way both of the following workflows would be valid and return the same result:

``` r
# passing an sf object
nc %>% 
    mutate(RADIUS = sample(1:10,n(), replace = TRUE)) %>% 
    st_buffer(RADIUS)

# passing an sfc object
nc %>% 
    mutate(RADIUS = sample(1:10,n(), replace = TRUE)) %>%    
    mutate(geom = st_buffer(geom,RADIUS))
```

**Comment by edzer** [comment]
For that, we'd only need
```r
dist = eval(substitute(dist), x)
```
in `st_buffer.sf` - I'm fine with that, don't see why we'd need dependency on lazyeval.

**Comment by etiennebr** [comment]
I'll need to check, from the top of my head I think that `eval(substitute())` only works one level-deep, but I'll need to check the consequences.

**Comment by edzer** [comment]
If no one moves this forward, I'd be happy to close - doesn't seems specific to `sf`, just nice to have.

**Comment by etiennebr** [comment]
It is indeed a nice to have, I'm sorry I haven't had much time lately. I will reopen it if I have some bandwidth. In my opinion database drivers are a higher priority.

**Comment by edzer** [comment]
... and NSE is going to change drastically with dplyr 0.6.0, it seems, maybe wait for that.

**Comment by etiennebr** [comment]
Thanks for the heads up! I haven't looked much into dplyr 0.6.0.

**Comment by mdsumner** [comment]
Details on new dplyr here and see Compatibility article as well http://dplyr.tidyverse.org/articles/programming.html

**Comment by edzer** [comment]
Get ready for quosures... I think we have one [here](https://github.com/edzer/sfr/blob/master/R/tidyverse.R#L141), but with help from @lionel-. I still need to do more to grasp the concept.

**Comment by benscarlson** [comment]
I just want to add my support for nse in sf. For me one of the most appealing aspects of sf is that it works with dplyr piped workflows. So, it is natural to want to do something like nc %>% filter(...) %>% arrange (...) %>% st_buffer(radius). It feels clumsy to have to use st_buffer(nc$radius). Also, if I have filtered and arranged the dataset through a piped workflow, does using the object from the global environmental even work correctly? I suspect it wouldn't unless there is some additional magic happening. So, would I have to break out of the piped workflow to save my filtered dataset? I think nse would make these types of data processing more elegant.

**Comment by mdsumner** [comment]
try 

```R
nc %>% filter(...) %>% arrange (...) %>% st_buffer(.$radius)
```

**Comment by etiennebr** [comment]
Personally I wrap sf operations in a `mutate`
```r
nc %>% 
  filter(...) %>% 
  arrange (...) %>% 
  mutate(
    geometry =  st_buffer(geometry, radius)
  )
```
It has the benefit of being completely compatible and not require copying the functions on sf side (although some sf operations aren't tidy, so these would require a redesign). It is also compatible with `dbplyr` if you happen to need a database backend.

**Comment by benscarlson** [comment]
These are both great suggestions and it looks like nse is not necessary after all. Thank you!
