### ISSUE TITLE
st_read_db fails on NULL geometry

### ISSUE THREAD

**Issue by etiennebr** [edzer/sfr#244]
```r
# pg <- RPostgreSQL::dbConnect(RPostgreSQL::PostgreSQL(), ...)
require("sp")
data(meuse)
pts <- st_as_sf(meuse, coords = c("x", "y"), crs = 28992)
st_write_db(pg, pts, c("sandbox", "meuse"))
DBI::dbExecute(pg, "UPDATE sandbox.meuse
                SET wkb_geometry = NULL
                WHERE \"row.names\" = '76';")
#> [1] 1

st_read_db(pg, c("sandbox", "meuse"))
#> Error in if (substr(x, 1, 2) == "0x") substr(x, 3, nchar(x)) else x : 
#> missing value where TRUE/FALSE needed
```

**Comment by edzer** [comment]
This removes the error, but now gets you a `GEOMETRY` object back.

**Comment by edzer** [comment]
Interestingly, in postgis, we see that the geometry type remains POINT
```
postgis=# select * from geometry_columns;
 f_table_catalog | f_table_schema | f_table_name | f_geometry_column | coord_dimension | srid  | type  
-----------------+----------------+--------------+-------------------+-----------------+-------+-------
 postgis         | public         | meuse        | wkb_geometry      |               2 | 28992 | POINT
(1 row)
```
In current sf, you'd get that back to POINT by deselecting the empty geom:
```r
s = st_read_db(pg, c("meuse"))
s[!st_is(s, "GEOMETRYCOLLECTION"),] %>% st_cast() %>% st_geometry() %>% class()
# [1] "sfc_POINT" "sfc"  
```

**Comment by etiennebr** [comment]
Haven't tested your commit yet, but is there a `st_is_null` or `st_empty` operator for geometries? We could use it after reading all the geoms and cast to the correct geometry.

**Comment by edzer** [comment]
`st_dimension` returns `NA` on empty geometries. It would have been nice, but `NULL` is not a valid value for a simple feature; see the standard. Of course we can do as if it is, like postgis apparently does, but then we create new problems for the interfaces to GEOS and GDAL.

**Comment by edzer** [comment]
You'll see [here](https://github.com/edzer/sfr/blob/master/R/sf.R#L371-L380) another example, where `base::merge` puts NULL values in list columns with no match, and `sf` has to fix those.

I am quite torn here: the standard does not have NULL geometries, but calls for an empty version of every geometry type, but what is the difference in meaning between an empty `MULTIPOINT` and an empty `LINESTRING`? There's an overhead in the type administration. 

Second, there is no good (wkb) representation of an empty `POINT` -- `sf` gives `POINT(NA,NA)`, GDAL returns e.g. `POINT(NaN,NaN)`, standard says nothing. Messy, and calling for more administration, e.g. [here](https://github.com/edzer/sfr/blob/master/R/plot.R#L134-L136).

**Comment by edzer** [comment]
OTOH, if we'd replace all empty geoms with NULLs, we couldn't do a clean roundtrip x -> R -> x, because we'd loose the type of the empty geom. And that was one of the motivating reasons to go away from sp.

**Comment by edzer** [comment]
Any need to keep this issue open?

**Comment by etiennebr** [comment]
Well, given that NULL breaks the standard but still exists in Postgis, maybe we could catch the error and provide a meaningful message?

**Comment by edzer** [comment]
```r
> b["76",]
Simple feature collection with 1 feature and 12 fields (of which 1 is empty)
geometry type:  GEOMETRY
dimension:      XY
bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
epsg (SRID):    28992
proj4string:    +proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.4171,50.3319,465.5524,-0.398957,0.343988,-1.87740,4.0725 +units=m +no_defs
   cadmium copper lead zinc elev     dist  om ffreq soil lime landuse dist.m
76     3.4     55  325  778 6.32 0.575877 6.9     1    1    0      Bw    750
           wkb_geometry
76 GEOMETRYCOLLECTION()
```
cause trouble, and you'll get trouble.
