### ISSUE TITLE
bug in print.sf / "[.sf"

### ISSUE THREAD

**Issue by mpadge** [edzer/sfr#248]
```
> y <- list ()
> for (i in 1:21) y [[i]] <- sf::st_point (i+1:2)
> sf::st_sf (sf::st_sfc (y))
Simple feature collection with 21 features and 0 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: 2 ymin: 3 xmax: 22 ymax: 23
epsg (SRID):    NA
proj4string:    NA
First 20 features:
   sf..st_sfc.y.
1     POINT(2 3)
2     POINT(3 4)
...
20  POINT(21 22)
Warning messages:
1: In is.na(object) :
  is.na() applied to non-(list or vector) of type 'NULL'
2: In is.na(object) :
  is.na() applied to non-(list or vector) of type 'NULL'
```
This happens because of [this line in `print.sf`](https://github.com/edzer/sfr/blob/master/R/sf.R#L315), where `n` defaults to 20, so any values `>20` call [these lines in `[.sf`](https://github.com/edzer/sfr/blob/master/R/sf.R#L239-L242) which prompts the error.

**Comment by edzer** [comment]
For some reason, I don't get these warning messages. Do you work with the latest version?

**Comment by mpadge** [comment]
Hmm, that's strange.
```
> packageVersion ("sf")
[1] '0.3.4'
```
I'll investigate reproducibility in an `lxd` container and get back to you ...

**Comment by mpadge** [comment]
It is perfectly reproducible in a fresh container setup with your `.travis.yml` - `trusty` dist; `ubuntugis ppa`, nothing else, but no longer appears with your current `dev` version (0.3.5). Closing.
