### ISSUE TITLE
sfc column name limitations

### ISSUE THREAD

**Issue by tiernanmartin** [edzer/sfr#250]
Is there a particular reason that the `sfc` column needs to be named `geom` (or `geometry`) and not something else?

Here I tried changing the name to `GEOMETRY` and found that other `sf` verbs no longer recognize this column as the geometry container:

``` r

library(magrittr)
library(sf) 
library(tidyverse) 
demo(nc, ask = FALSE)

# Change all colnames to uppercase
nc_up <- nc %>% set_colnames(toupper(colnames(nc)))

# Check the geometry - returns NULL

st_geometry(nc_up)
#> NULL

# Rename the `geom` column and check geometry - returns correct geoms

nc_up %>% rename(geom = GEOM) %>% st_geometry
#> Geometry set for 100 features 
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> epsg (SRID):    4267
#> proj4string:    +proj=longlat +datum=NAD27 +no_defs
#> First 5 geometries:
#> MULTIPOLYGON(((-81.4727554321289 36.23435592651...
#> MULTIPOLYGON(((-81.2398910522461 36.36536407470...
#> MULTIPOLYGON(((-80.4563446044922 36.24255752563...
#> MULTIPOLYGON(((-76.0089721679688 36.31959533691...
#> MULTIPOLYGON(((-77.2176666259766 36.24098205566...
```

It's not a problem for me to keep the `sfc` column name in lower case, I just wanted to check if this limitation is documented somewhere. Thanks!

**Comment by edzer** [comment]
```r
st_sf(a = 1, GEOM = st_point(0:1))
```
`sf` objects have an attribute, `sf_column`, that points to the `sfc` list-column. If you rename columns without using the `sf` api (ie. no changing the attribute too), `sf` might no longer recognize it.

**Comment by edzer** [comment]
For your case (a "broken" `sf`), `st_sf(nc_up)` should work; right now it doesn't, need to look into that. What does work is
```r
do.call(st_sf, nc_up)
```

**Comment by tiernanmartin** [comment]
I see - thanks for explaining that.

**Comment by edzer** [comment]
See #270 - `ggplot2::geom_sf` currently still makes an assumption that the sfc col is called `geometry`, but it shouldn't.
