### ISSUE TITLE
Thread on updating SQLite on gdal-dev

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#251]
There is an interesting [thread](https://lists.osgeo.org/pipermail/gdal-dev/2017-March/046203.html) on gdal-dev on handling indices in SQLite/Spatialite when inserting/deleting/updating, Sandro inter alia says:

> so we must walk on a very narrow and slippery path in
> order to keep properly aligned both the SpatialIndex
> and the indexed table

Does this also apply to GPKG?

**Comment by edzer** [comment]
Thanks! Closing now, seems not to be a serious issue, or affecting GPKG.
