### ISSUE TITLE
Non-spatial joins drop "tbl_df" "tbl" classes prevents spatial calculations

### ISSUE THREAD

**Issue by datareaver** [edzer/sfr#253]
I was trying to find the intersection of an sfc and and sf object. I received the following error:

Error in CPL_geos_op2(op, st_geometry(x), st_geometry(y)) : 
  attr classes has wrong size: please file an issue

I first did a non-spatial join to an sf, then I took that sf and tried to find the intersection. It appears doing a non-spatial join removes classes tbl_df and tbl from the object. st_intersection failed when i tried it with and sfc object.

**Comment by edzer** [comment]
Please provide a reproducible example.

**Comment by datareaver** [comment]
[spatial_issue.zip](https://github.com/edzer/sfr/files/828916/spatial_issue.zip)

```
testDT <- readRDS("testDT.rds")
ex <- readRDS("ex.rds")
inter <- st_intersection(ex, st_sf(testDT))

```

**Comment by edzer** [comment]
object `ex` has an internal inconsistency. Could you please report how it was created?
```r
> attributes(st_geometry(ex))$classes
[1] "POLYGON"
> class(st_geometry(ex)[[1]])
[1] "XY"           "MULTIPOLYGON" "sfg"        
```

**Comment by datareaver** [comment]
It was a data table with WKT in one column and other attribute columns:

zipCode, attr1, ..., attr10, wkt

Converted to sf with st_as_sf and specifying crs = 4326

It was left_join with dplyr to another table with zipCode and attributes. The table is as follows:

zipCode, attr11, ..., attr20

Final table looks like this:

zipCode, attr1, ...attr20, sfc

**Comment by edzer** [comment]
I see. Did you install sf from github, or the one from CRAN?

**Comment by datareaver** [comment]
From CRAN, sf version 0.3-4.

**Comment by edzer** [comment]
you now need to do sth like
```r
inter <- st_intersection(st_sfc(st_geometry(ex)), st_sf(testDT))
```
with `sf` from github; I'll have to look into a more robust solution. A reproducible example creating `ex` would be helpful.

**Comment by datareaver** [comment]
Ok thanks! Unfortunately, some of the data I am using cannot be shared due to licensing and I'm am pulling the WKT from an API that is not exposed to the public. I'll look into creating a different dataset that can reproduce ex.

**Comment by datareaver** [comment]
`wkt <- readRDS('wkt.rds')

sf1 <- st_as_sf(zipWKT, wkt = 'zip_geometry_wkt', crs = 4326)

dt <- data.frame(zip_code = wkt$zip_code, value = rpois(nrow(wkt), 5),
                 stringsAsFactors = FALSE)
sf2 <- sf1[ , 1:12] %>% #not sure why i have to specify the columns
  inner_join(dt[ 2:300, ], by = 'zip_code')

st_intersection(testDT, sf2)`

I believe the problem can be isolated to subsetting dt by rows. 

[spatial_issue2.zip](https://github.com/edzer/sfr/files/842548/spatial_issue2.zip)

**Comment by edzer** [comment]
`zipWKT` is missing.

**Comment by datareaver** [comment]
Use ```sf1 <- wkt```, zipWKT is redundant

**Comment by edzer** [comment]
This should get you there; you may want to pipe results to `%>% st_cast("MULTIPOLYGON")` to get rid of the `GEOMETRY` mix, at some stage, if needed.
