### ISSUE TITLE
st_as_sf should mention what column it used as geometry

### ISSUE THREAD

**Issue by etiennebr** [edzer/sfr#255]
When it guesses the geometry column, I think the message could be more precise by mentionning the name of the column it picked.
```r
st_as_sf(df)
#> more than one geometry column: ignoring all but first
```
I suggest something like:
```r
st_as_sf(df)
#> more than one geometry column: picked `geom`, use `coords=` to specify a different column.
```

**Comment by etiennebr** [comment]
I think this issue is mostly resolved, however the warning still feels weirder now that `sf` support for multiple columns. Should a warning even be provided?
``` r
# test multiple geom columns
library(sf)
library(tidyverse)

#> lag():    dplyr, stats

nc <- st_read(system.file("shape/nc.shp", package="sf"), "nc", crs = 4267, quiet = TRUE)
nc <- nc %>% 
    mutate(geog = st_transform(geometry, 4326))
#> Warning in st_sf(x, ..., agr = agr): more than one geometry column: taking
#> `geometry'; use `sf_column_name=' to specify a different column.
```
Also not clear to me what `sf_column_name=` option it refers to.

**Comment by edzer** [comment]
What did you expect to be the active geometry of `nc` after this command?

The warning message reveals from which function it was called, did you look up its docs?

**Comment by etiennebr** [comment]
It's true that `st_sf` is mentioned, but it was not directly called and I don't believe it can be accessed via mutate. So I wonder what action should be taken by the user after that warning. 

If the universal `sf` rule is to keep the geometry column until it is explicitly changed using `st_geometry(x) <- "new_col"` or `st_sf(x, sf_column_name="new_col")`, then maybe there is no need for a warning?
