### ISSUE TITLE
Test the number of coordinates within a geometry object

### ISSUE THREAD

**Issue by aTnT** [edzer/sfr#259]
`st_dimension` allows one to test if a geometry is a point, linestring or a polygon. The command below:

    st_dimension(st_sfc(st_point(0:1), st_linestring(rbind(c(0,0),c(1,1))), 
                    st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,1), c(0,0))))))

Returns `[1] 0 1 2` 

However if we run (note the polygon with two coordinate elements):

    st_dimension(st_sfc(st_point(0:1), st_linestring(rbind(c(0,0),c(1,1))), 
                    st_polygon(list(rbind(c(0,0),c(0,0))))))

We also get `[1] 0 1 2`. Is there any way to test the number of coordinates within a geometry? For intance the "polygon" above has two coordinates which shouldn' t be allowed. 

Python' s Fiona module, runs a few tests to assert that a geometry has a minimum number of coordinates elements, calculating the length of 'coordinates' [as seen here](https://github.com/Toblerity/Fiona/blob/master/tests/test_geometry.py#L147)

How can we do something equivalent in R, i.e. how can we count the number of coordinates within a geometry type?

**Comment by edzer** [comment]
`st_coordinates` returns coordinate matrices for single geometries, along with indexes to which element the coordinate belongs: 
```r
> x = st_sfc(st_point(0:1), st_linestring(rbind(c(0,0),c(1,1))), 
+                 st_polygon(list(rbind(c(0,0),c(0,0)))))
> lapply(x, st_coordinates)
[[1]]
     X Y
[1,] 0 1

[[2]]
     X Y L1
[1,] 0 0  1
[2,] 1 1  1

[[3]]
     X Y L1 L2
[1,] 0 0  1  1
[2,] 0 0  1  1

> sapply(lapply(x, st_coordinates), nrow)
[1] 1 2 2
```
Alternatively, with https://github.com/edzer/sfr/commit/5378afb361a3c78e25c5870d4501d7827c9ca09e you can use `st_is_valid`, which now returns `NA` on geometries that would otherwise have triggered an error inside GEOS due to corrupt geometry:
```r
> st_is_valid(x)
[1] TRUE TRUE   NA
```

**Comment by aTnT** [comment]
Thanks for the reply and the commit, all clear!
