### ISSUE TITLE
Build failure with sf 0.4 and geos <3.5

### ISSUE THREAD

**Issue by rundel** [edzer/sfr#260]
Current [code](https://github.com/edzer/sfr/blob/6f37b6c20a2004d099e5cad2e7b591eb2cfac6dd/src/geos.cpp#L293-L296) uses `GEOSContext_setNoticeMessageHandler_r` and `GEOSContext_setErrorMessageHandler_r` in `CPL_geos_is_valid`. These functions were only added to the geos C api in version 3.5, as such they cause a compiler error for older versions (I believe geos 3.3 and above are supported by sf).

Something like `#if GEOS_VERSION_MAJOR >= 3 && GEOS_VERSION_MINOR >= 5` for the offending lines should correct the issue. I would create a pull request but I'm not 100% sure on what the correct behavior should be for geos <3.5.

**Comment by edzer** [comment]
Thanks, well spotted!
