### ISSUE TITLE
NEWS for 0.4-0

### ISSUE THREAD

**Issue by yutannihilation** [edzer/sfr#261]
Congratulations for the release! BTW, are there any news for this version? NEWS file describes only for version 0.3-5.

https://github.com/edzer/sfr/blob/6f37b6c20a2004d099e5cad2e7b591eb2cfac6dd/NEWS.md

**Comment by edzer** [comment]
Thanks! Please interpret the 0.3-5 news as for 0.4-0; I'll try to do better next time.

**Comment by yutannihilation** [comment]
Oh, I see. Thanks for the quick reply! :+1:
