### ISSUE TITLE
sf NEWS entry from within RStudio lands on 404 Not Found

### ISSUE THREAD

**Issue by wgrundlingh** [edzer/sfr#262]
According to the [R package release information](http://r-pkgs.had.co.nz/release.html), packages should include their updates in a `NEWS.md` markdown file. [`sf`](https://cran.r-project.org/package=sf)'s [NEWS link on CRAN](https://cran.rstudio.com/web/packages/sf/news.html) points to `news.html`. Understandably this allows the package author to format their package changes using HTML to suit their needs. However this might also be the reason why clicking on the NEWS link from within RStudio leads to [404 Not Found](https://cran.rstudio.com/web/packages/sf/NEWS):

![image](https://cloud.githubusercontent.com/assets/1776164/24174319/43d7164e-0e4d-11e7-9667-72bdf12498e0.png)

![image](https://cloud.githubusercontent.com/assets/1776164/24174343/63ba26b8-0e4d-11e7-8ec7-adb59b3767f5.png)

**Comment by yutannihilation** [comment]
I think we should rather blame RStudio for this. I've seen this 404 for most of the packages I installed ¯\_(ツ)_/¯

**Comment by wgrundlingh** [comment]
@yutannihilation Perhaps. RStudio would likely set up a generic way of handling any updates, pointing to a generic URL, rather than have this coded in a package-dependent way. So my guess would be filing an issue with RStudio would point to package authors not adhering to the NEWS requirement set out by CRAN.

**Comment by yutannihilation** [comment]
`/NEWS` URL is hard coded here: https://github.com/rstudio/rstudio/blob/5116786c273a1522ff100edaf7503f8bc4ef7fbd/src/cpp/session/modules/SessionPackages.R#L441

**Comment by yutannihilation** [comment]
@wgrundlingh 
> the NEWS requirement set out by CRAN.

Ah, sorry, I didn't know the `NEWS.md` doesn't satisfy the requirements. Thanks for the information.

**Comment by edzer** [comment]
This seems to be something between CRAN and rstudio to not be in sync, nothing special to sf.

**Comment by wgrundlingh** [comment]
The latest version of RStudio seems to have fixed this issue in general.
