### ISSUE TITLE
st_perimeter

### ISSUE THREAD

**Issue by etiennebr** [edzer/sfr#268]
I think it would be useful to have an [st_perimeter](http://postgis.net/docs/ST_Perimeter.html). Is it equivalent to have `st_cast("MULTILINESTRING") %>% st_length`?

**Comment by edzer** [comment]
(how) does it deal with holes in polygons?

**Comment by etiennebr** [comment]
```r
library(sf)
#> Linking to GEOS 3.5.0, GDAL 2.1.1, proj.4 4.9.3

m <- rbind(c(0,0), c(1,0), c(1, 1), c(0,1), c(0,0))
n <- (m - 0.5) / 2 + 0.5
s <- matrix(c(2, 0), 5, 2, byrow = TRUE)

single <- list(m)  %>% st_polygon()
multi <- list(list(m), list(m + s)) %>% st_multipolygon()
half <- list(n)  %>% st_polygon()

hole <- st_difference(single, half)
single %>% st_cast("MULTILINESTRING") %>% st_length()
#> [1] 4
half %>% st_cast("MULTILINESTRING") %>% st_length()
#> [1] 2
hole %>% st_cast("MULTILINESTRING") %>% st_length()
#> [1] 6

multi %>% st_cast("MULTILINESTRING") %>% st_length()
#> [1] 8
```

**Comment by edzer** [comment]
seems like its the sum of all lengths - I don't think that justifies a separate function.

**Comment by etiennebr** [comment]
Ok, then I don't want to insist too much, but what about enabling `st_length` for polygons?, so it can be applied to all geometries (points are 0).

**Comment by etiennebr** [comment]
I believe this is a good solution.

**Comment by edzer** [comment]
This has been revisited; anything not a `LINE` (not having dimension 1) returns length 0.

**Comment by etiennebr** [comment]
This would indeed be conform to OGC specifications. So you'd add a st_perimeter() ?

**Comment by edzer** [comment]
I don't see it anywhere in the SFA standard doc. Is it part of PostGIS, and if yes, is it in liblwgeom?

**Comment by etiennebr** [comment]
You're right, it's not in the specification. I took it from postgis [`st_length`](http://postgis.org/docs/ST_Length.html)
> * This method implements the OpenGIS Simple Features Implementation Specification for SQL 1.1. s2.1.5.1
> * This method implements the SQL/MM specification. SQL-MM 3: 7.1.2, 9.3.4

It's available from [lwgeom_length()](http://postgis.net/docs/doxygen/2.2/da/de7/liblwgeom_8h_a698332aacf1c53adbebcf4a06c96d8b3.html#a698332aacf1c53adbebcf4a06c96d8b3)

**Comment by edzer** [comment]
SQL MM (ISO/IEC 13249-3) defines st_perimeter, and postGIS has [st_perimeter](http://postgis.org/docs/ST_Perimeter.html), and liblwgeom has it implemented. So, this can be added to lwgeom.

**Comment by edzer** [comment]
Sure, great idea!
