### ISSUE TITLE
Test RPostgres support

### ISSUE THREAD

**Issue by etiennebr** [edzer/sfr#269]
Should perform the database read/write tests using Rpostgres.

**Comment by edzer** [comment]
It's still not on CRAN; it would be RPostgres would recognize (and not warn about) columns of type `geometry`, this seems pretty standard now. Could you check & raise an issue there if it doesn't?

**Comment by etiennebr** [comment]
Just to be clear, I don't think we should drop support for RPostgreSQL, but I'd add tests with Rpostges if they pass. They also have tests on their side e.g. https://github.com/rstats-db/RPostgres/issues/114.

I'll test and report back.

**Comment by edzer** [comment]
It looks like RPostgres is pretty inactive; maybe revisit this when it moves again.
