### ISSUE TITLE
plot (via geom_sf) of st_union-ed sf's does not work

### ISSUE THREAD

**Issue by espinielli** [edzer/sfr#270]
I have a shapefile (i.e. unzip [shp.zip](https://github.com/edzer/sfr/files/868697/shp.zip) in `shp/`) defining 3 airspaces (in Italy).
I can read and `plot` then with the `sf` package.

```r
library(sf)
all_it <- st_read("shp/all_IT.shp")
plot(all_it)
```

![image](https://cloud.githubusercontent.com/assets/891692/24306219/1f9b02ac-10c0-11e7-99ec-e241fafa0de5.png)

I am interested in merging the 3 airspaces into one:

```r
library(dplyr)
fir_it <- all_it %>% st_union()
plot(fir_it)
```

![image](https://cloud.githubusercontent.com/assets/891692/24306308/792ad8e2-10c0-11e7-9cf0-52ea58e14282.png)

If I try with `geom_sf` 

```r
library(ggplot2) # this is installed from github
ggplot() + 
   geom_sf(all_it, mapping = aes(colour = AV_AIRSPAC)) +
    coord_sf(crs = "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs")
```
![image](https://cloud.githubusercontent.com/assets/891692/24306527/3140d22e-10c1-11e7-92b1-6dea7dabbd89.png)

If I try w/ `fir_it`

```
ggplot() + 
   geom_sf(fir_it, mapping = aes(colour = AV_AIRSPAC)) +
    coord_sf(crs = "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs")
```
I get an error I cannot understand how to bypass/solve it (if at all possile):

> Error: ggplot2 doesn't know how to deal with data of class sfc_POLYGON/sfc

Any indication of a workaround or examples/documentation for better understanding is welcome.
Thanks!

**Comment by edzer** [comment]
Try convert it to an `sf` object with
```r
it <- st_sf(a = 1, geom = fir_it)
```
You can leave the `a=1` out, but I'm not sure whether `ggplot` wants sth to give color to.

**Comment by espinielli** [comment]
Thank you for the hint.
Here is what worked:

```
> it <- st_sf(AV_AIRSPAC = 'LIFIR', geom = fir_it)
> it
Simple feature collection with 1 feature and 1 field
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: 6.644167 ymin: 36.5 xmax: 19 ymax: 47.08694
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
  AV_AIRSPAC                           geom
1      LIFIR POLYGON((19 38.883333333, 1...
> ggplot() + 
     geom_sf(it, mapping = aes(colour = AV_AIRSPAC)) +
     coord_sf(crs = "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 units=m +no_defs")
TEXT_SHOW_BACKTRACE environmental variable.
TEXT_SHOW_BACKTRACE environmental variable.
```

![screen shot 2017-03-25 at 4 02 09 pm](https://cloud.githubusercontent.com/assets/891692/24323342/7b88f826-1174-11e7-8d3e-ec99eb28ff2a.png)

Problem solved. Thanks again.

PS: Where is `TEXT_SHOW_BACKTRACE environmental variable.` coming from? (googled without success...)

**Comment by espinielli** [comment]
Well something weird is the grid/latitudes/longitudes...it looks like they have "moved"...

**Comment by espinielli** [comment]
Strange

if I plot them without `coord_sf` they overlap
```
aa <- ggplot() + geom_sf(all_it, mapping = aes(colour = AV_AIRSPAC)) + geom_sf(it, mapping = aes(colour = AV_AIRSPAC), fill = "yellow",alpha= 0.1)
aa
```

![screen shot 2017-03-25 at 4 25 28 pm](https://cloud.githubusercontent.com/assets/891692/24323554/b8c0d652-1177-11e7-9176-a2dafadbc572.png)

But when I add `coord_sf` I get:

```
bb <- aa + coord_sf(crs = "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs")
bb
```

![screen shot 2017-03-25 at 4 29 46 pm](https://cloud.githubusercontent.com/assets/891692/24323597/5523437c-1178-11e7-9e6c-c65ccfa4fd80.png)

(there is a small dot in the lower left corner...)

Did I do something stupid? Any idea of what?

**Comment by edzer** [comment]
I think I caught it: if, instead of
```r
it <- st_sf(AV_AIRSPAC = 'LIFIR', geom = fir_it)
```
you call the geometry list-column `geometry`:
```r
it <- st_sf(AV_AIRSPAC = 'LIFIR', geometry = fir_it)
```
it works. I think this is a bug in `ggplot` - @hadley?

```r
it <- st_sf(AV_AIRSPAC = 'LIFIR', geometry = fir_it)
aa <- ggplot() + geom_sf(all_it, mapping = aes(colour = AV_AIRSPAC)) + geom_sf(it, mapping = aes(colour = AV_AIRSPAC), fill = "yellow",alpha= 0.1)
aa + coord_sf(crs = "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs")
```
![aa](https://cloud.githubusercontent.com/assets/520851/24326174/bd96135a-11a8-11e7-991e-992abcf42cf9.png)

**Comment by espinielli** [comment]
You are right, `geom_sf` code at [lines 155-160](https://github.com/tidyverse/ggplot2/blob/08e135e020428ed78158b8feccc012eae02773b0/R/sf.R#L155-L160) should work even w/ `geom` instead of `geometry` ...

Maybe it is the [following `if`](https://github.com/tidyverse/ggplot2/blob/master/R/sf.R#L161-L163) that doesn't set the *automatically determined* name of the geometry column just because `mapping$geometry` is not NULL...but I do not know how to inspect the mapping myself to validate this hypothesis. @hadley ?
