### ISSUE TITLE
Overwrite argument in st_write function.

### ISSUE THREAD

**Issue by Nowosad** [edzer/sfr#274]
```R
library('sf')
nc = st_read(system.file("shape/nc.shp", package="sf"), quiet=TRUE)

st_write(nc, 'my_file.gpkg') # save for the first time - works

# I made some changes to nc object

st_write(nc, 'my_file.gpkg') # error - "Dataset already exists."
st_write(nc, 'my_file.gpkg', update = TRUE) # error "Layer creation failed."
st_write(nc, 'my_file.gpkg', layer_options = 'OVERWRITE=YES') # error - "Dataset already exists."
st_write(nc, 'my_file.gpkg', layer_options = 'OVERWRITE=YES', update = TRUE) # works
```

Above you can find my struggles with overwriting a file.  An alternative to that is to delete the file from a hardrive and try again.

Is it possible to implement a simple "overwrite" argument, such as: ?
`st_write(nc, 'my_file.gpkg', overwrite = TRUE)
`

**Comment by edzer** [comment]
The story is a bit more complicated, since you can overwrite dsn's or layers, and an `overwrite` option would not make clear what to overwrite; in your commands above, at least it is clear that `overwrite` is an option that concerns the layer. For instance,
```r
st_write(nc, 'my_file.gpkg', "second_nc", update = TRUE)
```
adds a layer `second_nc` to `my_file.gpkg`; would you have expected `my_file.gpkg` to be overwritten with `overwrite=TRUE`, or layer `second_nc` in `my_file.gpkg` to be overwritten, in case it were already there?

See also `?writeOGR` which has more sensible arguments. We're looking at a single interface for nearly 80 drivers, many of which are not simply files.

https://github.com/edzer/sfr/commit/2e2b49c131ff2aabacd5e396bdd6db275acbda29 adds GPKG as one of the drivers for which `update` is `TRUE` by default.

**Comment by Nowosad** [comment]
I thought about the `overwrite` option as "delete an old file and create a new one". I was not aware of any writable drivers, which are not files. Are there any?

**Comment by edzer** [comment]
All the database drivers; gpkg is both: database and file, and so are spatialite, sqlite.
```r
> unlist(sf:::prefix_map)
       couchdb        db2odbc           dods            gft          mssql 
     "CouchDB"      "DB2ODBC"         "DODS"          "GFT" "MSSQLSpatial" 
         mysql            oci           odbc             pg            sde 
       "MySQL"          "OCI"         "ODBC"   "PostgreSQL"          "SDE" 
```
(not sure if all are writable)

**Comment by Robinlovelace** [comment]
Could one option would be for `overwrite` to only apply to drivers which create files, in which case it would delete the old one (or ones for .shp files). For the database drivers (or more defensively any driver that accepts multiple layers), `overwrite` could fail with a suitable error message. That's my 10 cents anyway - understand it's a complex issue and that this option may already have been considered (seems the most logical to me).

**Comment by edzer** [comment]
I like the simplicity, but is a gpkg a file, or a database? gpkg motivated this issue in the first place.

**Comment by Robinlovelace** [comment]
`gpkg` can be both so, playing safe, erring on the side of caution and programming defensively I say it should be treated as a DB to avoid overwriting it. The user can always hit `DELETE` if they get really pissed off with that weird `x.gpkg` file clogging up their hard-disk!

**Comment by Robinlovelace** [comment]
So would be happy with an Error for `gpkg` files but overwrite for `geojson` etc.

**Comment by edzer** [comment]
Rather than have an ambiguous `overwrite=TRUE`, I'd opt for a non-rigorous `delete_datasource=TRUE`, which simply tries to delete the entire data source before attempting to write. This is what `rgdal::writeOGR` does, what GDAL offers, and avoids speculative guessing on the sf-side.

**Comment by Robinlovelace** [comment]
`overwrite = TRUE` will be less ambiguous and more cross-compatible with other packages for most users I think. If you say what it does, that should be fine, e.g.:

```r
#' @param overwrite TRUE or FALSE (default) value determining whether the original file should be overwritten by new data. Only works for drivers that write a single layer to a file.
```

**Comment by edzer** [comment]
I see how convenient this would be from a user perspective, and would be happy to consider a PR implementing this.

**Comment by Robinlovelace** [comment]
:+1: If you could point us to the relevant file I'd be happy to take a look. @Nowosad may also be interested in this. Good challenge.

**Comment by edzer** [comment]
R function [st_write](https://github.com/edzer/sfr/blob/master/R/read.R#L153) and c++ function [CPL_write_ogr](https://github.com/edzer/sfr/blob/master/src/gdal_write.cpp#L108).

**Comment by etiennebr** [comment]
`st_write_db` uses `overwrite = TRUE` option to replace a table (used to be `drop_table`). Following this debate, should it be updated to something else? I think `overwrite` is fine, but I'm wondering if it's consistent with `st_write`.

**Comment by Robinlovelace** [comment]
Thinking about this, I suspect that it would be better for usability and maintenance if `st_write()` could only write static files and `st_write_db()` could only write to databases. Some issues arise (specifically the need to call the overwrite-for-static-files argument `drop` rather than the more intuitive, commonly used and probably expected `overwrite`) from the fact that `st_write()` writes to dbs and files I think.

On a related note (and heads-up @Nowosad if think `drop = TRUE` in `st_write()` fails to overwrite the existing file due to GDAL's behaviour - got a vague plan to fix that if I get some time but think discussing this wider issue of the distinction between `st_write()` and `st_write_db()` first would be idea. What are your thoughts on this Edzer?

**Comment by edzer** [comment]
My thoughts on this is that GDAL is a rather complicated piece of software, and that you guys have shown wishes to make things simpler on the R side, but have so far made no efforts to touch any C++. If we'd go your way, we'd confuse users who do understand GDAL, or who are simply looking at another driver than you do. The simple example is GPKG: is it a file? is it a database? Yes, yes.

Right now, `st_write()` interfaces GDAL, `st_write_db()` _does not_ but directly interfaces DBI/PosgreSQL (probably no other databases - I would be surprised. Interfacing all databases would be nice, but I suspect either DBI is too immature or standardisation of spatial database implementations is too heterogeneous for that, or both.)

Why are we working on `st_write_db()`? Good question. I believe it's one way out of R not being able to process massive spatial datasets: your dataset can be the result of a query, taking massive data piece by piece.

As for `st_write_db()`, I suggest to go back to calling `overwrite` `drop`, as that is what we do. 

There's still the option to make GDAL delete data sources before trying to write (as an _alternative_ to update), and also the option to improve examples for those who do not understand anything of [crud](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete).

**Comment by Robinlovelace** [comment]
Thanks for the explanation, makes a little more sense now. `drop` in `st_write_db()` sounds good but I'm not enough a user of DBs at this stage to comment on that from a users perspective +1 for examples. On that note, any idea what we should do about `update = TRUE` updating `.shp` files but not `.geojson` ones?

**Comment by edzer** [comment]
Regarding the update inconsistency between .shp and .geojson, I would try this functionality without R, i.e. with a ogr2ogr call using GDAL release version, so we can find out whether this is a problem with R/sf gdal interface, or with the gdal driver code.
