### ISSUE TITLE
st_union issues

### ISSUE THREAD

**Issue by bhaskarvk** [edzer/sfr#275]
I'm trying to migrate my tilegramsR package from sp to sf.
One of the operations I do is combine polygons by an attribute. I was using `rmapshaper::ms_dissolve` for it

Here's how it works in the old `sp` way of things

```r
library(sp)

evs <- tilegramsR::Pitch_US_Population_2016_v1
class(evs)
plot(evs) # Each polygon is an electoral vote

# Merge electoralvote polygons to state polygons using rmapshaper
evs_states <- rmapshaper::ms_dissolve(evs, 'state')
plot(evs_states) # Each polygon is a state
```

Before Combining

![Imgur](http://i.imgur.com/1HwLwAj.png)

After `rmapshaper::ms_dissolve`

![Imgur](http://i.imgur.com/JMvktiy.png)

I converted the `evs` to an sf object and then tried `st_union` after grouping by state, but I get some extra lines (see California, Florida states).

```r
sf_evs <- st_as_sf(evs)
plot(sf_evs['state'])

sf_evs_states <- dplyr::group_by(sf_evs, state) %>%
  dplyr::summarise(geometry = st_union(geometry)) %>%
  dplyr::ungroup()

plot(sf_evs_states['state'])
```

![Imgur](http://i.imgur.com/snAkHCT.png)

Full code is uploaded at [Rpubs](http://rpubs.com/bhaskarvk/sf-tilegrams)

**Comment by edzer** [comment]
Nice job for setting the precision: use e.g.
```r
st_precision(sf_evs) = 10000
```
(or use `st_set_precision in a pipe) after defining `st_evs`:
![evs](https://cloud.githubusercontent.com/assets/520851/24367275/569c7ef8-131c-11e7-9a7d-42bbcfd79971.png)

**Comment by bhaskarvk** [comment]
That works!
