### ISSUE TITLE
rbind.sf() seems to erase proj4string

### ISSUE THREAD

**Issue by remi-daigle** [edzer/sfr#281]
Let me start by saying I love this package! Great work!

I have been playing with it to explore it's capabilities and came across what I think is a few bugs (I'll post separate issues for the other bug).

I tried to rbind two 'sf' dataframes, but doing so seems to obliterate the projection information. See the example below:

```
library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"))

# subset of rows to bind later
nc2 <- nc[1:3,]
nc3 <- nc[4:6,]

# subetting does not afect the proj4string, as expected
st_geometry(nc)
st_geometry(nc2)
st_geometry(nc3)

# rbind seems to wipe the proj4string
nc4 <- rbind(nc2,nc3)
st_geometry(nc)
st_geometry(nc4)
```

**Comment by edzer** [comment]
Doesn't happen here. Which version do you use?

**Comment by remi-daigle** [comment]
Oops, I was using 0.3-4 from CRAN (installed just a few weeks ago), updating to the latest version resolved the issue. Apologies for the inconvenience.
