### ISSUE TITLE
geoms vs geometry column names

### ISSUE THREAD

**Issue by remi-daigle** [edzer/sfr#282]
I'm now using sf version 4.2 downloaded from github today. I'm honestly not certain if this is a bug or a feature but when I use `st_intersection()` I get some unexpected behaviour and I cannot understand why based on the documentation.
```
library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"))
# subset of rows to intersect later
nc2 <- nc[1:3,]
nc3 <- nc[1:6,]

# subetting does not afect the variable names, as expected
names(nc)
names(nc2)
names(nc3)

# however, the output of st_intersection changes 'geometry' into 'geoms'
nc4 <- st_intersection(nc2,nc3)
names(nc4)

# and also changes the sfc_MULTIPOLYGON into sfc_GEOMETRY
str(nc4)
str(nc3)
```
I'm not sure if the switch from 'geometry' to 'geoms' is intentional, and/or what it means.

**Comment by edzer** [comment]
What in the documentation exactly gave you a reason to not expect these results?

**Comment by remi-daigle** [comment]
I guess my question was poorly worded, it wasn't anything in particular in the documentation that led me to expect a certain result. But I could not find anything that described why sometimes the sfc column is named `geometry` and others it's called `geoms`. My expectation was that they would always be named the same because I have no reason to believe that they are different, but since they weren't I assumed it was either a bug or intentional. If it was intentional, then I expected to find 'why' in the documentation, but failed to do so.

Similarly, I could not find why the sfc column goes from `sfc_MULTIPOLYGON` to `sfc_GEOMETRY` after using `st_intersection()`. It is my understanding that `sfc_MULTIPOLYGON` is essentially a list of multipolygons, while `sfc_GEOMETRY` is a list that contains a mix of simple features (e.g. multipolygons, and multipoints). I don't understand why, if my input for `st_intersection()` is only two sets of `sfc_MULTIPOLYGON`, then why is the output `sfc_GEOMETRY`? What is 'added' to the `sfc_MULTIPOLYGON` to make it an `sfc_GEOMETRY`?

Perhaps I missed or misunderstood something, or perhaps the documentation is missing some of that explanation. Otherwise it could a legitimat bug?

**Comment by edzer** [comment]
Did you read the vignettes?

**Comment by remi-daigle** [comment]
Yes

**Comment by edzer** [comment]
The first vignette describes how an intersection can result in a mix of geometry types. The third describes how a set of features with different geometry types gives a `GEOMETRY` column.

The geometry list-column has no predefined name; `sf` objects can have more than one geometry list-column. For `obj`, `attr(obj, "sf_column")` gives the name of the "active" geometry list-column.

**Comment by remi-daigle** [comment]
OK, thank you, that makes sense for the mix of geometry types! I think I was looking to find something linked to the different column names since I thought those two issues were related. 

Yes, I understood that the geometry list-column name is fairly arbitrary. However, having different functions return different names is definitely non-intuitive. I thought since they were named differently, they would be fundamentally different.

I think I now understand what my issue was, but I would recommend being consistent in naming the geometry list-column to avoid confusion. I probably would have not been so confused had I not been chasing the 'red-herring' that was the column name.

**Comment by edzer** [comment]
I wished life was that simple.
