### ISSUE TITLE
st_write does not expand tildes automatically

### ISSUE THREAD

**Issue by Robinlovelace** [edzer/sfr#283]
Just testing this - no major issue and happy for it to be a wontfix, as long as it's documented, but just thought it useful to flag as an issue as I don't think anyone else has yet:

```r
x = st_read(system.file("shape/nc.shp", package="sf"))
st_write(x, "/tmp/x.geojson") # works
st_write(x, "~/x.geojson") # fails
st_write(x, "x.geojson") # works
```

Interestingly, relative file paths work without the tilde `~`.

**Comment by edzer** [comment]
Please correct the title of this issue (since you acknowledge relative paths work), and try
```r
st_write(x, path.expand("~/x.geojson"))
```

**Comment by Robinlovelace** [comment]
That's the one.
