### ISSUE TITLE
aggregate in sf

### ISSUE THREAD

**Issue by GreenStat** [edzer/sfr#286]
Hi,
not sure if this is an error, bug  or lack of documentation ....

with this sf object

```
library(sf)
library(tidyverse)

data(meuse, package = "sp")
meuse_sf = st_as_sf(meuse, coords = c("x", "y"), crs = 28992, agr = "constant")
#  
meuse_sf %>% str
# suppresed output
```

I tried aggregate  with several options:

```
meuse_sf %>% aggregate(by=list(meuse_sf$soil))
Error in match.fun(FUN) : argument "FUN" is missing, with no default
#oke we need FUN

meuse_sf %>% aggregate(by=list(meuse_sf$soil), FUN="first")
Error in aggregate.data.frame(x, list(Group.1 = by), FUN, ..., simplify = FALSE) : 
  arguments must have same length
```
I also tried  other options for FUN (mean, max  etc) and  with 'union=TRUE'  but nothing seems to work

NB in `sp` this works
```
aggregate(as(meuse_sf,'Spatial'),by=list(meuse_sf$soil), FUN="first") 
```

Any thoughts ?

**Comment by Nowosad** [comment]
What do you think about this solution:

```
aggregate_meuse_sf <- meuse_sf %>% 
        group_by(soil) %>% 
        summarise()
```

**Comment by edzer** [comment]
Hi!
yeah, the sf behavior was (documented) such that `by=meuse_sf$soil` would have worked, without the `list()`. Since the `list()` is in line with `stats::aggregate` (and `sp::aggregate`), I now changed code such that a list is required (and hence multiple aggregation predicates can be defined). Thanks!

**Comment by Nowosad** [comment]
@edzer Is there a reason to name this function `aggregate`and not `st_aggregate`?

**Comment by edzer** [comment]
Yes: it is not a function but a method (`aggregate.sf`) for an existing function (`stats::aggregate`). We also don't write a `st_subset` when writing a method for `[`.
