### ISSUE TITLE
st_set_crs malfunction

### ISSUE THREAD

**Issue by mike42trees** [edzer/sfr#289]
I want to reproject a set of latlong points, so I have built them into an sfc object, but need to set an epsg and proj4string before reprojecting.  The output from the st_set_crs function indicates that it has worked, but if I immediately look at my sfc object, it has lost the epsg and proj4string data

> st_set_crs(markers.sfc, 4326)
Geometry set for 1 feature 
geometry type:  MULTIPOINT
dimension:      XY
bbox:           xmin: -56.67 ymin: 37 xmax: 35.95 ymax: 78.9
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
MULTIPOINT(12.22 78.9, 35.95 69.15, 19.13 74.38...

> markers.sfc
Geometry set for 1 feature 
geometry type:  MULTIPOINT
dimension:      XY
bbox:           xmin: -56.67 ymin: 37 xmax: 35.95 ymax: 78.9
epsg (SRID):    NA
proj4string:    NA
MULTIPOINT(12.22 78.9, 35.95 69.15, 19.13 74.38...>

**Comment by edzer** [comment]
`st_set_crs` returns an object with crs set, but doesn't modify its argument, as R passes arguments by value. If you want its return value, either assign that
```r
markers.sfc = st_set_crs(markers.sfc, 4326)
```
or use the replacement function `st_crs<-`:
```r
st_crs(markers.sfc) = 4326
```

**Comment by mike42trees** [comment]
Thanks - I should have thought of that.
Mike

**Comment by valentinitnelav** [comment]
Thanks @edzer for clarifications. I also thought that simply calling `st_set_crs` will set the CRS (I needed to set it to NA), so I tried
```r
st_set_crs(my_sf, NA) 
# then I tried
st_set_crs(my_sf, NA_crs_)
# then I finally arrived to
st_crs(my_sf) <- NA
```
I am also biased because I use `data.table` package syntax, where all set* functions change their input by reference, so this anchored my expectations of anything that sounds like "set*" :D
