### ISSUE TITLE
How can I convert area units?

### ISSUE THREAD

**Issue by Robinlovelace** [edzer/sfr#291]
Here's what I mean (sorry not reproducible):

```r
st_area(world)[1:3] / 1000000 
## Units: m^2
## [1]  652270.1 1245463.7   29694.8
```

That is not true.

This is the correct answer:

```r
st_area(world)[1:3] 
## Units: m^2
## [1] 6.522701e+11 1.245464e+12 2.969480e+10
```

I realise this issue may be impossible to 'fix'. Would be happy if it's documented clearly thought which I'd class as a fix.

Out of interest, what would be the best way to switch the answer to sqkm?

**Comment by Robinlovelace** [comment]
Update: I've figured out that this gets rid of the units:

```r
attributes(world$area) = NULL
```

**Comment by Robinlovelace** [comment]
And that this also works:

```r
as.numeric(st_area(world) / 1000000 )
```

**Comment by edzer** [comment]
What you did was not a unit conversion, but dividing an area by a million, and the answer is true. Try:
```r
> (x = st_area(nc)[1:3])
Units: m^2
[1] 1137388604  611077263 1423489919
> set_units(x, km^2)
Units: km^2
[1] 1137.3886  611.0773 1423.4899
```

**Comment by Robinlovelace** [comment]
Nice.

**Comment by richpauloo** [comment]
Very nice!

For anyone else who follows this thread, don't forget that `set_units()` is part of the `{units}` package. Try `units::set_units()`.
