### ISSUE TITLE
Error when plotting units generated by sf

### ISSUE THREAD

**Issue by Robinlovelace** [edzer/sfr#292]
Reproducible (this time) code:

```r
library(sf)
nc = st_read(system.file("shape/nc.shp", package="sf"))
nc$a = st_area(nc)
plot(nc["BIR74"]) # no problem
plot(nc["a"]) # error

## Error in Ops.units(range(x, na.rm = TRUE), 0) : 
##   both operands of the expression should be "units" objects
```

**Comment by edzer** [comment]
Annoying. Fixed in https://github.com/edzer/sfr/commit/b510f42627d24bc8ee0ba9a5b55de9ea0b3a4d9c.

**Comment by michaeldorman** [comment]
I'm seeing the same error when running the above code, using 'sf' version 0.5-5

**Comment by edzer** [comment]
Should work now. Thanks!

**Comment by michaeldorman** [comment]
Thanks for the quick reply!

The 'plot' error does not appear now. However, there seems be a strange behavior in the graphical output when the column contains 'NA's. 

For example, replacing some of the values in the 'area' column with 'NA' does not result in those polygons being blank on the plot. 

Reproducible example -

```
library(sf)
nc = st_read(system.file("shape/nc.shp", package="sf"))
nc$a = st_area(nc)
plot(nc["a"]) # Plot 1
nc$a[1:50] = NA
plot(nc["a"]) # Plot 2
```

In 'Plot 2' half of the polygons should appear blank. Instead, their colors are just different -

Plot 1
![rplot1](https://user-images.githubusercontent.com/9386655/33874466-92e5d440-df27-11e7-9912-4dd23ce92762.png)
Plot 2
![rplot2](https://user-images.githubusercontent.com/9386655/33874471-984e6e06-df27-11e7-8bf0-8036d1e3d0ba.png)

**Comment by edzer** [comment]
OOPS! Thank you, should be fixed now!

**Comment by michaeldorman** [comment]
Great, thanks! 

Now it works fine - 

Plot 1
![rplot1](https://user-images.githubusercontent.com/9386655/33882322-5f4bf6f0-df40-11e7-872b-263538652efb.png)

Plot 2
![rplot2](https://user-images.githubusercontent.com/9386655/33882328-64d51e1c-df40-11e7-8b40-a37bbf23ef59.png)
