### ISSUE TITLE
st_line_sample type = "regular" are not regular

### ISSUE THREAD

**Issue by joethorley** [edzer/sfr#299]
the `regular` function in `st_line_sample` with `n = 3` takes samples at 1/6,  3/6, 5/6 spacings.
```
regular = function(n) { (1:n - 0.5)/n }
```

I'm thinking a replacement or alternative (type = "equidistant"?) should be 
```
regular = function(n) { 1:n / (n + 1) }
```
which with `n = 3` give samples at 1/4, 2/4 and 3/4 spacings.

I'm happy to do a pull request if you agree.

**Comment by edzer** [comment]
Would you argue that 1/6, 3/6 and 5/6 are not equidistant? What's the compelling use case to add this?

**Comment by joethorley** [comment]
They are not equidistant in the sense that the line is not broken into equal length segments. If one only focuses on the distance between the intermediate points then one can argue that  1/10, 5/10 and 9/10 are just as equidistant as 1/6, 3/6 and 5/6. We are trying to use the function to reconstruct the position of individuals at equal intervals as they move from point A to point B. We know where they are at the start and end and want to know where they are when they are 1/4, 2/4 and 3/4 of the way along.

**Comment by edzer** [comment]
Don't you want 0 and 1 included, then?

**Comment by joethorley** [comment]
You can argue it either way - since they are easy to include or exclude. I would prefer 0 and 1 be included.

**Comment by joethorley** [comment]
the only trouble is if one sets n = 1 it is not possible to include 0 and 1.

**Comment by joethorley** [comment]
I guess one could go 
n = 1: 1/2
n = 2 0/2 and 2/2
n = 3 0/2 and 1/2 and 2/2

**Comment by edzer** [comment]
How about adding an argument, e.g. `sample`, that should take numbers between 0 and 1 (inclusive) that are then being used instead of `fn(n[i])`?

**Comment by joethorley** [comment]
I like that idea. Do you want me to implement? and do you think `sample` should replace the arguments `n`, `density` and `type`?

**Comment by edzer** [comment]
Yes; no, but it shall overrule them.

**Comment by joethorley** [comment]
Roger that - await my pull request!

**Comment by joethorley** [comment]
Seems to me little point in passing a function unless it is going to use `n` i.e. unless it takes one or more arguments all it is going to do is return a vector of numbers between 0 and 1. Would you like sample to be a vector of numbers between 0 and 1 or would you like sample to take n (or another argument)?

**Comment by edzer** [comment]
a vector with numbers between 0 and 1 inclusive.

**Comment by joethorley** [comment]
Roger that

**Comment by joethorley** [comment]
pull request
https://github.com/edzer/sfr/pull/300
