### ISSUE TITLE
anything similat to sp::over() ?

### ISSUE THREAD

**Issue by tyokota** [edzer/sfr#301]
Thank you for creating the sfr package. For the most part, working in R with GIS has been much more tolerable. With that said, I wanted to conduct some functions using the sp package. For example, I wanted to use ```sp::over()``` with point and polygon data. I got the following error message:

```unable to find an inherited method for function ‘over’ for signature ‘"sf", "sf"’```

Any suggestions on getting this done with sfr? Thanks.

**Comment by Nowosad** [comment]
Take a look at this page - https://github.com/edzer/sfr/wiki/migrating

**Comment by edzer** [comment]
`sp::over` did a lot of different things depending on its precise inputs; I'm happy we no longer have that. In case you have difficulty doing one of these things, please report back here, or on a new issue with more specific title.
