### ISSUE TITLE
Upcoming dplyr release breaks methods for sf objects

### ISSUE THREAD

**Issue by mstrimas** [edzer/sfr#304]
The upcoming `dplyr` release outlined [here](https://blog.rstudio.org/2017/04/13/dplyr-0-6-0-coming-soon/) overhauls the approach to NSE, and deprecates all the SE verbs (e.g. `select_()`). With these changes the `dplyr` verbs for `sf` objects no longer work. In some cases an error is raised, in others the code runs error free but strips the `sf` class from the resulting object.

```
# install development version
devtools::install_github("hadley/dplyr")
library(dplyr)
library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"), stringsAsFactors = FALSE)
# error
select(nc, AREA)
distinct(nc, SID74)

# strip sf class, converts to normal data frame
mutate(nc, area = AREA * 100) %>% class()
group_by(nc, SID74) %>% class()
filter(nc, AREA > 0.2) %>% class()
```

**Comment by edzer** [comment]
Premature excitement IMO, see my answer at #42.

**Comment by mstrimas** [comment]
@hadley possible backwards compatibility issue for SE dplyr verbs here
