### ISSUE TITLE
st_write KML output mixes up columns

### ISSUE THREAD

**Issue by gjuggler** [edzer/sfr#308]
I'm running into an issue when trying to output KML files with `<SimpleData>` entries corresponding to non-geometry columns. Here's a minimal example:

```
library(sf)
geom = st_sfc(st_point(1:2), st_point(3:4))
features = st_sf(
  geom=geom,
  first=c('bar', 'baz'),
  second=c(123, 456),
  third=c('aaa', 'zzz'))
head(features)
st_write(features, "test.kml", driver='kml', update=TRUE)
st_write(features, "test.txt", driver='GeoJSON', update=TRUE)
```

The GeoJSON output is fine, but the KML output (included at bottom) has a couple issues:

1. The first two non-geom columns (`first` and `second`) are getting put into the `<name>` and `<description>` tags of the `<Placemark>`.
2. The value of the third non-geom column (`third="aaa"`) is getting placed in a `<SimpleData>` tag, but with the column name of the first non-geom column (`first`).

Is there some mix-up happening on the way down to the gdal call?

Here's some info about my system:

```
$library(sf)
Linking to GEOS 3.4.2, GDAL 2.1.2, proj.4 4.9.1

$sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.4

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.4-1

loaded via a namespace (and not attached):
[1] httr_1.2.1    magrittr_1.5  R6_2.2.0      DBI_0.6-1     tools_3.3.3   units_0.4-3   Rcpp_0.12.10 
[8] udunits2_0.13 grid_3.3.3   
```

```
# test.kml

<?xml version="1.0" encoding="utf-8" ?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document id="root_doc">
<Schema name="test.kml" id="test.kml">
	<SimpleField name="first" type="string"></SimpleField>
	<SimpleField name="second" type="float"></SimpleField>
	<SimpleField name="third" type="string"></SimpleField>
</Schema>
<Folder><name>test.kml</name>
  <Placemark>
	<name>bar</name>
	<description>123</description>
	<ExtendedData><SchemaData schemaUrl="#test.kml">
		<SimpleData name="first">aaa</SimpleData>
	</SchemaData></ExtendedData>
      <Point><coordinates>1,2</coordinates></Point>
  </Placemark>
  <Placemark>
	<name>baz</name>
	<description>456</description>
	<ExtendedData><SchemaData schemaUrl="#test.kml">
		<SimpleData name="first">zzz</SimpleData>
	</SchemaData></ExtendedData>
      <Point><coordinates>3,4</coordinates></Point>
  </Placemark>
</Folder>
</Document></kml>
```

**Comment by edzer** [comment]
Seems like a KML driver bug to me -- driver `libkml` does not have this behaviour -- but this commit, inspired by what `rgdal` does, seems to solve it.

**Comment by gjuggler** [comment]
Thanks for the super quick fix!! :clap:

**Comment by ldemaz** [comment]
I am getting the same behavior as initially reported by @gjuggler. Using the same example:

**Comment by edzer** [comment]
Unsurprisingly, I get the same output as your linux output. Maybe this has to do with different versions of GDAL used by sf, or of libkml used by GDAL? Can you reproduce similar roundtrips with `rgdal`?

**Comment by ldemaz** [comment]
Sorry for the slow response.  Okay, so I can no longer reproduce the result on my mac using `sf`. However, using an `rgdal`/`sp` only approach, I get this:
