### ISSUE TITLE
st_write_db(row.names = FALSE) 

### ISSUE THREAD

**Issue by andreasLD** [edzer/sfr#312]
I recently used st_write_db() to upload a sf-object to my PostgreSQL-DB. R's row.names are included as a column and I haven't found a way to not include it (like in write.csv(row.names = FALSE) for example). Is this planned to be included? Thx

**Comment by edzer** [comment]
Good suggestion! @etiennebr ?

**Comment by edzer** [comment]
you can give argument `row.names = FALSE` in a call to `st_write_db`; it's being passed on to `DBI::dbWriteTable`:
```r
demo(nc)
# set up con
st_write_db(con, nc, "nc", row.names = FALSE)
```
