### ISSUE TITLE
Changing GEOS version?

### ISSUE THREAD

**Issue by zross** [edzer/sfr#314]
Sorry to bother you with this... I'm wondering how `sf` is determining which version of GEOS to use, I'd like to use 3.6.1 so I can work with the `sf_voronoi` function and I'm getting a warning about the version needing to be 3.5. I have updated GEOS on my system (in two places) to be 3.6.1 and I was able to successfully force `rgeos` to use the updated version with

```bash
sudo R CMD INSTALL rgeos_0.3-23.tar.gz --configure-args='--with-geos-config=/Library/Frameworks/GEOS.framework/unix/bin/geos-config'
```

But I can't seem to find a way to do this for `sf`. I updated my `$PATH` to point to GDAL 2.1.3 and the GEOS 3.6.1 and re-installed `sf` but I still get the notice when I load `sf`  -- `Linking to GEOS 3.4.2, GDAL 2.1.2, proj.4 4.9.1`.

I'm not sure where `sf` is finding GEOS. The version of GDAL it's using seems to be in `/Library/Frameworks/GDAL.framework/Versions/2.1` but when I do `./gdal-config --dep-libs` I see nothing.

Any guidance?

**Comment by edzer** [comment]
Zev, I will check whether I can reuse the `--with-xxxx-config` options from `rgdal` and `rgeos`, sounds useful and shouldn't be too hard.

**Comment by zross** [comment]
Wow, that's a fast response! Short-term are there any work-arounds?

**Comment by edzer** [comment]
This should work now the way it does for `rgeos`. The `--with-gdal-config` option was already there.

**Comment by zross** [comment]
Wow what service :)

Where should I grab the package with the updates, here on GitHub presumably?

**Comment by edzer** [comment]
Yes.

On 27 April 2017 15:03:30 CEST, zross <notifications@github.com> wrote:
>Wow what service :)
>
>Where should I grab the package with the updates, here on GitHub
>presumably?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/edzer/sfr/issues/314#issuecomment-297707044

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
