### ISSUE TITLE
parsing raw GPKG binary geometry columns

### ISSUE THREAD

**Issue by tim-salabim** [edzer/sfr#315]
I am not sure whether this is a feature request, bug report, both or neither. Via [this blog post](http://jsta.github.io/2016/07/14/geopackage-r.html) I learnt today that we can use use **dplyr** semantics to directly query `gpkg` files. While the database query works fine, I wonder how we can coerce data, once `collect`ed into simple features?
```r
library(sf)
library(dplyr)

conn = system.file("gpkg/nc.gpkg", package = "sf")
db = src_sqlite(conn)
tab = tbl(db, "nc.gpkg") %>% filter(AREA > 0.2) %>% collect()

str(tab)
```
gives
```r
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	11 obs. of  16 variables:
 $ fid      : int  37 47 54 57 79 88 94 96 97 98 ...
 $ geom     :List of 11
  ..$ : raw  47 50 00 03 ...
  ..$ : raw  47 50 00 03 ...
  ..$ : raw  47 50 00 03 ...
  ..$ : raw  47 50 00 03 ...
  ..$ : raw  47 50 00 03 ...
  ..$ : raw  47 50 00 03 ...
  ..$ : raw  47 50 00 03 ...
  ..$ : raw  47 50 00 03 ...
  ..$ : raw  47 50 00 03 ...
  ..$ : raw  47 50 00 03 ...
  ..$ : raw  47 50 00 03 ...
 $ AREA     : num  0.219 0.201 0.207 0.203 0.241 0.204 0.24 0.225 0.214 0.24 ...
 $ PERIMETER: num  2.13 1.8 1.85 3.2 2.21 ...
 $ CNTY_    : num  1938 1968 1989 2004 2083 ...
 $ CNTY_ID  : num  1938 1968 1989 2004 2083 ...
 $ NAME     : chr  "Wake" "Randolph" "Johnston" "Beaufort" ...
 $ FIPS     : chr  "37183" "37151" "37101" "37013" ...
 $ FIPSNO   : num  37183 37151 37101 37013 37163 ...
 $ CRESS_ID : int  92 76 51 7 82 31 78 9 71 24 ...
 $ BIR74    : num  14484 4456 3999 2692 3025 ...
 $ SID74    : num  16 7 6 7 4 4 31 8 4 15 ...
 $ NWBIR74  : num  4397 384 1165 1131 1396 ...
 $ BIR79    : num  20857 5711 4780 2909 3447 ...
 $ SID79    : num  31 12 13 4 4 7 26 5 3 17 ...
 $ NWBIR79  : num  6221 483 1349 1163 1524 ...
```
I have tried a few ways to create a valid **sf** object from this (`st_as_sf`, `st_as_sfc(.., EWKB = TRUE)` with various combinations of `unlist`ing, `rbind`ing or simply `c`ing), but have failed so far. Is this even possible? Am I missing something obvious? 

I am also not sure if this is a good approach to use at all, but I can see that, if working properly, it could potentially be quite attractive as an alternative to setting up a proper SQL/postgis database. Even though `st_write`ìng to `gpkg` seems to be much much slower that writing data as to a `shp` file (tested today with a POLYGON layer of ~ 2 Mio. polygons).

I would love to hear people's thoughts on this...

**Comment by edzer** [comment]
Interesting. I tried naively what `st_read_db` [does](https://github.com/edzer/sfr/blob/master/R/db.R#L67):
```r
> st_as_sfc(structure(tab$geom, class = "WKB"))
Error in CPL_read_wkb(x, EWKB = EWKB, endian = as.integer(.Platform$endian ==  : 
  unknown wkbType dim in switch
```
but then noted that the raw vectors should start with `00` or `01` if they were [wkb](https://en.wikipedia.org/wiki/Well-known_text#Well-known_binary). So two things to sort out:

* does GPKG store simple features as WKB blobs in the geometry column?
* if yes, why doesn't RSQLite, dbplyr and dplyr (I'm on pre-0.6.0) read them correctly?
* if no, what is it then?

**Comment by tim-salabim** [comment]
Seems like they should be proper WKB blobs and should start with `00` or `01`

http://www.geopackage.org/spec/#gpb_format

**Comment by edzer** [comment]
No, they're OGC wkb with a custom, variable-length header. Nr 6 is the OGC wkb. Seems like they call this _GeoPackage SQL Geometry Binary Format_ or _GeoPackageBinary_. They add bounding boxes and stuff; it's OGC wkb with a variable length header.

**Comment by edzer** [comment]
For this case, header is 40 bytes, so
```r
> drop_header = function(x,n) x[-(1:n)]
> st_as_sfc(structure(sapply(tab$geom, drop_header, n = 40), class = "WKB"))
Geometry set for 11 features 
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -80.06441 ymin: 33.88199 xmax: -76.49254 ymax: 36.06665
epsg (SRID):    NA
proj4string:    NA
First 5 geometries:
MULTIPOLYGON(((-78.9210739135742 35.57885742187...
MULTIPOLYGON(((-79.7649917602539 35.50593566894...
MULTIPOLYGON(((-78.5387420654297 35.31511688232...
MULTIPOLYGON(((-77.1037673950195 35.55018615722...
MULTIPOLYGON(((-78.11376953125 34.7209854125977...
```
and note that the `SRID` is lost - it's in
```r
> dbGetQuery(con, "select * from 'gpkg_geometry_columns'")
  table_name column_name geometry_type_name srs_id z m
1    nc.gpkg        geom       MULTIPOLYGON   4267 0 0
```

**Comment by tim-salabim** [comment]
Cool! Thanks for the clarification. How do we know the length of the header?

**Comment by edzer** [comment]
It's 8 bytes + envelope; envelope can be 0 (no envelope), 32 (XY: 4 x 8-bytes double), 48 (XYZ or XYM) or 64 bytes (XYZM). the `flags` byte tells you what is the case in positions 1/2/3.

**Comment by edzer** [comment]
We can now do
```r
> tbl(db, "nc.gpkg") %>% filter(AREA > 0.2) %>% collect %>% st_sf %>% print(n=1)
Simple feature collection with 11 features and 15 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -80.06441 ymin: 33.88199 xmax: -76.49254 ymax: 36.06665
epsg (SRID):    NA
proj4string:    NA
First 1 features:
  fid  AREA PERIMETER CNTY_ CNTY_ID NAME  FIPS FIPSNO CRESS_ID BIR74 SID74
1  37 0.219      2.13  1938    1938 Wake 37183  37183       92 14484    16
  NWBIR74 BIR79 SID79 NWBIR79                           geom
1    4397 20857    31    6221 MULTIPOLYGON(((-78.92107391...
```

**Comment by tim-salabim** [comment]
Getting the correct `srs_id` is not that straight forward I assume if it is stored in another table. However, how can I understand the hrade description?

```
GeoPackageBinaryHeader {
  byte[2] magic = 0x4750; 
  byte version;           
  byte flags;             
  int32 srs_id;
  double[] envelope;      
}
```
This indicates that it is part of the header, doesn't it?

**Comment by edzer** [comment]
Yes, and it is being read, but apparently it was written as zero, indicating "missing". I looked in the gdal driver code (I generated this gpkg with gdal, in early sf days), but couldn't figure out what is going on there.

It's somewhat similar to PostGIS (@etiennebr) where EWKB can have SRIDs for each feature geometry, but doesn't always have it. It gets even more tricky when you have custom CRS - the db will create a custom SRID that is not an EPSG value; you need to pull the proj4string from the db. See `sf:::get_postgis_crs` for how `st_read_db` does this.

There is this potential of making `st_read_db` read more than PostGIS; gpkg, spatialite, MySQL being candidates, but it's rather unlikely that I am going to spend much time on it this year.

**Comment by tim-salabim** [comment]
No problem. The current functionality is very useful as it is. Thanks for implementing this so quickly. We have a few projects where this could be potentially very useful. I will report back (here) if/when I make any generalised progress regarding this type of workflow.
From my side, we could close this issue.
