### ISSUE TITLE
st_transform silently ignores proj4string?

### ISSUE THREAD

**Issue by eamcvey** [edzer/sfr#317]
I suspect this is more a lack of understanding on my part than a bug.  But here it is:

I'm trying to get the CRS to match between two sf objects so that I can do joint operations (st_within(), etc.).  I have successfully transformed the epsg to match, but still get the error about CRS mismatch based on the proj4string.  I see the nice explanations in the st_crs() documentation (thank you!) which explain why this error is expected: 

_Two objects of class crs are semantically identical when: (1) they are completely identical, or (2) they have identical proj4string but one of them has a missing epsg ID. As a consequence, equivalent but different proj4strings, e.g. "+proj=longlat +datum=WGS84" and "+datum=WGS84 +proj=longlat" , are considered different._

_If both epsg and proj4string are provided, they are assumed to be consistent. In processing them, the epsg code, if not missing valued, is used and the proj4string is derived from it by a call to GDAL (which in turn will call PROJ.4). Warnings are raised when epsg is not consistent with a proj4string that is already present._

However, in an effort to get them to match, I have tried to apply a second st_transform (after the epsg) to transform to the same proj4string, but it silently doesn't appear to do anything:

`temecula_match_df <- temecula_sf %>% st_transform('+proj=longlat +datum=NAD83 +no_defs')`

`st_crs(temecula_match_df)`
$epsg
[1] 4269

$proj4string
[1] "+proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs"

attr(,"class")
[1] "crs"

I still have the same non-matching proj4string that this sf object started with.  Is this a bug?  If not, what is the right way to get two sf objects to have a valid matching CRS?

**Comment by edzer** [comment]
Yes, this is annoying - did you try to convert both datasets with that target crs?

If you're sure that the crs _are_ identical, just don't test as equal, you can overwrite one of them by simply setting it to the other's, i.e. sth like

x_new <- x %>% st_set_crs(st_crs(y))

and ignore the warning. You can avoid the warning by first setting it to `NA_crs_`.
