### ISSUE TITLE
Inconsistent geometry column names

### ISSUE THREAD

**Issue by mem48** [edzer/sfr#318]
Many of the functions rename the geometry column, switching between geometry, geoms, geom

Simple example:
```
library(sf)
A <- st_read(system.file("shape/nc.shp", package="sf"))
A <- A[,c(1,15)]
A <- st_transform(A, crs = 3857)
names(A) #"AREA"     "geometry"
B <- st_buffer(A, 10)
names(B) #"AREA"     "geometry"
C <- st_union(A,B)
names(C) #"AREA"   "AREA.1" "geoms" 
```

Is there a reason for this? And if not, is it possible to specify what the geometry column is called?

**Comment by edzer** [comment]
`st_read` reads the data from a data source, and that data source tells what the geometry column name is; see [here](https://github.com/edzer/sfr/blob/master/src/gdal_read.cpp#L56-L64): when the data source does not have a name (e.g. a shapefile) it defaults to `geoemetry`, (or `geometry1`, `geometry2`, ... if there are multiple geom columns). 

I modified the `st_union` group of functions to inherit the geometry column name from the first argument.

**Comment by AltfunsMA** [comment]
I have a bunch of `.gpkg` files, some with their geometry column as `geom` others as `geometry`. I was trying to rename the "geom" all to "geometry" but failing miserably.... I am able to reproduce the behaviour as below. In the last iteration, I would expect `nc_geometry.gpkg` to have its column called "geometry" not "geom". Not sure if I'm missing something...?

``` r
library(dplyr)
library(sf)

nc <- st_read(system.file("shape/nc.shp", package="sf"))
#> Reading layer `nc' from data source `C:\Users\mig_2\Documents\R\win-library\4.0\sf\shape\nc.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> geographic CRS: NAD27

attr(nc, "sf_column")
#> [1] "geometry"

# First change sf-column name to "geom" to reproduce issue
nc_geom <- rename(nc, geom = geometry) %>% 
  st_set_geometry("geom")


attr(nc_geom, "sf_column")
#> [1] "geom"

write_sf(nc_geom, "~/nc_geom.gpkg")


nc_read_geom <- st_read("~/nc_geom.gpkg")
#> Reading layer `nc_geom' from data source `C:\Users\mig_2\Documents\nc_geom.gpkg' using driver `GPKG'
#> Simple feature collection with 100 features and 14 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> geographic CRS: NAD27

attr(nc_read_geom, "sf_column")
#> [1] "geom"

nc_geometry <- rename(nc_read_geom, geometry = geom) %>% 
  st_set_geometry("geometry")


attr(nc_geometry, "sf_column")
#> [1] "geometry"

write_sf(nc_geometry, "~/nc_geometry.gpkg")

nc_read_geometry <- st_read("~/nc_geometry.gpkg")
#> Reading layer `nc_geometry' from data source `C:\Users\mig_2\Documents\nc_geometry.gpkg' using driver `GPKG'
#> Simple feature collection with 100 features and 14 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> geographic CRS: NAD27

attr(nc_read_geometry, "sf_column")
#> [1] "geom"
```

**Comment by edzer** [comment]
As far as I can tell, there is no way to specify the name of the geometry column when writing a GPKG file with GDAL/OGR.

**Comment by AltfunsMA** [comment]
I see, so is "geom" the default name given by GDAL/OGR when writing out to GPKG and "geometry" the default name read by `st_read` from a shapefile?

This was a bit of a pain in `dplyr` pipelines involving, e.g. mutate calls with `st_centroid(geometry)`. A workaround I found is `st_centroid(.)` not sure if that's the best way around this?
