### ISSUE TITLE
st_drop_zm no longer exists?

### ISSUE THREAD

**Issue by eamcvey** [edzer/sfr#319]
When converting sf to sp, I got the helpful error message about Z not being supported, with the suggestion to try st_drop_zm first... but that function no longer seems to exist.  It appears that it did because I see the issue in which the addition of the error message was suggested, but R tells me it can't be found, and when I search the Github repo I don't see it there either.

**Comment by edzer** [comment]
Thanks - the function got renamed to `st_zm`; I've updated the error message.
