### ISSUE TITLE
Fall back on lowest common denominator geometry on rbind?

### ISSUE THREAD

**Issue by RoyalTS** [edzer/sfr#322]
I'm trying to `rbind` two `sf` data frames. Here's the first:

    Simple feature collection with 8057 features and 12 fields
    geometry type:  MULTIPOLYGON
    dimension:      XY
    bbox:           xmin: -124.482 ymin: 32.52883 xmax: -114.1312 ymax: 42.00952
    epsg (SRID):    4269
    proj4string:    +proj=longlat +datum=NAD83 +no_defs

And here's the second:
    
    Simple feature collection with 833 features and 12 fields
    geometry type:  POLYGON
    dimension:      XY
    bbox:           xmin: -73.72777 ymin: 40.95094 xmax: -71.78724 ymax: 42.05059
    epsg (SRID):    4269
    proj4string:    +proj=longlat +datum=NAD83 +no_defs

This fails with error message `Error in CPL_get_bbox(obj, 3) : not a matrix`

What actually seems to be at fault here is that the two objects have different geometries. It would be great if the error message told me as much.

It would be even greater if `sf` tried to deal with this automatically by falling back on the lowest common denominator type on `rbind`. I'm assuming that every `POLYGON` is a `MULTIPOLYGON` so couldn't one `st_cast()` every `POLYGON` to `MULTIPOLYGON`, throw a warning about the conversion, but then proceed with the `rbind` instead of erroring?

**Comment by edzer** [comment]
This was a plain mistake (bug) in `sf`. Right now, `rbind`-ing mixed geometry types gives you a mixed geometry object with geometry type `GEOMETRY`. You then need to cast that yourself, by
```r
st_cast(x, "MULTIPOLYGON")
```
I'm with you how great the automatic bind `x` and `multix` into `multix` would be, and would be happy to consider a PR.
