### ISSUE TITLE
grep select with sf

### ISSUE THREAD

**Issue by obrl-soil** [edzer/sfr#326]
So if I want to select values from a subset of data frame columns with a common name-stem, I have been using

    vals <- as.vector(na.omit(unlist(data_frame[ , c(grep('X_', names(data_frame)))])))

(usually applied row-wise) which will grab me something like `c(val1, val2, val3)`. Doing this with an sf object gets me a vector that holds not only the values I want, but all the geometry data as well - one value for each coordinate, like `c(val1, val2, val3, x1, x2, x3, y1, y2, y3)`. IMO this shouldn't happen unless my grep is accidentally picking up the geometry column name, and it isn't in this case. I've been getting around the problem with 

    vals <- as.vector(na.omit(unlist(as.data.frame(sf_object)[ , c(grep('X_', names(sf_object)))])))

Is this a bug, or poor syntax on my part?

**Comment by edzer** [comment]
It is intended, but I'd agree with you that the documentation should make this more explicit.

Another way to make `sf` drop sticky geometries on subsetting is `sf_object[,colname,drop=TRUE]`.

**Comment by obrl-soil** [comment]
Yeah the only discussion I can find about the concept is here, in issues 121 and 183. I can see why its been done now. `drop = TRUE` is certainly easier to read, I'll use that going forward.
