### ISSUE TITLE
Exposing C++ API via headers in compiled package

### ISSUE THREAD

**Issue by JoshOBrien** [edzer/sfr#329]
I'm new to C++, but have recently used it to put together a package that wraps GDAL's `GDALRasterize()`, to greatly speed up rasterization compared to what `raster::rasterize` can do. While inspecting code in `edzer/sfr/src/` for examples of how to interact with GDAL's API, I came across several functions (e.g. `create_options()` and `CPL_write_ogr()`) that I'd like to use or at least play around.

If I understand correctly, I could easily link to compiled versions of those functions in the sf package (just as I'm currently linking to compiled code from `rwinlib/gdal2`) if the appropriate header files were placed in the `edzer/sfr/inst/incl/` directory. Is that something you might consider?

**Comment by edzer** [comment]
This is different from linking to `rwinlib/rgdal2`, as that is only a binary distro of a required external dependency on a given platform; what you have in mind is (cross platform) package-to-package linking on the C++ level. What we do with rgdal and rgeos linkingto sp (@rsbivand) is on the C level, and [WRE](https://cran.r-project.org/doc/manuals/R-exts.html#Linking-to-native-routines-in-other-packages) also mentions this; it's done also with C++ headers (BH), but that involves no dynamic linking. C++ has the issue of name wrangling.

If you'd go this path with a package that you'd wish to publish, it might cause some maintenance challenges: an update of sf involving the C++ code could immediately break, at the binary code level, your package.

**Comment by JoshOBrien** [comment]
Thanks for your detailed response. I know I'm in way over my head here, but hope you'll help me understand whether you're saying that: (1) this isn't really possible from your side; or (2) that it wouldn't be a wise design decision from my side to depend on sf in that way, even if I could.

You're exactly right that I was hoping for cross-platform package to package linking into compiled C++ code. And I understand that that's different from: (1) linking to `rwinlib/rgdal2` (not cross-platform); (2) rgdal and rgeos linking to sp (C, not C++); and (3) linking to BH (a header-only library). Still, Section 3.6 of the "Rcpp Attributes" vignette ([pdf here](http://dirk.eddelbuettel.com/code/rcpp/Rcpp-attributes.pdf)), "Providing a C++ Interface", seems to be saying that one can use the `[[Rcpp::interfaces]]` attribute to automatically generate a header-only interface to C++ functions. (It does the work of constructing and collecting appropriate headers into two files in `inst/include`, including creating inline definitions of exported C++ functions that enable calling them via the `R_GetCCallable` mechanism mentioned in the section of WRE that you linked to.)

Am I wrong in reading that to be saying that exporting a C++ interface from an package is possible? (Whether it would be desirable or worth the effort in the case of *sf* is obviously a totally different matter.)

**Comment by edzer** [comment]
Thanks! I didn't know about that. Brief experiments including `// [[Rcpp::interfaces(r,cpp)]]` in the two source files that have the functions you mentioned above leads to a package that no longer installs, which I can't use now. I might look into this later (and might try to use it for the stars project), if you figure out how it works I'd look forward to a PR.

**Comment by JoshOBrien** [comment]
Will do. I'm so thrilled by the 100-fold speedup in rasterization that I've gotten with the function I just put together that I'm contemplating on working on a larger package that would provide standalone access to all of the non-Python GDAL Utilities. If I find the time to do that, I'll be climbing much farther up this steep C++ learning curve, and may eventually be of assistance here as well.

**Comment by edzer** [comment]
Have been thinking about the C++ access to gdal utils as well, and have some code running for half of them or so; not yet pushed, but the `create_options()` issue came up there too.

Are you aware of [fasterizer](https://github.com/ecohealthalliance/fasterize)?

**Comment by JoshOBrien** [comment]
Nope, I hadn't come across that very-promising looking package. Thanks for the pointer!

**Comment by edzer** [comment]
I took another look at this, tried to expose `create_options` only, and got a bit further. It stopped at the lack of a converter (wrapper) from `std::vector<char *>` (the return value of `create_options`) to `SEXP` (an R object). Understandably, but doing this needs some C++ knowledge deeper than mine. Use `Xptr`?
 tidyverse is full with working examples, though.

**Comment by edzer** [comment]
First export experiments passed [here](https://github.com/edzer/sfr/tree/master/inst/include), but anything has to go through `SEXP` afaict.

**Comment by JoshOBrien** [comment]
Hi Edzer. Have you thought any more about providing Rcpp wrappers for the GDAL utilities? I've got wrappers for several of them, but expect that your approach is probably more elegant. In any case, I'd be interested in working to push this forward if you'd like the help.

**Comment by Robinlovelace** [comment]
This is over my head and I know 0 C++ but I read about this '[vapour](https://github.com/hypertidy/vapour)' package that says something that sounds similar "The goal of vapour is to provide a basic GDAL API package for R." Not sure if that's useful and I'm not well qualified to comment on this as I've very rarely used GDAL (for tile pyramids) other than via R or a GUI such as that provided by QGIS but the article that alerted me to this may have some interesting background information: http://miller-crab-81816.netlify.com/2017/09/01/gdal-in-r/

I asked the author @mdsumner if vapour would go on CRAN but it seems not. In any case they seem to have attempted accessing GDAL functionality at a low level and my have some additional pointers.

**Comment by rsbivand** [comment]
The post has challenges. One is in not explaining that there is no GDAL. Any GDAL installation offers services depending on choices available and/or made at configure time (as I found out wrt the NY8 data set). So for CRAN (and @mdsumner was then on Windows, and contributed now outdated documentation for building rgdal with VS C build trains), the binary Windows and OSX GDAL drivers and capabilities depend on how much we can ask the build train maintainers, lately Jeroen Ooms and Simon Urbanek, to include of driver-level external dependencies. Some drivers, in particular the NetCDF family, were never included as the upstream software had major portability issues at that time. The authority for this statement was Brian Ripley, whose judgement is without exception excellent. He solved most of the initial problems for providing Windows and OSX rgdal and rgeos binaries, indeed on his own CRANextras server before he retired.

Further, the post ignores [gdalUtils](https://cran.r-project.org/package=gdalUtils), which already provides shell-level access to the GDAL utilities. So using GDAL utilities at the shell level is done; because of this, the C++ API is less urgent. Also note that C++ APIs are much more volatile than C APIs, and the ABIs are a higher number circle of dependency hell. 

The real key to progress is being able to write and keep contracts to maintain packages, say for GDAL with some acceptable minimum set of capabilities and drivers, and to update these as upstream software is revised (including bug fixes). 

By the way, is anyone handling [GNM](http://www.gdal.org/gnm_arch.html)? Not an obvious fit for sf or stars?

**Comment by Robinlovelace** [comment]
Fascinating background info Roger, many thanks for that. Read in detail but will take time to absorb. I remember seeing the General Network Model component of GDAL a while back, I think Edzer may have alerted me. I think there would be a good fit with my current main domain of application in the Institute for Transport Studies in Leeds: transport planning/modelling.

I suspect this class system and functions using it at the C level could greatly improve **stplanr** functions such as `overline`. However I wouldn't know where to begin in terms of implementing this functionality ([`ConnectPointsByLines`](http://www.gdal.org/classGNMGenericNetwork.html#adfd4d1c7cb24e7610bfc15f0cbd1b476) looks really useful for creating route networks quickly from disparate data sources) and currently lack the time even if I did know where to begin with a book to write, package in need of updating (almost there with the **sf** [transition](https://github.com/ropensci/stplanr/pull/198)) and usual work commitments.

But well up for helping out when my house is in order.

**Comment by edzer** [comment]
@JoshOBrien I haven't progressed more than [this](https://github.com/r-spatial/stars/blob/master/src/utils.cpp), and I don't give it much love because I don't see the added value over directly using the corresponding gdal utils or using the R `gdalUtils` package. It just reads a file and writes a file and may pass some options -- why would you want to do this with the R binary? I think the added value, at lesat for the _stars_ package, should come from doing something with the data _with R_. But feel free to contribute, it's no real overhead or so (although I try to keep namespaces lean).

@Robinlovelace for the vapour, as Mike writes, he wanted to learn using Rcpp with GDAL, and for that reason he forked (parts of) sf, which is of course a good way to start - you skip a lot of dirty work - so did I with rgdal and rgdal2. If he wants to bring this to CRAN it might make sense to de-duplicate first, in order not having to find and fix identical bugs in two places.

**Comment by Robinlovelace** [comment]
Cheers for the explanation - makes sense and helps understand how **vapour** and **sf** sit (uncomfortably) together. It seems there is functionality in there that could be useful and from what you say that if that is the case it would make sense for that to be part of **sf**. Great to be reading about this largely hidden layer underlying much R-spatial stuff and grateful that much of the 'dirty work' of providing an R interface to some of the most useful functionality has already been done.

**Comment by JoshOBrien** [comment]
@edzer  I hear you, and from a software design perspective can't say anything but "amen" to your arguments. Keeping the R package lean, and letting gdal do gdal makes great sense. (And also, thanks for the pointer to your wrapper for `gdal_rasterize`)

Here though, is an explanation of my very mundane reason for wanting an R binary that wraps gdal functionality. I am working on a project with government folks and other contractors who are firmly in the ArcGIS world. They're generally unfamiliar with R and GDAL, and express some (I think) reflexive distrustful of them; they just plain feel more comfortable with commercially supported software than with open source utilities. (I know, I know. And this is despite the fact that each time Esri releases a new version of ArcGIS, it breaks their current tool.)

I've in the past succeeded in getting them to let me implement a large portion of the analysis in R + `sp` + `rgdal` + `rgeos`. I bundle all those together with my own R package in a customized installer that ships alongside the ArcGIS interface. Over time, stability of the R side of the workflow convinced (some of) my coworkers to let me work on replacing the whole workflow with R GIS operations. I've got everthing working nicely on my own box with R + `sp` + `rgdal` + `rgeos` + `gdalUtils` ... but as you know, `gdalUtils` is really gdalUtils + GDAL (with GDAL in my case available as part of an OSGeo4W installation).

I can't rely on end-users (most of them not software developers) to already have GDAL installed on their Windows machines. I also can't ask that they install it: they won't be willing to, they may not even be given the permission to, and, to be honest, requiring an additional installation of OSGeo4W actually *would* be more of a pain than a solution that just included the necessary binaries in an R package.

For the project I'm working on, this is now actually a moot point.  The prospect of having to rely on GDAL + R (rather than "just" on R) seems to have spooked some folks on the project away from my proposal. But I think this does point to at least one reason for providing R packages that completely wrap binaries from other projects, rather than simply calling out to external installations of them. Heck, speaking from personal experience, I think in my own early days as a Windows R user, I'd have been much less likely to have moved over to R-driven GIS analysis had `rgdal` and `rgeos` not 'just worked', freshly-delivered from the CRAN server, without any need for external GDAL or GEOS binaries.

Sorry for the long comment, but I really do think it's worth at least understanding that for some R on Windows end users, being able to do something like "install.packages('rgdal')" really is significantly better than having to doing something like, "First install an entire external software installation in addition to R, and *then* do install.packages('gdalUtils')".

**Comment by edzer** [comment]
Thanks @JoshOBrien  -- that surely helps!

**Comment by edzer** [comment]
@JoshOBrien so the remaining C++ gdal_utils now have an interface in stars; Note that this is all dependent on GDAL >= 2.1 (parts of the CRAN build train are still on 2.0.x).

This needs testing by someone familiar with gdal utils (not me): can you compile things from source?

**Comment by JoshOBrien** [comment]
@edzer Thanks! I just successfully compiled the latest version and ran a few quick tests of `st_gdal_utils("rasterize", ...)`. Very happy to report that they all worked just as I would have hoped, including those tests in which I passed along a few options. 

The following, for instance, correctly used the attribute field `"ID_2"` of the polygon layer to supply burn in values for the raster.

```r
st_gdal_utils("rasterize", "SPDF.shp", "SPDF.tif", options=c("-a", "ID_2"))

## The R call above is equivalent to the following command-line call
## > gdal_rasterize SPDF.shp -a ID_2
``` 

When I have more time (unfortunately probably not until mid-December) I'll revisit this to contribute some reproducible examples and (if they'd be useful) tests.  In the meantime, if there are particular things you'd like me to test, just drop me a line, and I'll give them a go. 

(I also have some already-written code that, with a few tweaks, would provide an interface layer of R functions that take care of processing options and that look much more like the R functions in the **gdalUtils** package. I imagine you wouldn't want to clutter the **stars** package with those, but they could easily be bundled into a separate package that depends on **stars**.)

**Comment by edzer** [comment]
I like the idea of that package; ideally it would have a test suite that shows that output of (wrapped) `st_gdal_utils` calls are binary (checksum) identical to those obtained from `gdalUtils`.

**Comment by JoshOBrien** [comment]
Good suggestion. `tools::md5sum()` would make that easy.

I'll have to get more up to speed on a few aspects of the development process, like setting up test suites, plus Travis and AppVeyor CI. But before any of that, I'll just get the basic R package together. Will let you know when I post it to GitHub.

**Comment by JoshOBrien** [comment]
@edzer OK, I just now finally pushed to GitHub a first version of a package that provides a straightforward interface to the GDAL utilities wrapped by `sf::gdal_utils()`. The URL is here: https://github.com/JoshOBrien/gdalUtilities . 

I've included a set of tests of checksum identity between results from my package (**gdalUtilities**) and Jonathan Greenberg's **gdalUtils** (which uses a system install of GDAL). The results are in many cases identical and in all cases substantially identical. The differences that do exist (which are mentioned in the test files) likely derive from differences in versions of the many supporting libraries. i.e., the binaries linked to by the GDAL 2.2.3 at [https://github.com/rwinlib/gdal2](rwinlib/gdal2) (and used by **sf** and thus my **gdalUtilities** package) are in some cases likely of different versions than the libraries linked to by the OSGEO4W-provided GDAL 2.2.3 installed on my system (and used by  **gdalUtils**).

Please feel free to have a look at the package.  Any suggestions for improvement are more than welcome!
