### ISSUE TITLE
a tolerance for the geometric predicates (9IM)

### ISSUE THREAD

**Issue by faridcher** [edzer/sfr#330]
A tolerance to override the default `all.equal` (`sqrt(.Machine$double.eps)`) for coordinates comparison in spatial predicates should be defined.

**Comment by edzer** [comment]
Did you look into `? st_set_precision`?

**Comment by faridcher** [comment]
I can only see the `precision` attribute is being manipulated in various functions (st_read, ...). I don't see its usage in the spatial predicate. Although it is good to see this is part of the design.

**Comment by edzer** [comment]
Did you read in the docs when it is used?

**Comment by faridcher** [comment]
first the link is not working in st_as_binary doc page:

http://tsusiatsoftware.net/jts/javadoc/com/vividsolutions/jts/geom/PrecisionModel.html

second running this example tells me that the coordinates are not affected:
```r
x <- st_sfc(st_point(c(pi, pi)))
dput(x)
st_precision(x) <- 0.01
dput(x)
```

Could you clarify how the precision attribute is used in predicates? if at all!

**Comment by rsbivand** [comment]
See:

```
library(rgeos)
example(setScale)
```

and section 5.2.2 in Bivand, Pebesma & Gómez-Rubio (2013), with code [here](http://www.asdar-book.org/bundles2ed/cm2_bundle.zip).

**Comment by edzer** [comment]
I tried to improve the docs; pls check that things are clear, now.

**Comment by faridcher** [comment]
Much better now. So, `st_as_binary` is called internally in `st_write_db` if the `binary` is set to TRUE. My realization is that the user MUST call `st_as_binary` before using the GEOS operators or writing objects through GDAL. If this is the case my suggestions would be :

1. make it internal (call to `st_as_binary`) in both writing and calling to GEOS operators once the user set the precision attribute
2. document the st_set_precision in the GEOS operations doc page and the `st_write` doc page.

In addition there is a small typo in the improved doc : precion > precision

thanks

**Comment by edzer** [comment]
The docs say "`st_as_binary` is called on sfc objects on its way to the GDAL or GEOS libraries", meaning this is internal, and always. I tried to clarify the docs further.

**Comment by faridcher** [comment]
The new doc rocks. Now I understand the underlying mechanism. I ran a bunch of other tests:

```r
# the only change is in the decimal points 4 and 5
(x = st_sfc(st_point(c(1.23456, 1.23456))))
(y = st_sfc(st_point(c(1.23489, 1.23489))))
st_intersects(x,y,sparse = F) #FALSE

(x = st_sfc(st_point(c(1.23456, 1.23456)), precision = 1000))
(y = st_sfc(st_point(c(1.23489, 1.23489)), precision = 1000))
st_intersects(x,y,sparse = F) #TRUE

#doesn't work with sfg (attr is set at sfc level just like crs)
p1<- st_point(c(1.23456, 1.23456)) %>% st_set_precision(1000) #error
p2<- st_point(c(1.23489, 1.23489)) %>% st_set_precision(1000) #error

#if not using the precision param in the st_sfc and st_set_precision after that, works fine
(x = st_sfc(st_point(c(1.23456, 1.23456))) %>%  st_set_precision(1000)) 
(y = st_sfc(st_point(c(1.23489, 1.23489))) %>% st_set_precision(1000))
st_intersects(x,y,sparse = F)
```

thanks
