### ISSUE TITLE
ungroup removes sf class

### ISSUE THREAD

**Issue by Yeedle** [edzer/sfr#333]
Not sure if this is a bug or not, but certainly unexpected behavior or I'm missing something.

```r
library(sf)
#> Linking to GEOS 3.5.0, GDAL 2.1.0, proj.4 4.9.2
library(dplyr)
ibrary(stringr)

nc <-  st_read(system.file("shape/nc.shp", package="sf"),quiet = T)

nc %>% 
  group_by(group = str_detect(NAME, "^H")) %>% 
  ungroup() %>%
  class()
#> [1] "tbl_df"     "tbl"        "data.frame"
```

To transform it back into a `sf` object, I have to pipe it into `st_sf` function to reconvert it to `sf`. Is this behavior intentional? If so, why?

**Comment by edzer** [comment]
Thanks, should be fixed now.

**Comment by Yeedle** [comment]
It is! Thanks! Awesome package and awesome author/maintainer!

**Comment by thiesben** [comment]
Hey, 
I've stumbled upon this issue today. I'm using s 0.9-5 and I observed:
```
library(rnaturalearth)
library(rnaturalearthdata)
library(dplyr)
library(sf)

africa <- ne_countries(continent = "africa", returnclass = "sf")
africa %>% class
[1] "sf"         "data.frame"
africa %>% ungroup %>% class
[1] "sf"         "data.frame"
africa %>% rowwise %>% class
[1] "rowwise_df" "tbl_df"     "tbl"        "data.frame"
africa %>% rowwise %>% ungroup %>% class
[1] "tbl_df"     "tbl"        "data.frame"
africa %>% rowwise %>% ungroup %>% st_as_sf() %>% class
[1] "sf"         "tbl_df"     "tbl"        "data.frame"
```
So, apparently the object loses its sf upon rowwise -> ungroup!

**Comment by edzer** [comment]
Thanks, should work now - please try out!

**Comment by thiesben** [comment]
Wow - thanks for the quick reply! Unfortunately, I still obtain
```
> africa %>% rowwise() %>% ungroup() %>% class
[1] "tbl_df"     "tbl"        "data.frame"
``` 

with version 0.9-6 loaded in the session.

**Comment by edzer** [comment]
The correction was made to the version on github, you reinstalled the CRAN version. This will be in 0.9-7 on CRAN.

**Comment by thiesben** [comment]
Of course - just checked with the version here on GitHub and it works flawlessly. Thanks for the quick fix!
