### ISSUE TITLE
st_layers error: "index out of bounds"

### ISSUE THREAD

**Issue by nilescbn** [edzer/sfr#334]
I've been getting the following error message when using st_layers() on an ESRI file geodatabase:

*Error in CPL_get_layers(dsn, options, do_count) : index out of bounds*

I'm perplexed because I successfully used the function on the same geodatabase just a couple days ago. And rgdal's ogrListLayers() prints the layers in the .gdb just fine. And st_layers() reads the layers in a different .gdb in a nearby file directory. 

I'm a pretty novice user, of if the issue is obvious my apologies. I thought it worth noting given that rgdal's function does work. If relevant, I'm using Windows 7, R 3.4.0, RStudio v1.0.143 and v0.4-2 of sf. I initially suspected that the recent package update could be the reason for the error, but rolling back to v0.4-1 did not solve the problem.  

Thank you all for your time and work on this package. I'm enjoying learning and working with it.

**Comment by edzer** [comment]
Did you reinstall, or else try reinstalling, `sf`? Any chance you could make gdb available that gives you this problem, possibly by direct mail?

**Comment by nilescbn** [comment]
Yes, I will zip and e-mail it. Thank you. 

Also, I did try reinstalling sf because of another issue I was having with geom_sf. That issue was resolved by the reinstall but the st_layer() error is still there.

**Comment by edzer** [comment]
Thanks for sending me off-line. I also can't open the file; also `gdalinfo filename.gdb` only gives an error: "not recognized as a supported file format", so that's consistent with what `sf` does.

Did you previously possibly use a GDAL install with ESRI's binary driver (i.e., the third-party driver mentioned [here](http://www.gdal.org/drv_filegdb.html)?)

gdb is a proprietary format, so there are valid reasons for open source software not being able to read it. You might consider switching to using an open format, or mixing ESRI proprietary drivers with GDAL by yourself.

In any case I see it as an ESRI/GDAL issue, not solvable by `sf`.

**Comment by nilescbn** [comment]
Okay, thank you for taking the time. I'll look into the drivers issue. I
haven't made changes recently, and it is odd though that I can use
st_layers on other gdbs. And I've always been able to read from
geodatabases using sf. They just don't let you write back with anything but
shapefiles. But yes, I won't bug you with this issue unless the st_layers
error becomes more pervasive or I get some new insight into what's going
on. Again, I appreciate it.

On switching to open source, I hear you and am using your package when I
can. I can't say the same for others within my agency. ESRI is here to stay
for the foreseeable future.

The good news is that ESRI has their R Bridge now and it is much easier to
work with their files in R. I asked and they said they'll be building in
more support for your package too:
https://github.com/R-ArcGIS/r-bridge/issues/8. So that will be great.

**Comment by edzer** [comment]
OK, thanks for opening that issue, and please report back here if you found a solution.

**Comment by scw** [comment]
Note that there is a clean room open source [FileGDB driver](http://www.gdal.org/drv_openfilegdb.html), though it only has read support. Overall, Geopackage makes good sense for interop, and the package mentioned should make this easier, especially once we have `sf` support directly. Let me know if there's anything you could use from the Esri side in testing for sf.

**Comment by aazaff** [comment]
@nilescbn Were you able to fix this problem by adjusting the drivers as suggested? I get the same error, even though I am able to use `st_read( )` to load in the first layer successfully.

**Comment by nilescbn** [comment]
No, @aazaff, I never did investigate the drivers issue. The `st_layers()` function works on some file geodatabases but not others.  When it doesn't work, I switch to the `rgdal::ogrListLayers()` function.  

I just rechecked the .gdb I first had this issue with. I still get the same error. And like you, `st_read()` works. 

On scw's suggestion, I've not had much luck with the geopackage format. 





On scw's comment, I have not had luck with the Geopackage format. The `sf`

**Comment by nilescbn** [comment]
@aazaff, what "types" does your geodatabase hold? The one I was looking at has several File Geodatabase Feature Class types and one File Geodatabase Table. I had a hunch that the table was the issue. After deleting it, `st_layers()` now works. @edzer, perhaps that's the issue?

**Comment by edzer** [comment]
If you have a file on which `st_layers` does not work, but `ogrListLayers` does, I'd be interested to obtain a copy - this should be a bug in `sf`.

**Comment by nilescbn** [comment]
@edzer, it's the same one I sent you on May 10. I can resend.

**Comment by edzer** [comment]
Please do.

**Comment by aazaff** [comment]
I can confirm that `rgdal::ogrListLayers( )` works with my gdb, but `st_layers( )` does not. I do suspect this may be partially driver related as neither works on OSX, but one works and the other does not on Windows.

**Comment by edzer** [comment]
This commit should fix it, works for the file you sent me; layers without geometry have now geometry_type `NA`.

**Comment by edzer** [comment]
You'll need https://github.com/r-spatial/sf/commit/c9e64cc0a4fb2f9ed99ebfb9a141c6064d4187e1 for the fix (or the latest github version).

**Comment by nilescbn** [comment]
Great, I just tested it myself and it worked as you say. Thanks again.

**Comment by edzer** [comment]
Cool, thanks for the feedback!
