### ISSUE TITLE
ggmap does not work with plot_sf/geom_sf

### ISSUE THREAD

**Issue by Yeedle** [edzer/sfr#336]
I'm getting an error when attempting to combine a ggmap object with an sf object in a plot
``` r
library(sf)
library(ggmap)

nc = st_read(system.file("shape/nc.shp", package="sf"))

nc_map = get_map(location = unname(st_bbox(nc)))
ggmap(nc_map)
```
![](http://i.imgur.com/1ZpYKVc.png)

``` r
ggplot(nc) + geom_sf()
```
![](http://i.imgur.com/hSLipTc.png)

So far so good. But when I try to combine them with `geom_sf`:
``` r

ggmap(nc_map) + geom_sf(data = nc)
#> Error in FUN(X[[i]], ...): object 'lon' not found
```
And similarly with `plot_sf`:
``` r

plot_sf(nc, bgMap = nc_map)
#> Warning in plot_sf(nc, bgMap = nc_map): crs of plotting object differs from
#> that of bgMap, which is assumed to be st_crs(3857)
```
(It should be noted that the same error occurs even when the zoom level in `get_map` is set so that all of North Carolina is included in the `ggmap` object)

**Comment by edzer** [comment]
The warning could have been a hint:
```r
plot(st_transform(nc, 3857)[1], col = 0, bgMap = nc_map)
```
![x](https://cloud.githubusercontent.com/assets/520851/25966166/82606e0a-368a-11e7-84f5-e7ae8537a23e.png)

As you see, the background map is pretty much off; `ggmap` gave you a warning that it is not so good at retrieving a google map from a bounding box.

The issue of `ggmap` not working with `geom_sf` has nothing to do with `sf`, as far as I can see.

**Comment by Yeedle** [comment]
So the issue is that `sf` object has to be converted with `st_transform` first before it can be combined with `ggmap`?

**Comment by Yeedle** [comment]
Oh, I see now. I'm sorry for misreading. I think this issue can be closed, I'll try to take it up with ggplot/ggmap.

**Comment by mikoontz** [comment]
For posterity, I'm finding some success when I get the `#> Error in FUN(X[[i]], ...): object 'lon' not found` error to use the `inherits.aes = FALSE` argument in the `geom_sf()` function call:

```
ggmap(nc_map) + 
geom_sf(data = nc, inherits.aes = FALSE)
```

Oddly, I sometimes get a `Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found` when I do this, but I rerun the code and then it works. I haven't looked deeper into this...

I think the original error may be related to the `lon` and `lat` columns created in the `fourCorners` data.frame within the `ggmap()` function as the ggplot `p` is being created. That is, when you get a basemap with `ggmap()`, it returns a ggplot `p` that uses an `aes(x = lon, y = lat)` aesthetic. The `sf` objects that you add on top using the `geom_sf()` function tries to inherit the x and y mapping from that original layer, but it really needs to use the $geometry column.

**Comment by enjoyjubilee** [comment]
> Oh, I see now. I'm sorry for misreading. I think this issue can be closed, I'll try to take it up with ggplot/ggmap.

Hi yeedle, 

I have the same issue as you did and I've read the conversation between you and edzer. However, I didn't get the meaning of " take it up with ggplot/ggmap". Could you please show the codes you ran when you solved the problem? Thanks!

Student in anxious process of a capstones project

**Comment by edzer** [comment]
https://github.com/dkahle/ggmap - note that ggmap now requires an API key to use the google API. An alternative would be not using google; I've seen good results from people using package ggspatial. Let us know what you end up doing.

**Comment by aourednik** [comment]
@edzer The need for API key for `ggmap::get_map()` seems to be unrelated to this issue. I have the same issue with `ggmap::getstamenmap()` that requires no key. 

But, good news, the workaround of @mikoontz still works ! Just add `inherit.aes = FALSE` in the argument of `geom_sf()`.
On the ggmap side, @dkahle, would you have time to fix this? Making the workaround dispensible would offer smooth integration between the two great packages sf and ggmap :-) It takes users time to find this workaround and some give up...

Also, why not remove the obligation to _name_ the bounding box vector in `ggmap::getmap()` and `ggmap::getstamenmap()`? 
ggmap requires ´c("left", "bottom", "right", "top")´, while `st_bbox()` names its vector `c("xmin" , "ymin", "xmax", "ymax")`. This uselesly generates an incomptability that can only be circumvened by another workaround: `st_bbox(mespoints) %>% setNames(c("left", "bottom", "right", "top"))  %>% get_stamenmap(...)`

Here a working example :

```r
mespoints <- st_read('{ "type": "FeatureCollection", "features": [
    { "type": "Feature", "geometry": {
        "coordinates": [9.007992484256647,46.0299246522398],
        "type": "Point"
    }},
    { "type": "Feature", "geometry": {
        "coordinates": [8.9478934338552,45.977147786636834],
        "type": "Point"
    }},
    {"type": "Feature", "geometry": {
        "coordinates": [8.8329890317913,46.04030106008443],
        "type": "Point"
    }},
    {"type": "Feature", "geometry": {
        "coordinates": [8.950073186262301,45.913272474209464],
        "type": "Point"
    }}
]}')

library(ggmap)
fondsCarte <- st_bbox(mespoints) %>% setNames(c("left", "bottom", "right", "top")) %>% get_stamenmap(maptype = "terrain",zoom=13)
ggmap(fondsCarte) + geom_sf(data=mespoints, inherit.aes = FALSE)
```
