### ISSUE TITLE
st_read of sqlite causes RStudio to crash

### ISSUE THREAD

**Issue by sebdalgarno** [edzer/sfr#337]
I have a spatialite file called 'section.sqlite' stored in 'input' folder within my working directory.

Doing `section <- sf::st_read(dsn = 'input/section.sqlite')` causes RStudio to crash. This was working before installing sf version 0.4-2.

I have saved the same file as .shp and .geojson, and these can both be read, using:
```
section <- sf::st_read(dsn = 'input/section.shp')
section <- sf::st_read(dsn = 'input/section.geojson')
```

I have tried other .sqlite files with the same results.

I am not sure whether this is specific to my system, or whether others have run into the same issue.

**Comment by edzer** [comment]
Can you successfully run `gdalinfo` on the sqlite file?

If yes, please provide me with a file that gives you the problem, and give the output of your `sessionInfo()`.

**Comment by sebdalgarno** [comment]
My apologies Edzer...my colleague was able to open the file without problems using same version of sf, R, RStudio, and operating system. This problem is unique to my machine I think. I'll close the issue.
