### ISSUE TITLE
st_intersection changes geometry type to 'GEOMETRY'

### ISSUE THREAD

**Issue by ibarraespinosa** [edzer/sfr#338]
Dear community,

I've been testing with sf in order to migrate my package. In the code it is shown that there are two sf objects: **ml** (MULTILINESTRING) and **g** (POLYGON). After intersect them with with _st_intersection_, the resulting object, **teste**, has the geometry type GEOMETRY, hence, _st_length_  doesnt work. I tried to change the geometry type with _st_geometry_ but **ml** has different number of rows with  **teste** 

Many thanks

```
#ML
l1 = st_linestring(matrix(runif(6)-0.5,,2))
l2 = st_linestring(matrix(runif(6)-0.5,,2))
l3 = st_linestring(matrix(runif(6)-0.5,,2))
s = st_sf(a=2:4, b=st_sfc(l1,l2,l3))
ll = "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
st_crs(s) = ll
l4 = st_linestring(matrix(runif(6),,2))
# plot multilinestrings:
ml1 = st_multilinestring(list(l1, l2))
ml2 = st_multilinestring(list(l3, l4))
ml = st_sf(a = 2:3, b = st_sfc(ml1, ml2), crs = "+init=epsg:4326")
ml$lkm <- st_length(ml)

# grid
sfobj <- ml
height <- 0.1
width <- 0.1
bb <- sf::st_bbox(sfobj)
cs <- c(width, height)  
cc <- bb[1:2] + (cs/2) ## cell offset

g <- st_make_grid(x = ml, cellsize = 0.1, offset = cc,  
                  crs = "+init=epsg:4326", what = "polygons")
gg <- st_sf(id = 1:length(g), g)
head(ml) #geometry type:  MULTILINESTRING
head(gg) #geometry type:  POLYGON

# Intersetion
teste <- st_intersection(ml, gg)
teste$lkm <- st_length(teste) #erro

head(teste) #geometry type:  GEOMETRY

```

**Comment by edzer** [comment]
Hi Sergio, the last figure in [this section](https://cran.r-project.org/web/packages/sf/vignettes/sf1.html#geometrycollection) gives an example what may result from intersections.

A way out is to select only those features with linear geometry, e.g.:
```r
st_length(st_cast(teste[st_dimension(teste) == 1,]))
```

**Comment by ibarraespinosa** [comment]
I see. Therefore, the intersection can return a GEOMETRY collection with different types of spatial features? Many thanks! :1st_place_medal:

**Comment by edzer** [comment]
Yes.
