### ISSUE TITLE
Placeholder: Solaris issue

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#341]
From [Solaris](https://www.r-project.org/nosvn/R.check/r-patched-solaris-sparc/sf-00check.html) for released sf 0.4-3:

Running the tests in ‘tests/read.R’ failed.
...

```
Error in CPL_read_wkb(x, EWKB, spatialite, endian = as.integer(.Platform$endian == :
    reading non-native endian spatialite geometries not supported
  Calls: st_as_sfc ... st_as_sfc -> st_as_sfc.WKB -> CPL_read_wkb -> .Call
  Execution halted
```
Could this return a NULL and throw a warning?

**Comment by edzer** [comment]
I don't think that is worth doing, as I don't expect anyone in real life to run into this; I will instead try to make the test conditional to little-endian platforms, where it passes.
