### ISSUE TITLE
Geometry is dropped by dplyr verbs when `sf` not attached

### ISSUE THREAD

**Issue by adamdsmith** [edzer/sfr#343]
Geometry only appears to be sticky when `sf` is attached, which complicates things when using `dplyr` verbs on `sf` objects within a package/function and `sf` isn't attached explicitly via `Depends`.  

I'm not sure I explained that well, but here's an example:

``` r
## Doesn't work without attaching `sf` package
library(dplyr)
nc <- sf::st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
nc %>% mutate(area_km2 = AREA * 10000) %>% class()
#> [1] "data.frame"

## Calling exported `mutate.sf` from `sf` doesn't solve the problem
nc %>% sf::mutate.sf(area_km2 = AREA * 10000) %>% class()
#> Error in NextMethod(): 'NextMethod' called from an anonymous function

## Appears to work only with `sf` attached
library(sf)
#> Linking to GEOS 3.5.0, GDAL 2.1.1, proj.4 4.9.3
nc %>% mutate(area_km2 = AREA * 10000) %>% class()
#> [1] "sf"         "data.frame"

#> Session info -------------------------------------------------------------- 
#>  setting  value                       
#> version  R version 3.3.2 (2016-10-31)
#> Packages ------------------------------------------------------------------
#>  package    * version    date       source                           
#>  dplyr      * 0.5.0.9005 2017-05-16 Github (tidyverse/dplyr@a99a969) 
#>  sf         * 0.5-0      2017-05-16 Github (edzer/sfr@03ea441)       
```

**Comment by edzer** [comment]
I'm afraid this is how R works: `sf` objects are data.frames, so only loading `dplyr` will only give you methods that act on them as if they were data.frames.

But I agree that this is worth documenting, probably in a vignette on using dplyr on spatial data. #324

**Comment by edzer** [comment]
Since I don't see a way in which activity on the side of `sf` can improve this, I'm closing here. Please feel free to reopen with suggestions how work on `sf` could improve this issue.
