### ISSUE TITLE
as_Spatial - ID mismatch?

### ISSUE THREAD

**Issue by SFrav** [edzer/sfr#345]
When converting an sf object to a SPDF I had to go through the following process to be able to perform further operations:
tmp <-as(nc, 'Spatial')
tmpid <- sapply(slot(tmp, "polygons") 
function(x) slot(x, "ID"))  
row.names(tmp) <- tmpid

Is this something that can be addressed in the as_Spatial function?

**Comment by edzer** [comment]
This commit sets row.names of the data slot and IDs of polygons or lines both to row.names of the `sf` object - does that solve your problem?

**Comment by SFrav** [comment]
That will work nicely.
