### ISSUE TITLE
st_sf from st_sfc has changed?

### ISSUE THREAD

**Issue by mpadge** [edzer/sfr#348]
edzer, this used to work up to 0.4.1, but now fails on both 0.4.3 and 0.5.0
```
st_point(1:2) %>% st_sfc() %>% st_sf()
# Error in st_sf(.) : no simple features geometry column present
```
The first conversion to `st_sfc()` works as expected, but `st_sf()` on a geometry set fails. Is this an intentional change to functionality?

**Comment by edzer** [comment]
Thanks, Mark!
