### ISSUE TITLE
replacement function for sf and sfc subsetting function

### ISSUE THREAD

**Issue by faridcher** [edzer/sfr#352]
A few enhancement proposals:
right now sf supports `[.sf` .

`x[i = sfg|sfc|sf, j, ..., drop = FALSE, op = st_intersects]`

the sfg could also be supported for i (right now only sfc and sf are supported)

a replacement function i.e. `[.sf<-` is very useful.

in addition, sfc subsetting `[.sfc` (+replacement `[.sfc`) by geometry is yet another useful addition:

`sfc[i = sfg|sfc|sf, j, ..., drop = FALSE, op = st_intersects]`

finally, when the `drop=T`, the result should be vector if one column is selected. right now it returns a data.frame.

thanks

**Comment by edzer** [comment]
Thanks; please test this. 

The replacement `[.sf<-` should already work through the `[.data.frame<-` method, which doesn't drop the class or other attributes.

**Comment by faridcher** [comment]
subsetting by sfg works. however, since crs (and precision is not defined at sfg level, this may rise problem in future.

the code from `st_sf` example:
```r
g = st_sfc(st_point(1:2))
st_sf(a=3,g)
st_sf(g, a=3)
st_sf(a=3, st_sfc(st_point(1:2))) # better to name it!
g = st_sfc(st_point(1:2), st_point(3:4))
s = st_sf(a=3:4, g)
s[1,]
class(s[1,])
s[,1]
class(s[,1])
s[,2]
class(s[,2])
g1 = st_sf(a=2:3, g)
g2 = st_sf(a=2:3, g)
sfg_pol <- st_polygon(list(cbind(c(0,3,3,0,0),c(0,0,3,3,0))))
sfc_pol = st_sfc(sfg_pol)
h = st_sf(r = 5, pol)
g[h,]
h[g,]
```
some testing:
```r
#one column selection works
g1[,'a',drop=T]

#`[.sf by sfg|sfc|sf`
g1[sfg_pol,]
g1[sfc_pol,]
g1[h,]

#[.sfc by sf|sfc|sfg works
g[sfc_pol]
g[sfg_pol]
g[h]

#`[.sfc<-` not working
g[sfc_pol] <- st_geometry(h)

#`[.sf<-` doesn't work
g1[pol,] <- g2[2,]
```

replacement functions don't work.

**Comment by edzer** [comment]
`sfg` objects not having a crs or precision is by design. Replacing geometry is done by `st_geometry<-` or `st_set_geometry`. Replacement works for (non-geometry) vectors, as in
```r
g1[1:2, "a"] = 4:5
```
