### ISSUE TITLE
large MULTIPOLYGONZ  example data

### ISSUE THREAD

**Issue by mdsumner** [edzer/sfr#355]
The multipatch  zip (251 MB) includes an ESRI Geodatabase (.gdb) form
http://www1.nyc.gov/site/doitt/initiatives/3d-building.page

```R
library(sf)
d <- read_sf("DA_WISE_Multipatch/DA10_3D_Buildings_Multipatch.gdb")
```

A good reference data set for testing I think. I haven't tried the DGN or CityGML versions yet. (They are larger downloads). I've never seen such a good data set in this MULTIPOLYGONZ form.

**Comment by edzer** [comment]
The other two won't load; the gml returns with a message that it doesn't contain simple features (`ogrinfo` also doesn't list layers).

What kind of tests do you have in mind?
