### ISSUE TITLE
Equivalent of minDimension in sp

### ISSUE THREAD

**Issue by Robinlovelace** [edzer/sfr#361]
Reproducible example in sp:

```r
# l1_sp = as(l1, "Spatial") # fails

s1 = rbind(c(0,3), c(0,4), c(1,5), c(2,5))
s2 = rbind(c(0,3),c(0,4))
s3 = rbind(c(0,4),c(0,5))

library(sp)
l1 <- SpatialLines(LinesList = list(Lines(list(Line(s1)), ID = "1")))
l2 <- SpatialLines(LinesList = list(Lines(list(Line(s2)), ID = "2")))
l3 <- SpatialLines(LinesList = list(Lines(list(Line(s3)), ID = "3")))

l = rbind(l1, l2, l3)
plot(l, lwd = (1:3)^2)
```

![unnamed-chunk-1-3](https://cloud.githubusercontent.com/assets/1825120/26378141/1f419198-400b-11e7-84a7-2c82201ca069.png)

```r
# they both touch 1 in at least a point
over(l[2,], l[1,])
```

```
## 2 
## 1
```

```r
over(l[3,], l1[1,])
```

```
## 3 
## 1
```

```r
# but only the 2nd has an overlapping line
over(l[2,], l[1,], minDimension = 1)
```

```
## 2 
## 1
```

```r
over(l[3,], l1[1,], minDimension = 1)
```

```
## [1] NA
```

**Comment by Robinlovelace** [comment]
OK I think I've figured it out by looking at the output of `st_relate` - I guess the question then shifts to how to specify the dimension without knowing the [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM) pattern?

Solution to the previous issue:


```r
l = as(object = l, Class = "sf")
st_relate(l[2,], l[1,])
```

```
##      [,1]       
## [1,] "1FF00F102"
```

```r
st_relate(l[3,], l[1,])
```

```
##      [,1]       
## [1,] "FF10F0102"
```

```r
st_relate(l[2,], l[1,], pattern = "1FF00F102")
```

```
## [[1]]
## [1] 1
```

```r
st_relate(l[3,], l[1,], pattern = "1FF00F102")
```

```
## [[1]]
## integer(0)
```

**Comment by Robinlovelace** [comment]
OK updated the name of the issue according to my discoveries (shows the benefits of clear reproducible questions!) which basically solves my question.

The question of how to specify an equivalent of `minDimension` is relatively minor, but is important for usability I think. As a starter for 10, how would this be:

```r
minDimension = "1"
if(minDimension == "0") {
  "FF10F0102"
} else if(minDimension == "1") {
  "1FF00F102"
} else if(minDimension == "2") {
  "something_else"
}
```

**Comment by edzer** [comment]
`sp::over`, and the functions it calls in `rgeos`, only use position 1, 2, 4 and 5 of the relate string, meaning intersection of inner and boundaries of x and y.

**Comment by Robinlovelace** [comment]
Great that `st_relate()` is more powerful in this regard. However, for simply finding intersecting lines, it seems a little like using a machine gun to kill a fly. I think it would be useful to have `minDimension` or something similar for common types of intersection so that people don't have to memorise DE-9IM patterns.

**Comment by Robinlovelace** [comment]
For reference, I've just come a good guide here: http://docs.geotools.org/stable/userguide/library/jts/dim9.html

Are there any other go-to resources you would recommend reading-up on? Could reference them in vignettes/help for `st_relate()` is my thinking.

**Comment by edzer** [comment]
I disagree that having a `minDimension` is useful. It is not well understood nor well documented. I had to look into the source code; you could have done that as well, but did you do it? In contrast, `st_relate` is well understood; as you see, you can find it explained in many places.

**Comment by Robinlovelace** [comment]
The source code of geos you mean? Taking a look here https://trac.osgeo.org/geos/browser/trunk but cannot find the source code for `st_relate`.

**Comment by edzer** [comment]
OK to close this issue?

**Comment by Robinlovelace** [comment]
Sure - I think it's a question of documentation rather than functionality. Expect some PRs on that soon which I'll be happy to modify/discard based on your input.

I can see there is a tension between user friendliness and 'dumbing down' / 'feature creep' that good docs can help overcome (not saying minDimension was very user friendly btw!).

If you could point me to the 'source code' you mention I'd still be very grateful and will take a look with interest.

**Comment by edzer** [comment]
The source code I referred to is [here](https://r-forge.r-project.org/scm/viewvc.php/pkg/R/over.R?view=markup&revision=500&root=rgeos).

As you can see, maintenance of `sf` is already quite a burden, as is ironing out bugs; download numbers have doubled last month. I'm inclined to keep the API of `sf` minimal, and not add bells and whistles that don't contain new or essential functionality.

**Comment by Robinlovelace** [comment]
Thanks, agreed.

Ah I thought you meant the source code of GEOS is what I should look at.

Makes sense - bells and whistles can be added by the numerous packages that will no doubt build on `sf`, e.g. our own neglected **stplanr** (trying to find time to work on that).
