### ISSUE TITLE
as(sfg_point, "Spatial") does not work

### ISSUE THREAD

**Issue by Robinlovelace** [edzer/sfr#362]
Reproducible example:

```r
as(st_point(c(0, 1)), "Spatial")
```
```
Error in as(st_point(c(0, 1)), "Spatial") : 
  no method or default for coercing “XY” to “Spatial”
```

**Comment by Robinlovelace** [comment]
OK now see that this works:

```r
sfc_obj = st_sfc(st_point(c(0, 1)))
as(sfc_obj, "Spatial")
```

Imagine there's a reason, just not sure what it is.

**Comment by edzer** [comment]
Yes, this is by design.

**Comment by Robinlovelace** [comment]
Could be useful for this to be documented and I'm up for helping with that as per #295 - but not sure where this bit of info should go.
