### ISSUE TITLE
Int64, package bit64

### ISSUE THREAD

**Issue by edzer** [edzer/sfr#37]
GDAL 2.x can read Int64 values, but (base) R can't store them. Right now, sf converts these to double, and warns when information gets lost (values are over 2^53). Another approach would be to return them as `integer64`, an S3 type provided by package [bit64](https://cran.r-project.org/web/packages/bit64/index.html).

**Comment by rsbivand** [comment]
I'd opt for not doing this, firstly because all the uses of Int64 have been errors (either a long ID or a value that should have been real), and secontly because R should get int64 sometime, and it will be more sensible to wait. I'm going to change rgdal to only return string/factor for int64 ("no.loss"). I'd only change my view and introduce a rather unstable hack if there was overwhelming evidence of real use cases.

**Comment by bhaskarvk** [comment]
Every shapefile downloaded from US Census bureau has this problem.
Download the states file from https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2016&layergroup=States+%28and+equivalent%29 and see for yourself.

Here's a gist with outputs reading once with gdal 1.x and then with 2.x
https://gist.github.com/bhaskarvk/686deca51e3e81cb785ed8f2430ac2fc

**Comment by rsbivand** [comment]
The "precision" implied by interger64 should never have been there at all - this is an upstream
problem exclusively. Please ask them to master their own software (ESRI?) so
that they actually use the right field definition (float with a decimal sign
for areas, etc.). Even better, stop using shapefiles, DBF is EOL.

Think of what you are asking before jumping to conclusions. Converting to
double will be useless when the value is actually a category (like census
block numbers). Obliging the user to cast to the correct representation is
the least misleading policy.

**Comment by bhaskarvk** [comment]
I am not asking for a default conversion to double. I would be very much happy with the integer64 argument of readOGR defaulting to 'warn.loss'.
I would be more than happy to stop using shapefile, but there is a ton of GIS data out there that is distributed exclusively as shapefiles, and most probably wrongly generated as you've highlighted. 

Defaulting to 'warn.loss' seems like a sensible option to me, but I'll let others weigh in.

**Comment by rsbivand** [comment]
There aren't any others here. I'll post where there are others, on R-sig-geo, to ask whether to leave things as they are, do to "no.loss", or the middle position of "warn.loss".

**Comment by edzer** [comment]
Resolved [here](https://stat.ethz.ch/pipermail/r-sig-geo/2016-November/025104.html) for `rgdal::readOGR`; `sf::st_read()` still coerces to double, meaning no loss up to 2^53, and warns on loss.
