### ISSUE TITLE
readRDS issue with objects; sf_0.4-3

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#374]
In exercises, we are saving objects at the end of one session, to avoid regeneration in the next session. An example:

```
library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"))
class(nc[[attr(nc, "sf_column")]])
# [1] "sfc_MULTIPOLYGON" "sfc"             
saveRDS(nc, file="nc.rds")
q()
```
Next session, starting by subsetting to the area of interest:
```
nc <- readRDS("nc.rds")
class(nc[[attr(nc, "sf_column")]])
# [1] "sfc_MULTIPOLYGON" "sfc"             
nc_14 <- nc[1:4,]
class(nc_14[[attr(nc_14, "sf_column")]])
# [1] "list"
library(sf)
nc_14 <- nc[1:4,]
class(nc_14[[attr(nc_14, "sf_column")]])
# [1] "sfc_MULTIPOLYGON" "sfc"
```

This misunderstanding is caused because of S3 classes, that is subsetting chooses the only method it knows for `nc[`and does not propagate the geometry properties.

We've seen this predictably, but I don't think there is a convenient fix. S4 classes did force the loading of the namespace implied by the class definition, so sp -> sf conversion of scripts will need to be careful about this.

**Comment by edzer** [comment]
Is this similar to #343?

**Comment by rsbivand** [comment]
Yes, it looks similar. My  sp-based workflow was to store intermediate objects between lab sessions in RDS because others used the lab. I forgot that I'd need to put sp actively in the search path because S4 did that automatically, because it was declared that the class definitions were in sp. With S3, there is no such mechanism, so the wrong "[" is used in this case, for "data.frame" rather than for absent "sf". 

I agree as in #343 that this is a matter for explanation, because I don't think there is a fix.
