### ISSUE TITLE
Additional args to FUN in st_join() don't work

### ISSUE THREAD

**Issue by Robinlovelace** [edzer/sfr#376]
Reproducible example (on `sf_0.4-3` not tested on latest version):

```r
library(sf)
example("st_join")
st_join(a, b, FUN = mean, na.rm = T)
```

**Comment by edzer** [comment]
Well, the `...` are now passed on to the `join` function; you can't pass them on to both; in the dev version (which I'm looking at) this is documented. Whether it is a good idea is another question. The thinking was that you could pass on a pattern to `st_relate`, when that is used to join.

**Comment by Robinlovelace** [comment]
If it's documented that makes it less of an issue but I still think it's an issue: if people have a `FUN` argument a logical next step is to pass it args, as will lapply etc. I see the issue about not being able to pass all `...` and am not sure what the best solution to this issue is. If the code above can be made to work, or replaced by a different command that achieves the same result in `example("st_join")` that would be a benefit for users I think.

**Comment by edzer** [comment]
We should drop the FUN argument here, and use aggregate.sf directly when you want to aggregate.

On 11 June 2017 06:17:50 BST, Robin <notifications@github.com> wrote:
>If it's documented that makes it less of an issue but I still think
>it's an issue: if people have a `FUN` argument a logical next step is
>to pass it args, as will lapply etc. I see the issue about not being
>able to pass all `...` and am not sure what the best solution to this
>issue is. If the code above can be made to work, or replaced by a
>different command that achieves the same result in `example("st_join")`
>that would be a benefit for users I think.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/edzer/sfr/issues/376#issuecomment-307607399

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by edzer** [comment]
I am going to remove the `FUN` argument, and leave aggregation to `sf::aggregate.sf` of `summarise`, so that we can do this, following the example of `?st_join`, by
```r
st_join(a, b) %>% aggregate(list(.$a.x), mean)
```
or
```r
library(dplyr)
st_join(a, b) %>% group_by(a.x) %>% summarise(mean(a.y))

```

**Comment by edzer** [comment]
Deprecated arg `FUN` in `st_join` in https://github.com/edzer/sfr/commit/1db9b59ea3a6f6d31c4e704bf26e7f171b74f4d3.

**Comment by Robinlovelace** [comment]
Thanks Edzer, great fix! Will look into docs although probably not until I'm back from travels in July.
