### ISSUE TITLE
bbox (output of st_bbox) should inherit from sfg.

### ISSUE THREAD

**Issue by faridcher** [edzer/sfr#377]
Since bbox is special case of sfg.POLYGON class, it should inherit from `sfg`. so the `plot` and other functions would work properly with it. right now we have:

```r
dput(bbox)
```

> structure(c(352.761929384165, 3452.77142022004, 395.548757725359, 
3513.5466750884), .Names = c("xmin", "ymin", "xmax", "ymax"), class = "bbox", crs = structure(list(
    epsg = 32640L, proj4string = "+proj=utm +zone=40 +datum=WGS84 +units=km +no_defs"), .Names = c("epsg", 
"proj4string"), class = "crs"))

`class(bbox)` outputs `bbox` where it should be `bbox, sfg`.

the `plot(bbox)` doesn't plot a rectangle rather a bunch of points! Other spatial operators and functions (st_intersect etc) will work after this fix.

**Comment by edzer** [comment]
the output of `st_bbox` is not a special case of an `sfg` - what makes you think so?

**Comment by faridcher** [comment]
It doesn't have to be. This is part of a nice object oriented design. a `bbox` is basically a rectangle that can be represented by a polygon object (`sfg`).

**Comment by edzer** [comment]
No, it's not, you're talking about a different design (wish), not `sf`'s.

**Comment by tim-salabim** [comment]
@faridcher there is package [spex](https://github.com/mdsumner/spex) for this and it seems that it will (or even already does) provide what you want: https://github.com/mdsumner/spex/issues/7

**Comment by kent37** [comment]
Is a raster::extent usable with sf spatial functions such as st_intersects, etc.? I have occasion to use the bounding box of one geometry (a large collection of points) to subset another geometry (polygons). To do this it would be helpful to have a way to convert a bbox to an st_sfc. Here is my effort:
```
st_as_sfc.bbox = function(bb) {
  box = st_polygon(list(matrix(bb[c(1, 2, 3, 2, 3, 4, 1, 4, 1, 2)], ncol=2, byrow=TRUE)))
  st_sfc(box, crs=st_crs(bb))
}
```

**Comment by edzer** [comment]
Good thinking!

**Comment by edzer** [comment]
For compatibility with raster, maybe add an `st_bbox.Raster` method?

**Comment by kent37** [comment]
I don't work with `Raster` objects so I can't comment knowledgeably on`st_bbox.Raster`; however it seems to make sense.

**Comment by arredond** [comment]
Sorry to add onto this after more than half a year, but I concur with @faridcher that being able to coerce a `bbox` object to an `sfg` polygon object would be useful, although that doesn't mean changing `sf`'s design, which I particularly enjoy.

My particular struggle right now is the following: I have a set of rasters for which I want to extract each extent and keep them all in a single `sf` data frame. This is quite common in Remote Sensing: to have a vector layer showing the extent of your raster files. I have used @kent37 's solution to do that:

~~~R
st_polygon.bbox = function(bb) {
  st_polygon(list(matrix(bb[c(1, 2, 3, 2, 3, 4, 1, 4, 1, 2)], ncol=2, byrow=TRUE)))
}
~~~

What do you think about having an `st_polygon` method for `bbox` objects? It seems more natural to convert your bounding box to a polygon and _then_, if needed, group into an `sfc` list-column than to directly convert the `bbox` to the `sfc`. There would then be no need for `st_as_sfc.polygon`, as one could simply do:

~~~R
# For one bbox
bb %>% st_polygon %>% st_sfc 

# For multiple bbox's
a <- st_polygon(bb1)
b <- st_polygon(bb2)
st_sfc(list(a, b))
~~~

**Comment by tim-salabim** [comment]
`st_as_sfc(st_bbox(x))` should be what you are after. Or `x %>% st_bbox %>% st_as_sfc`

**Comment by arredond** [comment]
@tim-salabim The thing is I don't have one raster `x`, I have 800, and I want to group their bbox's in single geometry column, not in 800.

As I said, converting the `bbox` to a `sfg` Polygon instead of into an `sfc` list-column makes a lot more sense to me: one bbox to one feature geometry, not one bbox to a list of feature geometries.

**Comment by tim-salabim** [comment]
How bout a good-old `do.call` or `append`?

**Comment by tim-salabim** [comment]
So, I assume we are dealing with a list of rasters here? Here's an example of how you can get a `sfc` list-column from 800 rasters (though admittedly identical bboxes for all of them):
```r
library(sf)
library(mapview) # for the poppendorf raster data

rst = replicate(n = 800, poppendorf[[1]])
bbx = lapply(rst, function(i) st_as_sfc(st_bbox(i)))

bb_lst_1 = do.call("c", bbx)
bb_lst_2 = Reduce(append, bbx)

identical(bb_lst_1, bb_lst_2)

class(bb_lst_1)
```
One thing that is quite crucial here is that `st_as_sfc(st_bbox(x))` preserves the projection information, which is very useful. A `sfg` object cannot have projection information AFAIK (@edzer correct me if my wrong).

**Comment by arredond** [comment]
I have to admit I had no idea that could be done; I suppose I should have looked more into how list-columns work. 

I still think converting a `bbox` to a single feature is more intuitive than reducing a list-column but conserving the projection is an excellent point. Thanks!
