### ISSUE TITLE
tidyr::unite error

### ISSUE THREAD

**Issue by Nowosad** [edzer/sfr#378]
It's probably connected with https://github.com/edzer/sfr/issues/359.
The `unite()` function is the complement of the `separate` function. The latter works great, but the first one does not:

```R
library(sf)
library(tidyverse)
demo(nc, ask = FALSE, echo = FALSE)

nc2 = nc %>% 
  separate(CNTY_ID, c("a", "b"), sep = 2)

nc2 %>% 
  unite(CNTY_ID_NEW, c("a", "b"), sep = "")

Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index
```

**Comment by edzer** [comment]
Thanks; pls make your scripts reproducible (it seems you failed to load `tidyr`).

**Comment by edzer** [comment]
... but please double check it.

**Comment by Nowosad** [comment]
I've check it on two dataset - works well! Thanks.
