### ISSUE TITLE
Combine polygons by attribute

### ISSUE THREAD

**Issue by Nowosad** [edzer/sfr#382]
related to #275 

I've combined polygons by attribute using `group_by()` and `summarise()`. It leaves some lines, so I've tried @edzer tip about using `st_set_precision()`. However, every value I've tested (100 - 1000000000) keeps some "artefacts". What's the best way to deal with that kind of problems?

```
# devtools::install_github("nowosad/spData")
library(spData)
library(sf)
library(tidyverse)

world_continents1 = world %>% 
  group_by(continent) %>% 
  summarise(pop = sum(pop, na.rm = TRUE), country_n = n())
plot(world_continents1[1]) 

world_continents2 = world %>% 
  st_set_precision(10000) %>% 
  group_by(continent) %>% 
  summarise(pop = sum(pop, na.rm = TRUE), country_n = n())
plot(world_continents2[1]) 
```

![rplot](https://user-images.githubusercontent.com/3457131/27060678-6e54ed6a-4fac-11e7-9fff-cdda5f02a4d5.png)

**Comment by edzer** [comment]
Which lines do you see? You're sure these are not holes?

**Comment by Nowosad** [comment]
Yes, I'm certain. 

Data before `group_by()` and `summarise()` - no holes:

`plot(world[0])`

![rplot01](https://user-images.githubusercontent.com/3457131/27080891-f6f8632c-500b-11e7-851e-20aa134e533a.png)

Data after `group_by()` and `summarise()`, different value of precision - "artefacts" in a different places (e.g. North America):

```
world_continents3 = world %>% 
  st_set_precision(100) %>% 
  group_by(continent) %>% 
  summarise(pop = sum(pop, na.rm = TRUE), country_n = n())
plot(world_continents3[1]) 
```

![rplot02](https://user-images.githubusercontent.com/3457131/27080897-fc12af7a-500b-11e7-9171-2526b226e8a2.png)

**Comment by edzer** [comment]
None of the geometries you get are actual lines, all have dimension 2 and positive area:
```r
> world_continents2[1] %>% st_area() %>% units::set_units(km^2)
Units: km^2
[1] 29946212.22 12335958.52 31252444.82 23065279.95 24484309.31  8504478.20
[7]    11602.57 17762597.45
> world_continents2[1] %>% st_dimension()
[1] 2 2 2 2 2 2 2 2
```
what is of course possible is that there's no man's land between polygons. Africa seems to have 4 holes:
```r
> world_continents2[1] %>% st_cast("MULTIPOLYGON") %>% st_geometry() %>% sapply(lengths)
[[1]]
[1] 1 5

[[2]]
[1] 1 1 1 1 1 1 1 1

[[3]]
 [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1

[[4]]
 [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1

[[5]]
 [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[39] 1 1 1 1 1 1 1 1 1

[[6]]
 [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

[[7]]
[1] 1

[[8]]
[1] 1 1 1
```
Maybe use mapview to explore them, and mapedit to remove them?

**Comment by tim-salabim** [comment]
Thanks for the use-case :-)

**Comment by Nowosad** [comment]
@edzer Thanks for the investigation. I'm just still unsure why the number and location of these holes changes with different values of a "precision".

@tim-salabim I'll definitely try to use mapedit.

**Comment by edzer** [comment]
@Nowosad see also `?st_as_binary` for more docs, also try precision values smaller than 0; create a toy example to understand how it works.
