### ISSUE TITLE
Simple features types

### ISSUE THREAD

**Issue by Nowosad** [edzer/sfr#383]
@edzer I've a question about the number of implemented feature types. The "README.md" file starts with "Package sf: represents natively in R all 17 simple feature types for all dimensions (XY, XYZ, XYM, XYZM)", however I've only seen examples with `POINT`, `LINESTRING`, `POLYGON`, `MULTIPOINT`, `MULTILINESTRING`, `MULTIPOLYGON` and `GEOMETRYCOLLECTION`. 
I also tried to create unusual type (for example `CIRCULARSTRING`) , but was unable to plot it.
Therefore, are all of the features implemented? If not, do you plan to implement them?

**Comment by edzer** [comment]
All 68 types can be represented in R, and read and written to external sources. You overlooked the tests when searching for examples. The feature types _after_ `GEOMETRYCOLLECTION` are rarely found in the wild, and only received (partial) [support](https://trac.osgeo.org/gdal/wiki/rfc49_curve_geometries) relatively recently from GDAL.

As long as nobody uses these types, implementing plot methods for them in R doesn't make sense.

**Comment by Nowosad** [comment]
Thanks for clarification!
