### ISSUE TITLE
Comparison between the global OLS and the local GWR to predict determinant of the variance communicable diseases based on geographical variations.

### ISSUE THREAD

**Issue by hamzah73** [edzer/sfr#386]
Dear experts,

Based one of interesting research articles that available in http://cjs.sljol.info/articles/abstract/10.4038/cjs.v45i3.7399/. 

The authors make conclusions when the Ordinary Least Square (OLS) regression was first applied to find its suitability in an identification of the linear relationship. OLS analysis conducted 

> under this study revealed OLS is not a good method to model the relationship between dengue incidence and influencing factors". Then Geographically Weighted Regression (GWR) analysis was conducted and "it outran OLS in modelling the relationship.

 

For explanatory variables rainfall and population density, 

> OLS can only explain 33.2% of the variance of dengue incidence" while "GWR can explain 56.3% of the same. "GWR can identify the spatially non-stationary behaviour of influencing factors on dengue incidence". These analyses revealed the influence of rainfall and population density is location dependent and hence need local analysis over conventional global analysis. 

My questions as following 

Why the local GWR better explain the phenomenon compared than global OLS?
Is the conclusion of this study that it can be making the generalisation for all investigations comparison global OLS and local GWR to predict determinant of the variance communicable diseases based on geographical variations?
What did the advantage and disadvantage using local GWR and global OLS? 
When the global OLS make better explanation situation than local GWR?

I very much look forward to hearing from you. Thank you very much for your feedback. 

With kind regards.

**Comment by rsbivand** [comment]
Write to [R-sig-geo](https://stat.ethz.ch/mailman/listinfo/r-sig-geo) - this is not an issue for this package. Do so after reading [Páez et al. (2011)](http://journals.sagepub.com/doi/abs/10.1068/a44111) and [Gollini et al. (2015)](https://www.jstatsoft.org/article/view/v063i17). GWR was developed to try to detect missing variables, but because it induces local collinearity, it is very unreliable statistically.

**Comment by hamzah73** [comment]
Dear 

I thank you for taking time out to give comments my question. I am interested in the issue since have been reading

> Fotheringham  AS, Brunsdon C, Charlton M. Geographically weighted regression: the analysis of spatially varying relationships: John Wiley & Sons; 2003 which available in http://eu.wiley.com/WileyCDA/WileyTitle/productCd-0471496162.html 

So, I am creating the connection to the topic with the article above.  Sorry for the inconvenience!

Best regards

**Comment by rsbivand** [comment]
This book is very out of date and makes many untested claims. Only the first author is concerned now with continuing to "sell" GWR, the others contributed to Gollini et al. (2015) which is open-access. Read that instead!

**Comment by hamzah73** [comment]
Once again, I thank you for taking time out to give comments regarding of the issue and useful links. 

I will learn it. 


Best regards
