### ISSUE TITLE
Usage of st_contains

### ISSUE THREAD

**Issue by boshek** [edzer/sfr#388]
Hi there,

Amazing package. Wonderfully useable. 

I am trying to figure out how `st_contains` works. I am imagining that it takes some points and figures out which polygons there are in. But doesn't seem to the output I am getting so I must be missing something. Here is a minimal example:

```
library(sf)
devtools::install_github("tidyverse/ggplot2")
library(ggplot2)
library(dplyr)

## Some city data
cities <- st_as_sf(data.frame(city = c("Raleigh","Durham","Charlotte"),
           lat = c(35.787743, 35.994034, 35.227085),
           lon = c(-78.644257,-78.898621, -80.843124)), coords = c("lon", "lat"), crs = 4326)


## Read in north carolina data
nc <- st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE) %>%
  st_transform(crs = 4326)

## Plot it - looks right
ggplot(nc) +
  geom_sf(aes(fill = AREA)) +
  geom_sf(data = cities, aes(shape = city), colour = "green") 

## Not sure how to interpret output from st_contains
st_contains(nc, cities)
```
But then I get a list of values when really what I would like is a data.frame or preferably an `sf` object that contains a column for city and then the county that it is in. Maybe I am mis-interpreting what `st_contains` is. But what I am looking for is to assign county to city (or it could be the reverse doesn't matter). Any ideas?

Thanks in advance.

**Comment by edzer** [comment]
`st_join`?

```r
> st_join(cities, nc)
although coordinates are longitude/latitude, it is assumed that they are planar
Simple feature collection with 3 features and 15 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: -80.84312 ymin: 35.22709 xmax: -78.64426 ymax: 35.99403
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
       city  AREA PERIMETER CNTY_ CNTY_ID        NAME  FIPS FIPSNO CRESS_ID
1   Raleigh 0.219     2.130  1938    1938        Wake 37183  37183       92
2    Durham 0.077     1.271  1908    1908      Durham 37063  37063       32
3 Charlotte 0.143     1.887  2041    2041 Mecklenburg 37119  37119       60
  BIR74 SID74 NWBIR74 BIR79 SID79 NWBIR79                    geometry
1 14484    16    4397 20857    31    6221 POINT(-78.644257 35.787743)
2  7970    16    3732 10432    22    4948 POINT(-78.898621 35.994034)
3 21588    44    8027 30757    35   11631 POINT(-80.843124 35.227085)
```

**Comment by boshek** [comment]
Yes I think this is perfect. I am a little confused then exactly what `st_contains()` does and what it outputs. Is it possible for you to elaborate?

**Comment by rsbivand** [comment]
Ouch! Smell of shot feet ...

```> st_crs(nc)
$epsg
[1] 4267

$proj4string
[1] "+proj=longlat +datum=NAD27 +no_defs"

attr(,"class")
[1] "crs"
```
and [EPSG 4267](https://epsg.io/4267) isn't WGS84. There is a warning about geographical coordinates, maybe about differing datums/etc. too?

**Comment by ben519** [comment]
Adding to this, I'm also a bit confused about the difference between `st_contains()`, `st_contains_properly()` and `st_intersects()`.  Here's an example where I'd expect `st_contains()` and `st_contains_properly()` to give different results, but they don't.

```
library(sf)

# make a unit square
unitsquare <- st_polygon(x = list(
  matrix = rbind(c(0,0), c(1,0), c(1,1), c(0,1), c(0,0))
))

# make some points
somepts_collection <- st_sfc(
  st_point(c(0, 0)),
  st_point(c(0.5, 0.5)),
  st_point(c(0.5, 1)),
  st_point(c(0, 1)),
  st_point(c(1, 0)),
  st_point(c(1.5, 1.5)),
  st_point(c(0.5, 0))
)

# plot
plot(somepts_collection)
plot(unitsquare, add = TRUE)

# spatial joins
st_contains(unitsquare, somepts_collection)  # 2
st_contains_properly(unitsquare, somepts_collection)  # 2
st_intersects(unitsquare, somepts_collection)  # 1 2 3 4 5 7
```

<img width="352" alt="screen shot 2017-06-19 at 2 32 38 pm" src="https://user-images.githubusercontent.com/723099/27302374-754cbc6a-54fc-11e7-8a44-d1e7c1466e11.png">

**Comment by boshek** [comment]
@rsbivand Where is that coordinate system coming from? I see:

```
> st_crs(cities)
$epsg
[1] 4326

$proj4string
[1] "+proj=longlat +datum=WGS84 +no_defs"

attr(,"class")
[1] "crs"
> 
> st_crs(nc)
$epsg
[1] 4326

$proj4string
[1] "+proj=longlat +datum=WGS84 +no_defs"

attr(,"class")
[1] "crs"
```

**Comment by edzer** [comment]
@ben519 here is the difference:
```r
> st_contains(unitsquare, unitsquare)
[[1]]
[1] 1

> st_contains_properly(unitsquare, unitsquare)
[[1]]
integer(0)
```

**Comment by rsbivand** [comment]
OK, the example did transform:

```
nc <- st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE) %>%
  st_transform(crs = 4326)
```
but I'd assumed simply - another NSE issue:
```
nc <- st_read(system.file("shape/nc.shp", package="sf"))
```
I would always do:
```
nc <- st_read(system.file("shape/nc.shp", package="sf"))
nc_wgs84 <- st_transform(nc, 4326)
```
as nc in most of the documentation is untransformed.

**Comment by ben519** [comment]
@edzer Thanks (I actually read this in the docs).  What's confusing to me is that, the unit square contains the unit square, but the unit square does not contain a subset of the unit square? Specifically the point (0, 0.5)?

```
st_contains(unitsquare, unitsquare)  # unit square contains unit square
st_contains(unitsquare, st_point(c(0.5, 0)))  # unit square does not contain a point on the unit square
```
Note that if I make an invalid polygon of just one point (0.5, 0), `st_contains()` returns the point.

```
st_contains(unitsquare, st_polygon(list(matrix = rbind(c(0.5,0), c(0.5,0), c(0.5,0), c(0.5,0), c(0.5,0)))))
```

Any way to describe the logic behind `st_contains()` in words?

**Comment by edzer** [comment]
[this](https://en.wikipedia.org/wiki/DE-9IM) might help - it explains what GEOS actually does.

**Comment by ben519** [comment]
@edzer Just what I was looking for, thanks!

> a contains b iff no points of b lie in the exterior of a, and at least one point of the interior of b lies in the interior of a
