### ISSUE TITLE
crash during st_intersect()

### ISSUE THREAD

**Issue by tcovert** [edzer/sfr#389]
I've experienced a variety of crashes in the form of:
```
Assertion failed: (0), function query, file AbstractSTRtree.cpp, line 287.
Abort trap: 6
```
the most recent one was a call to `st_intersect()` - I can post the code and shape files if it helps, but I assume the crash is related to a variety of previously noted GDAL/GEOS issues:
https://github.com/Toblerity/Shapely/issues/260
https://stackoverflow.com/questions/27675734/python-basemap-assertion-failed
https://stackoverflow.com/questions/32054721/basemap-causes-python-to-abort

These are all python-specific solutions, so I am not sure how I would apply them here.

My setup is R 3.4.0, GEOS 3.6.1, GDAL 2.1.2, and proj.4 4.9.3 - all homebrew (Mac OS 10.12.5) and mostly built from source.  Any suggestions about how to fix this?  I tried building GDAL and GEOS from source before re-installing `sf`, but I still get these bugs.  

Thanks in advance for any suggestions!

**Comment by edzer** [comment]
Did this also happen with `st_intersects(..., prepared = FALSE)`?

If you want me (or anyone else) to look into this, please provide a reprex.

**Comment by tcovert** [comment]
My mistake - was `st_intersection()` that is throwing the error.  Here is an MWE:

```
library(sf)
library(dplyr)
library(tibble)

units <- st_read("State_Units.shp")
leases <- st_read("all_lease.shp")
lease_unit <- st_intersection(leases, units)
```

the two shapefiles are available [here](https://www.dropbox.com/s/1vrwzzowuszcy6u/all_lease.tar.gz?dl=0) and [here](https://www.dropbox.com/s/1qjpd0gdodi6y6j/State_Units.tar.gz?dl=0)

Thanks in advance for taking a look!

**Comment by tcovert** [comment]
I also get the same crashes when I test for validity on those shape files using `st_is_valid()`.  Note: QGIS doesn't seem to have a problem opening them up.

**Comment by tcovert** [comment]
Ok, I'm pretty sure this is a homebrew issue and not an `sf` issue: I was at least able to get this intersection started by using the R binary + a fresh install of `sf`.  Thanks for taking a look.
