### ISSUE TITLE
Can't specify the namespace explicitely for summarise

### ISSUE THREAD

**Issue by pierreroudier** [edzer/sfr#390]
I have a coplex workflow that uses packages that pull both `plyr` and `dplyr`, so I need to specify explicitely the namespace of functions that share the same name using the `::` operator:

```
plyr::summarise(...)
dplyr::summarise(...)
```

I can't seem to be able to do so with the `summarise` method for `sf` objects:

```
library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"))
nc %>% 
  dplyr::group_by(SID74) %>%
  sf::summarise(foo = mean(AREA))
```

Gives:

```
Error: 'summarise' is not an exported object from 'namespace:sf'
```

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_NZ.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_NZ.UTF-8        LC_COLLATE=en_NZ.UTF-8    
 [5] LC_MONETARY=en_NZ.UTF-8    LC_MESSAGES=en_NZ.UTF-8   
 [7] LC_PAPER=en_NZ.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_NZ.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0 sf_0.5-0   

loaded via a namespace (and not attached):
 [1] compiler_3.4.0   lazyeval_0.2.0   R6_2.2.1         assertthat_0.2.0
 [5] magrittr_1.5     tools_3.4.0      DBI_0.6-1        units_0.4-4     
 [9] tibble_1.3.3     Rcpp_0.12.11     udunits2_0.13    grid_3.4.0      
[13] rlang_0.1.1    
```

**Comment by edzer** [comment]
The cause for this mess lies with the author of the plyr and dplyr packages, no doubt a new plyr is in the pipeline to resolve this, if you want to be sure, raise an issue there.

`sf` only exports an S3 method for `summarise`, with `dplyr` providing the generic. This means that the method is only activated after `dplyr`'s namespace is loaded. You don't want to do this, in which case you can address the unexported function implementing the method by `sf:::summarise.sf`. Not very nice, I'd agree, but caused by a problem somewhere else (or by not having migrated entirely to the tidyverse).

**Comment by pierreroudier** [comment]
@edzer Thanks for the swift reply,

I should have mentioned that I also did try using the unexported `summarise.sf``, but it returns the following error:

```
> nc %>% 
+   dplyr::group_by(SID74) %>%
+   sf:::summarise.sf(foo = mean(AREA))
Error in NextMethod() : 'NextMethod' called from an anonymous function
```

The problem persists even if I load `dplyr`:

```
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> nc %>% 
+   dplyr::group_by(SID74) %>%
+   sf:::summarise.sf(foo = mean(AREA))
Error in NextMethod() : 'NextMethod' called from an anonymous function
```

**Comment by edzer** [comment]
After loading `dplyr` you can simply call `summarise` without the `sf::` or `sf:::`.
