### ISSUE TITLE
st_write, GPKG and ESRI

### ISSUE THREAD

**Issue by obrl-soil** [edzer/sfr#392]
I hesitate to call this a bug since it only causes problems in ArcMap, however I'm trying to wean my colleagues off using shapefiles and this has been a hurdle:

```
library(sf)
Linking to GEOS 3.5.0, GDAL 2.1.1, proj.4 4.9.3
> nc = st_read(system.file("shape/nc.shp", package="sf"))
> setwd('C:/DATA/stwrite')
> st_write(nc, file.path(getwd(), 'nc.gpkg'), quiet = TRUE)
> st_write(nc, dsn = file.path(getwd(), 'nc2.gpkg'), layer = 'nc', quiet = TRUE)
> st_write(nc, dsn = file.path(getwd(), 'nc3.gpkg'), layer = 'nc.gpkg', quiet = TRUE)
```

of the three st_write calls above, only the second can be opened in ArcMap 10.4.1, I think because of the file extension getting repeated in the layer name. Here's what they look like in ArcCatalogue:

![screencap](https://github.com/obrl-soil/bits-n-pieces/blob/master/images/arc_catalogview.PNG?raw=true)

The other two throw some fairly cryptic errors. Would it be a bad idea to change the default for `layer` to something like `ifelse(driver %in% db_drivers, tools::file_path_sans_ext(basename(dsn)), basename(dsn))`?

**Comment by edzer** [comment]
This is nasty, but looking at the [standard](http://www.geopackage.org/spec/#_contents) it looks to me as if ESRI is the one not implementing it, rather than GDAL, which sf uses. Maybe ask support from them?

**Comment by obrl-soil** [comment]
Hmm might have to. That said, it seems like SQLite table names containing '.' [are technically not valid](https://stackoverflow.com/questions/3694276/what-are-valid-table-names-in-sqlite), but can be quoted in queries, like R data frame column headings that have spaces. So maybe ESRI aren't wrong exactly, just more strict about their table names than other apps. Their proprietary formats are [similarly strict](http://support.esri.com/technical-article/000005588).

**Comment by rsbivand** [comment]
I'd ask @scw for an opinion, he's in on plenty of things, and will have insights from ESRI here, I guess.

**Comment by scw** [comment]
I can confirm that names which would be valid in a quoted context aren't in ArcGIS. We have an internal issue tracking this problem for SQLite backed databases (including Geopackage). As mentioned, the workaround is to use only names which are valid without quoting. Agree that it may be worth trying to prevent entry of these independently of the implementation bug in ArcGIS, since this is more likely to cause confusion than benefit to users, who will need to explicitly quote the resulting table names in many contexts.

**Comment by edzer** [comment]
Does anyone see any disadvantage in taking off the .gpkg from the default layer name?

**Comment by acadetev** [comment]
st_write(obj = miprov, dsn ='miprovexportado.gpkg', driver = 'gpkg')
miprovexportado <- st_read(dsn = 'miprovexportado.gpkg')

**Comment by acadetev** [comment]
que error puede tener esta linea de códigos?
st_write(obj = miprov, dsn ='miprovexportado.gpkg', driver = 'gpkg')
miprovexportado <- st_read(dsn = 'miprovexportado.gpkg')

**Comment by acadetev** [comment]
![linea cod](https://user-images.githubusercontent.com/39652018/68092761-d7125b80-fe64-11e9-9cbe-426823f9fbb7.JPG)
me da este error
