### ISSUE TITLE
latitude outside [-90,90] causes segfault

### ISSUE THREAD

**Issue by edzer** [edzer/sfr#398]
Reported here: https://github.com/tidyverse/ggplot2/issues/2172

**Comment by rsbivand** [comment]
Does generating the graticules in geom_sf lead to an inverse projection for which no inverse exists in PROJ.4, which would crash R for PROJ.4 <4.9.3 and unprotected function? Couldn't the posters quote the versions of external dependencies? I'm going to patch rgdal to use the PROJ >= 4.9.3 fix rather than Barry's fix for this.

**Comment by edzer** [comment]
Short version of the crash:
```r
library(sf)
pt = st_sfc(st_point(c(0,92)), crs = 4267)
robin_crs <- "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
india_crs <- "+init=epsg:24383"  # India-centered Lambert conformal conic projection
st_transform(st_transform(pt, robin_crs), india_crs)
```

**Comment by edzer** [comment]
Of course, 
```r
> st_transform(pt, robin_crs)
Geometry set for 1 feature 
geometry type:  POINT
dimension:      XY
bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
epsg (SRID):    NA
proj4string:    +proj=robin +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs
POINT(NaN NaN)
```
so we could try and catch that before calling `st_transform` again.

Also, 
```r
> st_point()
POINT(NA NA)
```
is how `sf` represents an empty point (lacking anything better: following the sfa standard here).

**Comment by rsbivand** [comment]
```
> sp_pt <- as(pt, "Spatial")
> summary(sp_pt)
Object of class SpatialPoints
Coordinates:
          min max
coords.x1   0   0
coords.x2  92  92
Is projected: FALSE 
proj4string :
[+proj=longlat +datum=NAD27 +no_defs +ellps=clrk66
+nadgrids=@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat]
Number of points: 1
> spTransform(sp_pt, CRS(robin_crs))
Error in spTransform(sp_pt, CRS(robin_crs)) : 
  error in pj_transform: latitude or longitude exceeded limits
> traceback()
3: .Call("transform", proj4string(x), slot(CRSobj, "projargs"), 
       n, as.double(crds[, 1]), as.double(crds[, 2]), NULL, PACKAGE = "rgdal")
2: spTransform(sp_pt, CRS(robin_crs))
1: spTransform(sp_pt, CRS(robin_crs))
```

and line 385 ff in rgdal/src/projectit.cpp:

              if(pj_transform(toPJ, fromPJ, (long) n, 0, xx, yy, NULL) != 0) {
		pj_free(fromPJ); pj_free(toPJ);
		error("error in pj_transform: %s",
                    pj_strerrno(*pj_get_errno_ref()));

so the error is thrown by pj_transform itself at or around line 495 in src/pj_transform.c. Actually, the error is set but the rgdal implementation is overly strict, as HUGE_VAL is assigned, so it could leave the mess up to the user to sort out, maybe unlike what is in GDALs ogr/ogrct.cpp following line 1200. So yes, maybe an is.finite check? Maybe test on R_FINITE in the loop at sfr/src/gdal.cpp about line 275?

**Comment by rsbivand** [comment]
Actually this is not an empty point, is it? It is a point that cannot exist in the CRS?

**Comment by rsbivand** [comment]
By the way, I don't see a crash:

```
> sf_extSoftVersion()
          GEOS           GDAL         proj.4         lwgeom 
       "3.6.1"        "2.2.0"        "4.9.3" "2.3.2 r15302" 
> st_transform(st_transform(pt, robin_crs), india_crs)
Geometry set for 1 feature 
geometry type:  POINT
dimension:      XY
bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
epsg (SRID):    24383
proj4string:    +proj=lcc +lat_1=12 +lat_0=12 +lon_0=80 +k_0=0.99878641 +x_0=2743195.5 +y_0=914398.5 +a=6377299.151 +b=6356098.145120132 +towgs84=295,736,257,0,0,0,0 +units=m +no_defs
POINT(NaN NaN)
```

Which PROJ.4 is underlying your crashing case?

**Comment by edzer** [comment]
I was testing with
```r
> library(sf)
Linking to GEOS 3.5.1, GDAL 2.1.3, proj.4 4.9.2, lwgeom 2.3.2 r15302
```
and will check proj.4 4.9.3

**Comment by rsbivand** [comment]
OK, may be: https://github.com/OSGeo/proj.4/commit/757a2c8f946faccf9d094d76cb79e6ebe0006564#diff-f0c3df1eafd91a86f6cd9cf68cc306ddR23

**Comment by edzer** [comment]
@rsbivand : I think that a point that cannot exist in the current CRS is a missing point. Missing geometries are like `NA`-valued geometries. I had to think of this:
```r
> cut(0:4, 1:3)
[1] <NA>  <NA>  (1,2] (2,3] <NA> 
Levels: (1,2] (2,3]
```
what we can't map, becomes missing-valued.

**Comment by rsbivand** [comment]
OK, but then we need two missing value variants, one that cannot exist by definition, and another that could exist but is not observed?

**Comment by edzer** [comment]
I don't think [sfa](http://www.opengeospatial.org/standards/sfa) addresses unobserved existing geometries. Empty geometries reflect the logical empty set, e.g. the intersection of two non-intersecting geometries.

(It's only for `POINT` that this involves `NA` values; for all other geometries the implementation is an empty set (multipoint/linestring with zero points, other things empty sets/lists); I believe this is a recognized design flaw of sfa.)

**Comment by rsbivand** [comment]
OK, makes sense as a standard.
