### ISSUE TITLE
Support GeoJSON identifiers in st_write

### ISSUE THREAD

**Issue by mem48** [edzer/sfr#401]
The output GeoJSON is not exactly compliant with the GeoJSON standard specifically:

http://geojson.org/geojson-spec.html#feature-objects 
"If a feature has a commonly used identifier, that identifier should be included as a member of the feature object with the name "id"."

st_write produces

```
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature" ,"properties": { "id": 1, "code": "E01014536" }, "geometry": { "type": "Point", "coordinates": [ -2.547147520499006, 51.428192037882319 ] } },
{ "type": "Feature" ,"properties": { "id": 2, "code": "E01014546" }, "geometry": { "type": "Point", "coordinates": [ -2.618523650706068, 51.454530202716143 ] } }
]
}
```

ideal GeoJSON is

```
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "id": 1 ,"properties": { "code": "E01014536" }, "geometry": { "type": "Point", "coordinates": [ -2.547147520499006, 51.428192037882319 ] } },
{ "type": "Feature", "id": 2 ,"properties": { "code": "E01014546" }, "geometry": { "type": "Point", "coordinates": [ -2.618523650706068, 51.454530202716143 ] } }
]
}
```
It is a subtle difference, but will cause software that strictly enforces the standard to reject the file.

**Comment by edzer** [comment]
`sf` doesn't write GeoJSON by itself, it uses the GDAL library for that; see [here](http://www.gdal.org/drv_geojson.html) for the driver description -- in case there is an issue you'd have to file it there.

Also note that GeoJSON is still a draft standard, that the document you refer to points out that it is obsolete.

**Comment by mem48** [comment]
Thanks for the clarification.
