### ISSUE TITLE
No methods to explicitly convert an sf object to a tibble with class sf

### ISSUE THREAD

**Issue by odeleongt** [edzer/sfr#404]
Although methods are provided for tidyverse verbs which allow preserving `sf` class when using `dplyr` and `tidyr` verbs, there is no method to explicitly convert a regular `sf` (class sf and data.frame) to a tibble preserving the sf class:

```
library(package = "sf")
library(package = "tidyverse")
nc <- read_sf(system.file("shape/nc.shp", package = "sf"))
class(as_tibble(nc))
## [1] "tbl_df"     "tbl"        "data.frame"
```

With the currently provided methods, sf objects are converted to tibbles only implicitly through the use of some tidyverse verbs:

```
class(count(nc, CNTY_ID))
## [1] "sf"         "tbl_df"     "tbl"        "data.frame"
```

**Comment by edzer** [comment]
#405 (thanks!) is one way of doing this; another is to have `read_sf` always create `tbl_df`'s. because that's what `read_*` functions do.

I don't see so much point in moving between the two (very similar) representations when they're already converted to `sf` - that should better happen before that.

**Comment by odeleongt** [comment]
I agree. It already uses the `stringsAsFactors = FALSE` default and follows the naming convention, it might as well return a tibble. I just felt it was a more intrusive change, though it would work for me.

I like the idea of providing `as_tibble.sf` and `as_data_frame.sf` methods because they change the behavior only if `tibble` is attached or imported, which is when it makes sense using them.
It also allows to explicitly convert if for some reason you want to and have and sf data.frame.

Since `sf` does not import `tidyverse` functions, and we can't assume it to be installed, converting to class `tbl_df` in `read_sf` should be done manually. This would add overhead to package maintenance (if tibble classes are changed internally for some reason), but even if something changes in the `tidyverse` sf objects with class `tbl_df` would still work as `sf` and `data.frame`s:

```
read_sf <- function(..., quiet = TRUE, stringsAsFactors = FALSE){
	x = st_read(..., quiet = quiet, stringsAsFactors = stringsAsFactors)
        class(x) = c("sf", "tbl", "tbl_df", "data.frame")
        x
}
```

Should I add this change to the pull request? I can also revert the commits implementing the `as_tibble.sf` and `as_data_frame.sf` methods, though I still think those could be useful and have little footprint.
