### ISSUE TITLE
[Request] dplyr join operations with spatial predicates?

### ISSUE THREAD

**Issue by kendonB** [edzer/sfr#50]
I haven't dug into ``sfr`` yet, so I don't know if you're allowing ``sf`` objects to contain multiple geometries (i.e. two ``MULTIPOLYGON``s or a ``MULTIPOLYGON`` and a ``MULTIPOINT``). If you can, (and if you can't, I think you should), then *join operations would result in ``sf`` objects with multiple geometries.

A proposed combo:
```
mp1 # sf with MULTIPOLYGON
mp2 # sf with MULTIPOLYGON
mp3 <- left_join(mp1, mp2, border = FALSE)
```
would result in an ``sf`` with two columns geometry1 and geometry2 and would behave just like left_join in dplyr except a match is defined as two geometries with positive spatial overlap; ``border = TRUE`` would include matches with common borders. ``left_join(x, y)`` includes all observations in x, regardless of whether they match or not. Multiple matches return as multiple rows.

There are maybe more match conditions that you would want to include. Perhaps allowing any function that takes two ``sfg`` objects and returns a logical would make the most sense. Does ``st_intersects``, for example, allow ``sfg`` objects as inputs? If so, then this could be fully general for any pair of ``sf`` types. Usage would be something like:
```
mp3 <- left_join(mp1, mp2, match_fun = st_touches)
```
It probably also makes sense to do this so you don't have to reinvent the join wheel. I don't believe dplyr allows for arbitrary conditions for join matches yet (https://github.com/hadley/dplyr/issues/557), but there might be a solution that isn't too difficult to implement.

The user could also generate new geometry columns using any function that takes two ``sfg``s and returns an ``sfg``. i.e.:
```
mp3 <- mp3 %>%
  mutate(geometry3 = purrr::map2(geometry1, geometry2, st_intersection))
```

**Comment by kendonB** [comment]
A relevant discussion: https://github.com/edzer/sfr/issues/121

**Comment by edzer** [comment]
See also #239 ; join methods still return single geometry columns, t.b.d.

**Comment by edzer** [comment]
I tried with `dplyr` release candidate, but that doesn't let you join two tables with geometry list columns, even if you don't join on either of them, meaning we can't solve this on the `sf` side.
