### ISSUE TITLE
Feature request -- eliding and ± scaling multipolygons; PLUS need more than just *.shp

### ISSUE THREAD

**Issue by technocrat** [edzer/sfr#51]
First, the minor gotcha, for the benefit of other pilgrims. I was trying to read in a shapefile 

```
filename <- system.file("/Users/rc/Desktop/gitmo/guardian/data/cb_2015_us_cd114_5m.shp", package="sf")
```
and got

```
   Error in default_layer(dsn) : 
  cannot guess layer name from this datasource
```
but then realized my data was not readable with system.file because it wasn't in a package.

Then I tried

```
    filename <- "/Users/rc/Desktop/gitmo/guardian/data/cb_2015_us_cd114_5m.shp"
    > us <- st_read(filename, crs = 4267)
      Cannot open data source /Users/rc/Desktop/gitmo/guardian/data/cb_2015_us_cd114_5m.shp
      Error in eval(substitute(expr), envir, enclos) : Open failed.
    In addition: Warning message:
      In CPL_read_ogr(dsn, layer, as.character(options), quiet, iGeomField -  :
     GDAL Error 4: Unable to open /Users/rc/Desktop/gitmo/guardian/data/cb_2015_us_cd114_5m.shx             or /Users/rc/Desktop/gitmo/guardian/data/cb_2015_us_cd114_5m.SHX.Try --config      SHAPE_RESTORE_SHX true 

```
Finally, I realized that .shp *still* needs to be in the same directory with the other ESRI files

```
> filename <- "/Users/rc/Desktop/gitmo/guardian/data/cb_2015_us_cd114_5m/cb_2015_us_cd114_5m.shp"
> us <- st_read(filename, crs = 4267)
Reading layer cb_2015_us_cd114_5m from data source /Users/rc/Desktop/gitmo/guardian/data/cb_2015_us_cd114_5m/cb_2015_us_cd114_5m.shp using driver "ESRI Shapefile"
features:       441
fields:         8
converted into: MULTIPOLYGON
proj4string:    +proj=longlat +datum=NAD83 +no_defs 
Warning message:
In check_replace(x, value) :
  st_crs: replacing crs does not reproject data; use st_transform for that

```

So, in this way, it works just like ReadOGR.  

The **feature** I need are the ability to elide and scale (as shown in the US map in the June presentation (not obvious how to do this in *sf*) and to be able to scale a multipolygon **up**. My objective is to outset the really small units like RI, DE and especially DC out in the Atlantic, big enough to add centroid labels and to color with attributes.

**Comment by edzer** [comment]
Thanks for the report. I improved the vignette, noting that `system.file` is not for regular use.

Regarding elide & scale, you can do regular math ops `*`, `+` and `-` to scale, rotate and shift geometries or geometry collections:
```
> st_point(c(1,2)) * 3 + c(0,10)
POINT(3 16) 
```
Re-install sf from github, and run `demo(affine)` for a demo:
![rot](https://cloud.githubusercontent.com/assets/520851/20036950/6dea9af0-a417-11e6-8544-351f3749e84d.png)

The interface is that of the [affine transformation](https://en.wikipedia.org/wiki/Affine_transformation), where you specify `M` (or in case of a scalar: the diagonal of `M`) and `b` (which can also be scalar). To reach your objective, some helper functions may be convenient (pls suggest), but in principle you can do it by affine transformation.

**Comment by rgzn** [comment]
some built in helper functions for affine transformations would indeed be helpful. Something like:

```
st_rotate = function(sf_object, rot_angle) {
  rot_M = function(a) matrix(c(cos(a), sin(a), -sin(a), cos(a)), 2, 2)
  sf_object %>% 
    `-`(st_centroid(st_union(sf_object))) %>% 
    `*`(rot(rot_angle * pi / 180)) %>% 
    `+`(st_centroid(st_union(sf_object)))
}
```

obviously i'm using tidyverse stuff here which probably wouldn't be appropriate. But it would be nice to have common transformation encapsulated as functions within the sf package.
