### ISSUE TITLE
saving sf objects with geometry type: GEOMETRY

### ISSUE THREAD

**Issue by tiernanmartin** [edzer/sfr#56]
Is there a recommended file format for storing `sf` objects that have `geometry type: GEOMETRY`?

It seems like both `.shp` and `.gpkg` return the following error:
```
GEOMETRY :
Error in eval(substitute(expr), envir, enclos) : unknown type!
```

A reproducible test:

```
# Polygon geometry: pol

p1 <- rbind(c(0,0), c(1,0), c(3,2), c(2,4), c(1,4), c(0,0))
p2 <- rbind(c(1,1), c(1,2), c(2,2), c(1,1))
pol <-st_polygon(list(p1,p2))
# 
# Multi-polygon geometry: mpol

p3 <- rbind(c(3,0), c(4,0), c(4,1), c(3,1), c(3,0))
p4 <- rbind(c(3.3,0.3), c(3.8,0.3), c(3.8,0.8), c(3.3,0.8), c(3.3,0.3))[5:1,]
p5 <- rbind(c(3,3), c(4,2), c(4,3), c(3,3))
mpol <- st_multipolygon(list(list(p1,p2), list(p3,p4), list(p5)))

# sf object w/ polygon: sf_pol

sf_pol <- 
        data.frame(VAR1 = 'foo',VAR2 = 'bar') %>% 
        mutate(geom = st_sfc(pol)) %>% 
        st_as_sf()

# sf object w/ multi-polygon: sf_mpol

sf_mpol <-
        data.frame(VAR1 = 'foo',VAR2 = 'bar') %>% 
        mutate(geom = st_sfc(mpol)) %>% 
        st_as_sf()

# combined sf's, geometry type: GEOMETRY

sf_geometry <- rbind(sf_pol,sf_mpol)

sf_geometry

# attempt to write the sf object (currently both fail)
sf_geometry %>% 
        st_write(dsn = '.',layer = 'test',driver = 'ESRI Shapefile')

sf_geometry %>% 
        st_write(dsn = 'test.gpkg',driver = 'GPKG')
```

**Comment by edzer** [comment]
This is what [Paul Ramsey](https://twitter.com/pwramsey/status/783727762347470848) predicted. You can of course coerce everything to `GEOMETRYCOLLECTION`, then write GPKG. In the case above, you'd coerce to `MULTIPOLYGONS` to keep life easy. Before we rush into doing this however, I want to see real use cases instead of toy exercises. `st_read` for instance allows you to (try to) force into a particular type.

**Comment by tiernanmartin** [comment]
Patience seems like a good approach with this one.

In the meantime, you might consider adding a few examples of geometry coercion to the vignette. 

For instance:
- `POLYGON` to `MULTIPOLYGON`
- single-type to `GEOMETRYCOLLECTION`
- `GEOMETRYCOLLECTION` to `GEOMETRY`

It seems like these conversions will be important steps when users want to read or write mixed-type `sf` objects, not to mention when they need to convert `sf` to `sp`.

**Comment by tiernanmartin** [comment]
For instance...

Using the objects from the [test above](https://github.com/edzer/sfr/issues/56#issue-187587247), how would I subset `sf_geometry` to return an `sf` object with `geometry type:  POLYGON`?

```
sf_geometry[1,]
## Simple feature collection with 1 feature and 2 fields
## geometry type:  GEOMETRY
## dimension:      XY
## bbox:           xmin: 0 ymin: 0 xmax: 3 ymax: 4
## epsg (SRID):    NA
## proj4string:    NA
##   VAR1 VAR2                           geom
## 1  foo  bar POLYGON((0 0, 1 0, 3 2, 2 4...
```

**Comment by edzer** [comment]
In your first example, we can now do

    st_cast(sf_geometry, "MULTIPOLYGON")

to give a
```

Simple feature collection with 2 features and 2 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 4 ymax: 4
epsg (SRID):    NA
proj4string:    NA
  VAR1 VAR2                           geom
1  foo  bar MULTIPOLYGON(((0 0, 1 0, 3 ...
2  foo  bar MULTIPOLYGON(((0 0, 1 0, 3 ...
```
alternatively,
```

Simple feature collection with 2 features and 2 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 4 ymax: 4
epsg (SRID):    NA
proj4string:    NA
  VAR1 VAR2                           geom
1  foo  bar MULTIPOLYGON(((0 0, 1 0, 3 ...
2  foo  bar MULTIPOLYGON(((0 0, 1 0, 3 ...
Warning message:
In chkOne(x) :
  object does not have length one: casting causes information loss
```
passes, but warns that information got lost (the second multipolygon ring).

**Comment by edzer** [comment]
See also [here](https://edzer.github.io/sfr/articles/sf3.html).

**Comment by tiernanmartin** [comment]
I'm looking forward to cleaning up my type transformations with `st_cast()` and will let you know if I stumble across any unexpected behavior.

Thanks for adding this function that so neatly addresses my use case!

**Comment by edzer** [comment]
Great; it surely needs more testing, and possibly more thinking.

**Comment by edzer** [comment]
This was also mentioned in #87 and closes with https://github.com/edzer/sfr/commit/e46f34a3377dfef2666b50c47d922940a4f70314
