### ISSUE TITLE
stringsAsFactors = FALSE not working

### ISSUE THREAD

**Issue by kendonB** [edzer/sfr#57]
Here are a couple of tests to be added in test_read.R

```
test_that("stringsAsFactors = FALSE produces a data.frame with no factors", {
  nc <-  st_read(system.file("shape/nc.shp", package="sf"), "nc", crs = 4267,
                 stringsAsFactors = FALSE)
  expect_false(any(sapply(nc, class) == "factor"))
})

test_that("stringsAsFactors = TRUE produces a data.frame with factors", {
  nc <-  st_read(system.file("shape/nc.shp", package="sf"), "nc", crs = 4267,
                 stringsAsFactors = TRUE)
  expect_true(any(sapply(nc, class) == "factor"))
})

```

**Comment by kendonB** [comment]
Also, can I make a plug for actually removing the option and making ``character`` always the default, as is done in the ``tidyverse``? There is [no longer any memory benefit](http://simplystatistics.org/2015/07/24/stringsasfactors-an-unauthorized-biography/) and it makes for more error-prone code. Other than consistency with the way base-R works, I don't know of any argument for stringsAsFactors. I also don't know of any argument for this particular consistency with base-R.

**Comment by Nowosad** [comment]
Alternatively, keeping the option but making character the default.

**Comment by edzer** [comment]
Thanks! I closed this issue. If you want to fight the tidyverse crusade, please do it somewhere else, e.g. in issue 3 of https://github.com/rstats-db/odbconnect. I am in favor of user choice, and users now have the choice to have strings automatically read as character. I don't think that consistency with base R is a moot point. As we're dealing with statistical data, factors are in many cases more meaningful than character strings. If you're not working with statistical data, why use R? Try plotting a numeric variable against a character variable:
```

> plot(b~a, data.frame(a = c("a", "b", "a"), b = 1:3))
> plot(b~a, data.frame(a = c("a", "b", "a"), b = 1:3, stringsAsFactors = F))
Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In xy.coords(x, y, xlabel, ylabel, log) : NAs introduced by coercion
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf
```
