### ISSUE TITLE
What about the M component?

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#6]
There is some discussion on gdal-dev about the M-component (measure) when points are not just 2D. There is an open issue on the handling of M as an attribute in non-POINT features. Z and M are present in OGC.

**Comment by edzer** [comment]
Thanks for the pointer!

**Comment by rsbivand** [comment]
https://trac.osgeo.org/gdal/wiki/rfc61_support_for_measured_geometries just appeared, with some ideas and links to github repo.

**Comment by edzer** [comment]
The standard defines 17 x 4 = 68 different classes, but I bet that implementations that implement are very rare and that 99.99% of the use cases use less than 10 classes. I find it pretty unclear why you'd want an M attribute e.g. for polygon vertices. Measurement error?

**Comment by rsbivand** [comment]
The GDAL RFC is in process of being approved no, Ari Jolma is pushing this. One underlying motivation seems to be to disambiguate XYZ from XYM. I agree that this isn't sensible design, but we need to watch what upstream software is doing. GEOS is still only XY, I think.

**Comment by rsbivand** [comment]
There is a lot of on-going discussion on gdal-devel about Z and M; there are recent "discoveries" about the Shapefile spec., and the ISOWKT dialect (which I think rgeos doesn't use) What do we know about Tibco's wkb package?

http://lists.osgeo.org/pipermail/gdal-dev/2016-January/043544.html
http://lists.osgeo.org/pipermail/gdal-dev/2016-January/043583.html
http://lists.osgeo.org/pipermail/gdal-dev/2016-February/043622.html
http://lists.osgeo.org/pipermail/gdal-dev/2016-February/043670.html
http://lists.osgeo.org/pipermail/gdal-dev/2016-February/043731.html

**Comment by mdsumner** [comment]
I hope that the tools that read from formats don't apply formal classes. The way I see this is that the read tools should be low-level and just return lists of data in whatever form is closest to the way they are read from data sources. Then we can have multiple interpretations of those data, one that matches the OGC defs but not precluding others.  

I consider it a fatal limitation that sp and rgdal cannot read a Z or Z-M line for example, just because there's no class for the the line with x-y-z[-m]. I'd like to see the read capabilities of rgdal return generic data that is unclassed, and then packages can provide classes to ingest those generic data. I don't consider it the business of the read tool to have opinions about whether it makes sense, it should just read what is there and return it. Then we can put interpretations on it with other definitions, allowing others to do the same to their own wishes. Personally it works for me to have everything as tables, and I know that's not what everybody wants. I do want this project to be as general as possible.

**Comment by edzer** [comment]
We know about Ian's wkb package that it supports the 7 common sf types (point, linestring, polygon, multipoint, multilinestring, multipolygon, geometrycollection) for xy only. `sf` now supports the 10 types described by [OGC](http://www.opengeospatial.org/standards/sfa) (7 + TIN, Polyhedralsurface and Triangle), all for xyz, xym, xyzm. Where can I find the WKB description for (multi)curve and (multi)surface?

**Comment by edzer** [comment]
Has anyone seen some XYM or XYZM data in the wild, for testing?

**Comment by mdsumner** [comment]
There is this recently https://lists.osgeo.org/pipermail/gdal-dev/2016-August/045080.html

I did have a pretty decent collection some years ago for testing Eonfusion, so I'll see if I can get that again.

**Comment by edzer** [comment]
That would be great! This one works too:
```
> s = st_read(".", "OSMPTrails")
Reading layer OSMPTrails from data source . using driver "ESRI Shapefile"
features:       296
fields:         19
converted into: MULTILINESTRING
proj4string:    +proj=lcc +lat_1=39.71666666666667 +lat_2=40.78333333333333 +lat_0=39.33333333333334 +lon_0=-105.5 +x_0=914401.8288999998 +y_0=304800.6096 +ellps=GRS80 +units=us-ft +no_defs 
> st_geometry(s)
Simple feature collection with 296 features
feature type: MULTILINESTRING
dimension:    XYM
bbox:         xmin: 3026152 ymin: 1211608 xmax: 3103033 ymax: 1285332
epsg (SRID):  NA
proj4string:  +proj=lcc +lat_1=39.71666666666667 +lat_2=40.78333333333333 +lat_0=39.33333333333334 +lon_0=-105.5 +x_0=914401.8288999998 +y_0=304800.6096 +ellps=GRS80 +units=us-ft +no_defs 
precision:    double (default; no precision model)
First 5 geometries:
MULTILINESTRINGM((3071408.93954194 1272447.4367... 
MULTILINESTRINGM((3074097.4292437 1272167.43431... 
MULTILINESTRINGM((3066193.88763611 1270065.2711... 
MULTILINESTRINGM((3068955.52876636 1273462.1462... 
MULTILINESTRINGM((3064128.40259385 1271623.7703... 
```

**Comment by mdsumner** [comment]
[storms_xyzm.zip](https://github.com/edzer/sfr/files/499846/storms_xyzm.zip)

[storms_xyzm_feature.zip](https://github.com/edzer/sfr/files/499855/storms_xyzm_feature.zip)

I dug up Eonfusion and wrote the storms data from trajectories into an xyz (x, y, PR) and xyzm (x, y, PR, time) shapefiles. time is just a numeric version of the R POSIXct type. 

I have two copies of each form, one with feature attributes and one without.  sf doesn't like them without, and this could be handled at the R level afaics. 

Would you consider allowing st_read to read the first layer always by default? It could inform that there are other layers, and what it has chosen (much like raster() does). Or do you think that belongs in a higher level wrapper? 

```R
r <- st_read("C:\\Temp\\sfr\\data\\storms_xyz_feature.shp", "storms_xyz_feature")
```
```
Reading layer storms_xyz_feature from data source C:\Temp\sfr\data\storms_xyz_feature.shp using driver "ESRI Shapefile"
features:       71
fields:         1
geometry type:  LINESTRING
```
```
 ogrinfo . storms_xyz -so
```
```
INFO: Open of `.'
      using driver `ESRI Shapefile' successful.

Layer name: storms_xyz
Metadata:
  DBF_DATE_LAST_UPDATE=2124-09-29
Geometry: 3D Line String
Feature Count: 71
Extent: (-102.200000, 8.300000) - (0.000000, 59.500000)
Layer SRS WKT:
(unknown)
```

```bash
 ogrinfo . storms_xyzm -so
```

```
INFO: Open of `.'
      using driver `ESRI Shapefile' successful.

Layer name: storms_xyzm
Metadata:
  DBF_DATE_LAST_UPDATE=2124-09-29
Geometry: Measured Line String
Feature Count: 71
Extent: (-102.200000, 8.300000) - (0.000000, 59.500000)
Layer SRS WKT:
(unknown)
```

From sf I get this: 

```R
 r <- st_read("C:\\Temp\\sfr\\data\\storms_xyz.shp", "storms_xyz")
```
```
Reading layer storms_xyz from data source C:\Temp\sfr\data\storms_xyz.shp using driver "ESRI Shapefile"
features:       71
fields:         0
geometry type:  LINESTRING
Error in `[[<-.data.frame`(`*tmp*`, nm, value = list(c(-50.8, -51.2, -51.5,  : 
  replacement has 71 rows, data has 0

```R
r <- st_read("C:\\Temp\\sfr\\data\\storms_xyzm.shp", "storms_xyzm")
```
```
Reading layer storms_xyzm from data source C:\Temp\sfr\data\storms_xyzm.shp using driver "ESRI Shapefile"
features:       71
fields:         0
geometry type:  LINESTRING
Error in `[[<-.data.frame`(`*tmp*`, nm, value = list(c(-50.8, -51.2, -51.5,  : 
  replacement has 71 rows, data has 0
```

**Comment by edzer** [comment]
Thanks for the examples; `st_read` on sf without attributes now work, both data sets come out fine. I decided to have this return `sf` objects (`data.frame`) with only a geometry column, so that you can insert attributes right away.

**Comment by edzer** [comment]
Added the shapes above to `inst/shape`, added testing code to read them to `tests/read.R`. OK to close this as an issue?
