### ISSUE TITLE
empty raw WKB policy

### ISSUE THREAD

**Issue by mdsumner** [edzer/sfr#73]
With an empty WKB element I get errors, whether by pureR or not: 

```R
library(RODBC)
## not reproducible without Manifold and mdsumner/manifoldr installed
mfile <- "... ManifoldDVD\\Data\\Europe\\Hydrography.map"
con <- manifoldr::odbcConnectManifold(mfile)
x <- sqlQuery(con, "SELECT ID, CGeomWKB(Geom(ID)) AS [geom]  FROM [Hydrography Table]")
library(sf)
sf_geom_name <- "geom"
 
x[[sf_geom_name]] <- sf::st_as_sfc(structure(x[[sf_geom_name]], class = "WKB"), EWKB = FALSE)

#Error in eval(substitute(expr), envir, enclos) : 
 # non native endian: use pureR = TRUE

x[[sf_geom_name]] <- sf::st_as_sfc(structure(x[[sf_geom_name]], class = "WKB"), EWKB = FALSE, pureR = T)
#Error in readBin(rc, what = "integer", n = 1L, size = 4L, endian = endian) : 
#  invalid 'swap' argument

```

Here's what the empty geom and its neighbour look like: 

```R
x$geom[55285:55286]
[[1]]
raw(0)

[[2]]
  [1] 01 03 00 00 00 01 00 00 00 09 00 00 00 00 00 00 00 bc 43 10 41 00 00 00 00 c6 33 23 41 00 00 00 00 cc 43 10 41 00 00 00 00 7a 33 23 41 00 00
 [48] 00 00 38 46 10 41 00 00 00 00 7a 32 23 41 00 00 00 00 6c 49 10 41 00 00 00 00 a2 31 23 41 00 00 00 00 60 4a 10 41 00 00 00 00 c4 31 23 41 00
 [95] 00 00 00 78 4a 10 41 00 00 00 00 12 32 23 41 00 00 00 00 bc 48 10 41 00 00 00 00 ce 32 23 41 00 00 00 00 68 46 10 41 00 00 00 00 16 33 23 41
[142] 00 00 00 00 bc 43 10 41 00 00 00 00 c6 33 23 41
```

Should sf handle these broken cases? Is there any policy like this in the postgres work already for NULL geometries? 

I'll pursue the Manifold cast to WKB as a external problem, but it seems this could happen more generally from DB sources. 

I tried to make a reproducible example, independent of Manifold but can't get it to work, sorry.

**Comment by mdsumner** [comment]
What happens is that Manifold "Normalizes" the geometry for export, and this geometry is a degenerate polygon with no y-extent: http://www.georeference.org/forum/t133518.3

So, arguably the query should do the filtering on the Manifold side given the possibility of these degenerate outputs,, or insert a valid NULL geometry with the cast (to plug a hole in Manifold's coercion) until their WKB output is fixed. 

Still, maybe this is something for sf as well.

**Comment by edzer** [comment]
I'm not so in favor of accepting invalid WKB: where to stop? I'll solve it with the nicer error message.
