### ISSUE TITLE
Extract centroids coordinates as a matrix

### ISSUE THREAD

**Issue by rCarto** [edzer/sfr#75]
What would be the correct way to extract centroids coordinates of sf objects (I have  `sp::coordinates` in mind) ? There must something easier/cleaner than: 
``` r 
nc <- st_read(system.file("shape/nc.shp", package="sf"), "nc", crs = 4267)
st_geometry(nc) <- st_centroid(nc)
pts <- st_as_text(st_geometry(nc))
m <- matrix(data = as.numeric(unlist(strsplit(substr(pts, 7, nchar(pts)-1), split = " "))), ncol = 2, byrow = T)
```

**Comment by edzer** [comment]
You're converting coordinates to text, then to numbers again. But they are already numbers in R!

For points, try
```
nc <- st_read(system.file("shape/nc.shp", package="sf"), "nc", crs = 4267)
st_geometry(nc) <- st_centroid(nc)
pts <- do.call(rbind, st_geometry(nc))
```
for other types it is somewhat more complex: for `MULTIPOINT` and `LINESTRING` the same will work, but you loose the information which point belonged to which feature.

**Comment by rCarto** [comment]
Thanks, that's what I was looking for. I knew the "number to text to number stuff" was not  the thing to do...
