### ISSUE TITLE
Planar index

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#76]
I just noticed [RcppAnnoy](https://cran.r-project.org/package=RcppAnnoy), which, because the index is storable after building, might be a candidate for point data.

**Comment by edzer** [comment]
Do we have k-NN functions now, and should they be part of a package providing simple feature access?

**Comment by rsbivand** [comment]
No we don't, this is "future-proofing". The GEOS STRTree is used a little in rgeos (could be more, but prepared geometries aren't predicate-ready), but only easily searches for intersecting envelopes, which don't work for points. We know too little yet about vector tiling, but indexing seems to be needed for that. GPKG has RTree Spatial Indexes extensions, I guess others will be close soon. I can't predict where this is going, but if spatial is big, then indices will be part of the solution.

**Comment by edzer** [comment]
> but prepared geometries aren't predicate-ready

what did you mean by that remark?

**Comment by rsbivand** [comment]
Do not recall now. The underlying idea IIRC was to try to prepare for vector tiling by providing a stored and update-able index as an adjunct to a geometry column. I haven't got any further.

**Comment by edzer** [comment]
The current implementation computes indexes on the fly for most binary operations, and discards them afterwards; see http://r-spatial.org/r/2017/06/22/spatial-index.html
