### ISSUE TITLE
st_write_db enhancements

### ISSUE THREAD

**Issue by onehundredpercenttexan** [edzer/sfr#77]
Maybe this function could use `'drop if exists'` if available or wrap `'drop table'` in a `tryCatch`.
Also, it currently doesn't seem to be able to append or update an existing table. 

Here are a couple other things that I expected to work:

`#does not pass schema/table on to dbWriteTable`
`st_write_db(conn = pg_con, obj = nc, table = c("public", "sf_test_nc"))`

`# does not pass row.names on to dbWriteTable`
`st_write_db(conn = pg_con, obj = nc, table = "sf_test_nc", row.names = FALSE)`

**Comment by edzer** [comment]
Thanks!

I added a `try_drop`, but am not sure it matters; it seems an error was emitted but didn't stop the process with `dropTable` (now renamed to `drop_table`).

I am not sure the append will work: we're writing the complete attribute table first with `dbWriteTable` and that does not seem to have an append mode.

The `table = c("public", "sf_test_nc")` should work now;

I haven't seen `row.names=FALSE` documented anywhere in the DBI/RPostgreSQL docs.

**Comment by onehundredpercenttexan** [comment]
I just finished some testing and it seems that `try_drop` argument works now until I manually drop the table first by executing `dbGetQuery(pg_con, "drop table if exists myschema.sf_test_nc")`.
 It then subsequently fails on the first try with this message:
`Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  table "sf_test_nc" does not exist
)
Warning message:
In postgresqlQuickSQL(conn, statement, ...) :
  Could not create executedrop table sf_test_nc ;`
...and then works on every attempt thereafter.

There are a few references to `row.names` here: https://cran.r-project.org/web/packages/RPostgreSQL/RPostgreSQL.pdf. 

Also, the `append` argument is not writing new records as would be expected and  and `st_read_db` doesn't seem to parse this: `table = c("myschema", "sf_test_nc")`.

**Comment by onehundredpercenttexan** [comment]
I also would like to mention that the geometry columns in PostgreSQL are not getting an SRID set.

**Comment by edzer** [comment]
Should all work now; please reopen if it doesn't.
