### ISSUE TITLE
Copying proj-datumgrids to Windows and OSX binary packages

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#78]
The current proj-datumgrids file should be unpacked in the nad/ directory of the proj source tree before proj is compiled and installed. From proj-datumgrids 1.6, the contents may also be added to share/proj, or maybe to sfr/proj, but historically grid *.lla files needed conversion with nad2bin during the installation of proj itself.

See [current proj-datumgrid](http://download.osgeo.org/proj/proj-datumgrid-1.6.zip), with many other candidate grids that users can employ [here](https://github.com/OSGeo/proj.4/wiki).

For Windows, the files are copied in rgdal using rgdal/configure.win, and the same could be done for sfr. For OSX (as a Unix variant but built static), look at rgdal/configure.in lines from 415 and so on - they were written for Simon Urbanek. So configure args --with-data-copy=yes should trigger what configure.win does on Windows, that is adding the installed share/proj and share/gdal to R_PACKAGE_DIR.

**Comment by edzer** [comment]
Both win and osx binaries on CRAN now have datumgrids.
