### ISSUE TITLE
Building OSX GDAL/PROJ.4/GEOS and ext-deps for GDAL drivers

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#79]
I guess we still need --enable-shared=no in PROJ, and in GDAL --with-static-proj4=<PATH> and  --enable-shared=no. I believe CRAN had a good view of this, but I don't know where their logs are. GDAL drivers are important, and should also be built static (I guess).

**Comment by edzer** [comment]
For the record, Simon Urbanek's message on 13/12/16:
```
>

The current flag overrides are in are in

https://svn.r-project.org/R-dev-web/trunk/QA/Simon/packages/flags.inst/
https://svn.r-project.org/R-dev-web/trunk/QA/Simon/packages/preconf/

If you need custom settings, you'll have to let me know. rgdal has

--configure-args='--with-data-copy=yes --with-proj-data=/usr/local/share/proj'

is that what you want as well?

Cheers,
Simon
```
