### ISSUE TITLE
Curve and surface in OGR SFS

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#8]
Heads up for this ticket and associated thread

https://trac.osgeo.org/gdal/ticket/6401

This is for the Z/M/ZM changes, and related to getting GPKG up to full spec.

**Comment by edzer** [comment]
No news, pls reopen if there is anything unexpected. sf should support all 17 x 4 simple feature types.

**Comment by etiennebr** [comment]
When you said reopen, I guess this issue should be closed.
