### ISSUE TITLE
st_transform will not handle +proj=obtrans

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#81]
Just a placeholder - see the obtrans notes in rgdal::project and rgdal::spTransform. For its own reasons, proj swaps from and to crs here.

**Comment by edzer** [comment]
Where is this documented? I cannot find it in the documentation objects you mention.

**Comment by Nowosad** [comment]
(maybe this one?) Help page of `rgdal::spTransform`:
> The methods may take an optional argument “use_ob_tran”, default FALSE, if TRUE and “+proj=ob_tran”, use General Oblique Transformation with internalised from/to projection reversal (the user oblique transforms from longlat to oblique forward rather than inverse as suggested in PROJ.4 mailing list postings); these changes are intended to meet a need pointed out by Martin Ivanov (2012-08-15).

**Comment by rsbivand** [comment]
Right, obtrans is a special case where the user has to assign the SRS the wrong way round, for unknown reasons. The logic in rgdal::project results in the correct result. Yes, it is a special case, but it does occur when using numerical model output.

**Comment by edzer** [comment]
sf now does transformations by gdal (OGR/SRS), and it looks like gdal does not support `ob_tran` as a CRS. This means that this only could become possible if we directly use `PROJ.4`, bypassing gdal, to do the transformations.

**Comment by edzer** [comment]
See also #651 .
