### ISSUE TITLE
as() does not work to convert to sf

### ISSUE THREAD

**Issue by Robinlovelace** [edzer/sfr#84]
```r
data("meuse.grid_ll")
# obj_sf = as(meuse.grid_ll, "sf") # fails
obj_sf = st_as_sf(meuse.grid_ll) # works
obj_sp = as(obj_sf, "Spatial") # works
```

Minor issue as is possible with `st_as_sf` but would make it compatible with `as(obj_sf, "Spatial")`. 

Checked for instances of `as(` in the vignette and only found converting to `Spatial` objects in there.

**Comment by Robinlovelace** [comment]
This is the relevant vignette part btw: https://github.com/edzer/sfr/blob/master/vignettes/sf1.Rmd#conversion-including-to-and-from-sp

**Comment by edzer** [comment]
Thanks!

**Comment by Robinlovelace** [comment]
Fast work! BTW do you have any plans to implement `spsample` in **sf** soon (assuming you've not already, can't see it) - one of the many useful functions in **sp** that I look forward to using in simple features world.

**Comment by edzer** [comment]
Plans yes, but it's midway my priority list; fixing CRAN issues (mac port) and documentation on the top. Dec 6-9 Roger will visit, and we'll try to get some things done.

**Comment by Robinlovelace** [comment]
Awesome news, great work.

**Comment by Robinlovelace** [comment]
P.s. if there's a 'Robin shaped chunk' of work to do on this (e.g. documentation), send my way!

**Comment by rsbivand** [comment]
Visit 4-7 Dec, loan of OSX machine arranged
