### ISSUE TITLE
error on CRAN flavor fedora-gcc

### ISSUE THREAD

**Issue by edzer** [edzer/sfr#85]
Can anyone reproduce what the [CRAN farm does for sf 0.2-5 on platform r-devel-linux-x68_64-fedora-gcc](https://cran.r-project.org/web/checks/check_results_sf.html)?

Output is given [here](https://cran.r-project.org/web/checks/check_results_sf.html); it gives a warning (in tests becoming an error) on:
```

library(testthat)
library(sf)
x = st_sfc(list(st_point(0:1), st_point(0:1)))
y = x
(st_crs(y) <- 4326)
expect_silent(st_crs(y) <- 4326)
expect_warning(st_crs(y) <- 3857)
x = st_sfc(list(st_point(0:1), st_point(0:1)), crs = 4326)
expect_silent(st_sfc(x, crs = "+proj=longlat +datum=WGS84 +no_defs"))
expect_silent(st_sfc(x, crs = "+proj=longlat +datum=WGS84"))

```
sf 0.2-4 had the +no_defs, 0.2-5 removed the +no_defs (I recalled old gdal or proj versions didn't have it). I also remember @rsbivand  mentioning that gdal's ability to do epsg -> proj4string -> epsg etc doesn't work as you'd hope -- this might be a case. I'd be happy to remove this test, but would like to understand first.

**Comment by rsbivand** [comment]
Running current sfr/sf on (2016-11-24 r71686) on Fedora 25 shows no issues on "Linking to GEOS 3.6.0, GDAL 2.1.2" and proj 4.9.3. However - what is this (occurred looking inside sf:::"st_crs<-.sfc"):

```
Browse[2]> make_crs("+proj=longlat +datum=rubbish +no_defs")
$epsg
[1] NA

$proj4string
[1] "+proj=longlat +ellps=WGS84 +no_defs"

attr(,"class")
[1] "crs"
```

There are lots of minor differences in the tests (different GDAL and GEOS versions, different absolute locations of the sf.Rcheck directories.

**Comment by edzer** [comment]
Black magic? `OGRSpatialReference::importFromProj4` is a function with nearly 1000 lines...

**Comment by rsbivand** [comment]
Oopps:

```
> library(sp)
> CRS("+proj=longlat +datum=rubbish +no_defs")
Error in CRS("+proj=longlat +datum=rubbish +no_defs") : 
  unknown elliptical parameter name
> library(sf)
Linking to GEOS 3.6.0, GDAL 2.1.2
> sf:::make_crs("+proj=longlat +datum=rubbish +no_defs")
$epsg
[1] NA

$proj4string
[1] "+proj=longlat +ellps=WGS84 +no_defs"

attr(,"class")
[1] "crs"
```

and OGRSpatialReference::importFromProj4 is taking liberties compared to proj4. See ogr/ogr_srs_proj4.cpp line 1084:

`/* If we don't recognise the datum, we ignore it */`

and line 1134:

`Can't find ellipse definition, default to WGS84`

**Comment by edzer** [comment]
Also:
```
> st_crs("+proj=longlat")
$epsg
[1] 4326

$proj4string
[1] "+proj=longlat +ellps=WGS84 +no_defs"

```
