### ISSUE TITLE
more informative error message on as-Spatial Z not supported?

### ISSUE THREAD

**Issue by jsta** [edzer/sfr#86]
I tried to convert an `sf` object to `Spatial` and recieved this message:

```r
foo <- sf::st_read(foo_conn, foo_layer)
foo_sp <- as(foo, "Spatial")

```

> Error in StopZ(zm) : Z not supported

I realized after looking through the manual that I should use the `sf::st_drop_zm` function. I wonder if a notice about this function could be added to the error text to make it more informative?

Happy to submit a PR if this is deemed a good idea.

**Comment by edzer** [comment]
Great, sounds like a good idea!
