### ISSUE TITLE
GDAL 2.1.0 out

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#9]
Please note:

https://lists.osgeo.org/pipermail/gdal-dev/2016-May/044242.html

http://trac.osgeo.org/gdal/wiki/Release/2.1.0-News

https://trac.osgeo.org/gdal/wiki/rfc61_support_for_measured_geometries

https://trac.osgeo.org/gdal/wiki/rfc59.1_utilities_as_a_library

https://trac.osgeo.org/gdal/wiki/rfc48_geographical_networks_support

**Comment by edzer** [comment]
Now integrated in rwinlib: https://github.com/rwinlib/gdal2
