### ISSUE TITLE
ST_Azimuth

### ISSUE THREAD

**Issue by faridcher** [edzer/sfr#93]
is there any reason we don't have the very useful [`ST_Azimuth`](http://postgis.net/docs/manual-dev/ST_Azimuth.html) ? I suppose this function is not part of GEOS API. Even in this case, writing one wouldn't be so difficult! Is there any roadmap for `sf` package which includes the future features such as this one?

**Comment by edzer** [comment]
Is it defined in the simple feature standard?

**Comment by faridcher** [comment]
Ok, it is not; but don't you think it is important for `sf` to have this function? converting `sf` to `sp` and using other packages (or `sp` itself) for computing `Azimuth` is not pleasant. This is the first function I felt the need and realized that it is not there. 
From the moment I encountered `sf`, I found it very useful, and the reason being that geographical-minded people are familiar with SF. It kind of workarounds the messy spatial ecosystem of R. 
Although the `sf` is in it initial phase of growth, I was wondering if there is a plan to step a little further and include crucial NON-SF functions, such as `ST_Azimuth` etc.

**Comment by rsbivand** [comment]
And indeed GEOS requires planar geometries, while azimuth is more typically a relation between geographical coordinates. So both sets need checking first to see that they are not projected and have the same +ellps and +towgs84 specs, then azimuth values need to be calculated. You are welcome to contribute to an sf version of maptools, but this isn't sf. Life is always without exception messy, so attempts to add everything to sf will make it messy too, which is not the goal here.

**Comment by faridcher** [comment]
@rsbivand 
I see a few member functions in [GEOS doc](http://geos.osgeo.org/doxygen/classgeos_1_1algorithm_1_1Angle.html#details) for computing `angle`, though they are for planar geometries. 

Here, we can follow the convention of postgis `ST_Azimuth`: 
if the geometries are planar (geometric):
![image](https://cloud.githubusercontent.com/assets/9982519/20859436/281af490-b92d-11e6-84e8-19ccf5b1a078.png)

otherwise, for geographical coordinates (L:longitude, phi:latitude) :
![image](https://cloud.githubusercontent.com/assets/9982519/20859438/37e0661c-b92d-11e6-92b5-ca55d85104e6.png)

**Comment by rsbivand** [comment]
No, the second formula is an approximation only, see the documentation underlying maptools::gzAzimuth. Because something is in PostGIS is not a good reason to break the R practice of keeping packages as modular as reasonable (but not more so - too many packages is also not good).

**Comment by faridcher** [comment]
I updated the formula. Thanks for the hint.
I also extremely disagree with profilteration of packages. As a relatively new user of R, I found it failrly painful to find a suitable function for a purpose. Most of the time you find the function and then you have to find a way to intercommunicate between different packages which is again very disappointing. I believe `sf` should have some other preliminary functions such st_azimuth integrated with the simple feature, though it is not part of the OGC spec. 

So by contributing do you mean, writing this function and submitting a pull request for `sf`? I will be more than happy to do so.

**Comment by edzer** [comment]
I don't think it is allowed to copy [wikipedia content](https://en.wikipedia.org/wiki/Azimuth#Cartographical_azimuth) without attributing the source. Please add the attribution or (better) replace the content with a link to it.

**Comment by faridcher** [comment]
I  have implemented a generic version of this function. Now it only works `sfc_POINT`. It computes the pair-wise azimuth of coordinates. There is a dependency on maptools::gzAzimuth function which I think should be resolved. 
please see if it is ok to submit a PR:

```R
# this function is borrowed from sp::isProjected
is_projected <- function (p4str)
{
  if (is.na(p4str) || !nzchar(p4str))
    return(as.logical(NA))
  else {
    res <- grep("longlat", p4str, fixed = TRUE)
    if (length(res) == 0)
      return(TRUE)
    else return(FALSE)
  }
}

st_azimuth <- function(x,y,...) UseMethod("st_azimuth")
#fallback method
st_azimuth.default <- function(x,y,...) "st_azimuth is only implemented for sfc_POINT"

st_azimuth.sfc_POINT <- function(x,y,type = "snyder_sphere"){
  x_crd <- do.call(rbind,x)
  y_crd <- do.call(rbind,y)

  prj4str <- st_crs(x)$proj4string
  is_proj <- is_projected(prj4str)

  if(is.na(is_proj) || is_proj)
  {
    if (is.na(is_proj))
      warning("unknown proj4string, assuming coordinates are projected...")
    z_x <- complex(real = x_crd[,1],imaginary = x_crd[,2])
    z_y <- complex(real = y_crd[,1],imaginary = y_crd[,2])
    azi <- Arg(z_x-z_y)
  }
  else
    azi <- sapply(1:nrow(x_crd),function(i) maptools::gzAzimuth(x_crd[i,],y_crd[i,],type=type))
  return(azi)
}

#example
nc <- st_read(system.file("shape/nc.shp", package="sf"), "nc", crs = 4267)
nc_cent <- st_centroid(nc)

#nc_cent crs is NA
(azimuths <- st_azimuth(nc_cent,rev(nc_cent)))

st_crs(nc_cent) <- st_crs(nc) #reported bug/patch 96
#nc_cent crs if longlat
```

**Comment by edzer** [comment]
Dependency on maptools is a no-go. In case you have in mind copy over code, you need to sort out the ownership and this may have to go into the DESCRIPTION:Contributor field - potentially another no-go.

**Comment by faridcher** [comment]
I will develop my own version of `maptools::gzAzimuth` to remove the dependency on maptools very soon.
Regarding the ownership, feel free to include these codes in `sf` package; it's ok if you are not so inclined to include me in the contributor field. I will continue to contribute to `sf` by providing bug-fixes and other useful functions because I believe a thorough standard spatial package like `sf` is a must for R community. If you thought my contribution is at the level that should be mentioned in the CONTRIBUTOR field, It would my honor.
thanks

**Comment by edzer** [comment]
Thank you for your offer. I think I will prefer to reuse `geosphere::bearing`, as it can take care of the `st_crs`-specific ellipsoidal parameters, similar to what I now do with `st_distance` and the like. I'm pretty sure maptools does not do that and am not sure you had that in mind.

**Comment by faridcher** [comment]
I thought `st_distance` could handle geographical crs! Now I see that it only call the `GEOS` routines which are all geometrical. I suppose `maptools` only works with spherical earth though. 
I infer that you would like to implement it yourself, however if you wanted me to implement it based on `geosphere`, let me know.

**Comment by edzer** [comment]
Your local copy may be out of sync with the github version; please update and test, this is all pretty fresh.

**Comment by edzer** [comment]
You can always do now
```
> geosphere::bearing(st_multipoint(rbind(c(0,0),c(2,1))), st_multipoint(rbind(c(3,3),c(1,1))))
[1]  45.15296 -89.99127
```

**Comment by faridcher** [comment]
@edzer  could you please expose `geos::algorithm::Angle` to sf (like `CPL_geos_dist(x, y)`)?

thanks

**Comment by edzer** [comment]
No, for geos we are constrained to the [c api](https://geos.osgeo.org/doxygen/geos__c_8h_source.html), which does not include an angle function. 

Bit it isn't' hard to get them, using `atan2`:
```r
> do.call(atan2, rev(as.list(st_point(c(1, 1)) - st_point(c(0,0))))) * 180/pi
[1] 45
```
For directions on the sphere, we can use [s2](https://github.com/spatstat/s2).

**Comment by faridcher** [comment]
I have written a st_azimuth generic method and implemented it for sfc_POINT, sfc_LINESTRING, and sf classes which works on planar and geodetic CRS. 
```
remotes::install('faridcher/sfextra')
library(stextra)
?st_azimuth
```
