### ISSUE TITLE
what is the effect of precision?

### ISSUE THREAD

**Issue by faridcher** [edzer/sfr#98]
precision has no effect in the `st_sfc` or `st_as_binary`:
```
pt1 <- st_point(c(6.2155,14540.5456))
pt2 <- st_point(c(1,1))
(sfc <- st_sfc(pt1, pt2,precision = .01))
```

These are the same:
```
st_as_binary(sfc,precision = .01)
st_as_binary(sfc)
```
In the code behind of `st_sfc`, it only sets the attributes of precision:
```
...
attr(lst, "precision") = precision
...

```
Is it not implemented yet?!

**Comment by edzer** [comment]
It is: sfc -> binary does it (and all GDAL or GEOS operations take this route), in your example above precision was an attribute of `sfc`, hence the identical results form `st_as_binary`. You need to round-trip to see it:
```
> st_as_sfc(st_as_binary(st_sfc(pt1, pt2, precision = 100)))
Geometry set for 2 features 
geometry type:  POINT
dimension:      XY
bbox:           xmin: 1 ymin: 1 xmax: 6.22 ymax: 14540.55
epsg (SRID):    NA
proj4string:    NA
POINT(6.22 14540.55) 
POINT(1 1) 

```
